### ISSUE TITLE
QUESTION: Does this client library automatically use gRPC? Or is that something that needs to be configured?

### ISSUE THREAD

**Issue by edwmurph** [googleapis/nodejs-dialogflow#105]
From [a Dialogflow doc website](https://dialogflow.com/docs/reference/v1-v2-migration-guide-api) I see this:

> Dialogflow's V2 SDKs use gRPC, which allows you to call Dialogflow's APIs more efficiently. If you make a large number of API requests to Dialogflow, your application's performance may benefit from switching from REST APIs calls to a gRPC SDK. See the SDK page for Dialogflow gRPC SDKs and gRPC.io for more information on gRPC.

Just to be clear, does using this dialogflow-nodejs-client-v2 library, receive the gRPC benefits described above?

**Comment by JustinBeckwith** [comment]
Yes it does!  It automatically uses gRPC under the hood.  No changes needed from your side :)
