### ISSUE TITLE
QUESTION: Does this client work with a V1 Dialogflow agent?

### ISSUE THREAD

**Issue by edwmurph** [googleapis/nodejs-dialogflow#106]
I'm asking this because I took a working V2 agent with the following:
- a google service account configured with scopes for the Dialogflow API
- a generated service key json file
and then just toggled the agent to use the V1 API on the Dialogflow console, and then used this Dialogflow client to try calling the `detectIntent` method off a newly instantiated `SessionsClient`, and it still worked and provided back the same response structure (different `responseId`).

Is this intended behavior? Shouldn't I at least be seeing [different JSON response structures](https://dialogflow.com/docs/reference/v1-v2-mapping) when sending to the agent configured as V1/V2?

**Comment by JustinBeckwith** [comment]
@matthewayne we aren't really sure how to answer this one :) Can you take a look?

**Comment by matthewayne** [comment]
This library does not work with v1.  Please use [this client library for Dialogflow v1](https://github.com/dialogflow/dialogflow-nodejs-client).  I should note that the authentication, methods and expected requests/responses have changed from v1 to v2.
