### ISSUE TITLE
Browser error - Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by talkr-app** [googleapis/nodejs-dialogflow#109]
Samples work great from node, but trying to run from a browser is giving me an error:
'Uncaught TypeError: Cannot convert undefined or null to object' (pify:index.js 79) 

Reproduction Steps:
brunch new test
cd test
npm install dialogflow --save
echo 'const dialogflow = require("dialogflow");' >> app/initialize.js 
brunch watch --server

OS: OSX 10.13.4
Node: 10.4.1
npm: 6.1.0
dialogflow: 0.5.0

What am I doing wrong?

**Comment by JustinBeckwith** [comment]
Greetings! We're tracking browser support over in #16.  I'm going to close this one out for now :)
