### ISSUE TITLE
Issues trying to delete EntityTypes after Deleting Intents ("Entity still in use") 

### ISSUE THREAD

**Issue by AndrewKohnen** [googleapis/nodejs-dialogflow#120]
#### Environment details

  - OS: windows 10 
  - Node.js version: 8.11.3
  - npm version: 5.6.0
  - `dialogflow` version: 0.5.0

#### Steps to reproduce

  1. use List functions to gather the intents/entityTypes from an Agent with multiple custom entities
  2. create an Intents Client and an EntityTypes Client 
  3.  Using the client from 2, call delete intent on every intent based on the list from 1
  4.  Attempt to delete the EntityTypes using the same means as 3 only to get an "Entity in use" error 

#### Explanation

I wish to write a script that replaces the Intents/Entities in one agent with a set of intents/entities from local files that other programs can write to/from. This allows work on dialogflow to be done locally and deployed from a node script. To do this I acquire a list of Intents/Entities from the Dialogflow agent and delete them all one by one, then create new Intents/Entities based on  the local files one by one. I put in the necessary sleep functions as to not exceed my request limit. 

The program works fine for agents with one custom EntityType, but when I have agents with more than one custom EntityType the deleteEntityType operation fails because "Entities are still in use" even though all intents from the agent are gone. 

I confirm the successful deleting of intents by going to the dialogflow console and seeing that no intents are present. I think this is an issue where Dialogflow does not update it's state after a delete is called, so it thinks the entities are still in use. I figured a sleep period would give Dialogflow the time it needed to update it's dependencies but it was to no avail so I threw in some error catching. Any insight into this problem would be appreciated

![df bug](https://user-images.githubusercontent.com/15589181/41991913-0f9f5546-7a15-11e8-85ff-d91ff3ece39c.JPG)

Thank you for your time

**Comment by AndrewKohnen** [comment]
Sorry for the delay in my response. Are you requested more information on my end?

**Comment by aimjy** [comment]
I ran into the same issue. I tried to solve this with Promises, without any success. And I also tried a timeout Promise between the deletion of the Intent and the deletion of the Entity. And even then I got this issue. (And I tried waiting like 60s).

**Comment by aimjy** [comment]
I found a little trick to bypass this issue. I made an (almost) empty Agent. (With one intent, just the name filled in). And I use the restore Agent with this file.

**Comment by nnegrey** [comment]
Hi Praetoria88, 

Is your issue just with intents or also with entity types and entities?

Is your Agent setup like this?
- Intent 1
  - Intent 2 (follow-up intent to intent 1)
