### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by iamzhanghao** [googleapis/nodejs-dialogflow#123]
https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/87e4f897c480a285d18dadf913aab2533819db0e/samples/detect.js#L195

should be `AUDIO_ENCODING_LINEAR_16`

**Comment by jrash06** [comment]
You're right. AUDIO_ENCODING_LINEAR16 is the name used by v1, for v2 it should be AUDIO_ENCODING_LINEAR_16
