### ISSUE TITLE
How do i set the platform to Google in my requestSource

### ISSUE THREAD

**Issue by syedatifakhtar** [googleapis/nodejs-dialogflow#132]
I'm trying to write some tests for my bot using the nodejs sdk client.However i do not know how to set the platform type to google for the request.We're using the conv() object in our code and since there is no platform in the request, it creates it as null and i get the following error-:

`TypeError: Cannot read property 'user' of null at exports.dialogflowFirebaseFulfillment.functions.https.onRequest`

Why do we want to use storage - some of our code is highly dependent on things already in the storage and we want to be able to test it out.

I've tried to use the payload field under queryParams, but i dont see it in the request to my fulfillment

`            request.queryParams = {
                payload : {
                    requestSource: 'ACTIONS_ON_GOOGLE'
                }
            this.sessionClient.detectIntent(request)
            };`

#### Environment details

  - Node.js version: 8.10
  - npm version: 2.7.4
  - `dialogflow` version: v2 agent

**Comment by dpretty** [comment]
I've been trying to figure this out too.

It looks like `queryParams = { payload: { source: PLATFORM}}` should work: https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/d6eabd559da897120b3037d5ad79de3e6099743b/src/v2-agent.js#L114

And the spec says that `payload` can be any arbitrary JSON object: 

https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.QueryParameters

However, no matter what I put in the `payload` object, I see an empty `payload`

`query_params {
  payload {
  }
}
`
in Dialogflow gRPC Request in the logs (I have "Log interactions to Google Cloud" activated, so I'm looking at the logs in GCP). 

So, it looks like the payload is dropped somewhere between calling detectIntent() and the query reaching dialogflow?

**Comment by juhijariwala** [comment]
Hi @syedatifakhtar and @dpretty detectIntent() takes the payload in [protobuf struct](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Struct) format :)
```
query_params {
  payload {
    fields {
      key: "source"
      value {
        string_value: "ACTIONS_ON_GOOGLE"
      }
    }
  }
}
```

Passing the payload in above format should fix your problem. You can use [structjson util](https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/samples/structjson.js) to convert the JSON object to Protobuf obejct like this.

```
const structjson = require('./structjson.js');

const request = {
    session: sessionPath,
    queryParams: {
        payload: structjson.jsonToStructProto({source: 'ACTIONS_ON_GOOGLE'})
    },
    queryInput: {
        text: {
            text: query,
            languageCode: languageCode,
        },
    },
};
```

**Comment by JustinBeckwith** [comment]
Thanks for the answer @juhijariwala!  @syedatifakhtar, please do let us know if this is still an issue.

**Comment by barrtender** [comment]
By the way, the acceptable structure changed, so if anyone wants to pass queryParams in now the library to use as of 2020-08-13 is "pb-util". This encodes the payload like this:
```
payload: {
  fields: { 
    source: { 
      kind: 'stringValue', 
      stringValue: 'ACTIONS_ON_GOOGLE' 
    }
  }
}
```
Which is slightly different. Hopefully I save someone else a week or more of toil.

**Comment by xenx-efy** [comment]
@barrtender does it look like this?
``` const request = {
            session: sessionPath,
            queryParams: {
                payload: value.encode({source: 'ACTIONS_ON_GOOGLE'}),
            },
            queryInput: {
                text: {
                    text: message,
                    languageCode: 'ru-RU',
                },
            },
        };
```
it just doesn't work. I get an empty answer, because source has not changed
