### ISSUE TITLE
Getting error: "Endpoint read failed"

### ISSUE THREAD

**Issue by HoverAlex** [googleapis/nodejs-dialogflow#15]
I'm using this client in my firebase cloud functions environment and on some request i'm getting this error: 
```
{ Error: Endpoint read failed
    at /user_code/node_modules/dialogflow/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
```

This is my request:
```
const dlg_projectId = 'XXXX';
const conversation_id = 'some id here';
const dlg_languageCode = 'de-DE';
const dlg_sessionPath = dialogflow_sessionClient.sessionPath(dlg_projectId, conversation_id);

const dlg_request = {
	session: dlg_sessionPath,
	queryInput: {
		text: {
			text: dlg_query,
			languageCode: dlg_languageCode,
		},
	},
};

dialogflow_sessionClient
	.detectIntent(dlg_request)
	.then(responses => {

		// the program does not reach this part

	}).catch(err => {
		console.error(consoleTAG, 'dialogflow ERROR:', err); // This is the error.
	});
```

Is this a known bug or am i doing something wrong?

Greets
Alex

**Comment by zelikris** [comment]
I'm seeing the same issue but it occurs only after the agent I'm sending to hasn't received any requests in about 5 minutes

**Comment by callmehiphop** [comment]
@HoverAlex @zelikris seems like there hasn't been a lot of activity here in a long while, is this something either of you are still experiencing?

**Comment by callmehiphop** [comment]
I'm going to close this out, I'm betting the latest version no longer suffers from this issue since we moved away from the C extension version of gRPC. Please let us know if the issue persists and we'll be happy to re-open!
