### ISSUE TITLE
contexts doesn't work in queryParams of detectIntent() method calling by event name 

### ISSUE THREAD

**Issue by kalanyuz** [googleapis/nodejs-dialogflow#155]
Environment details
OS: macOS 10.13.6
Node.js version: 8.11.4
npm version: 6.4.0
dialogflow version: v0.6.0

I'm experiencing the exact same problem. My payload is simple:
'cant_find_user' is already defined in the web interface.
```
{
       session: sessionPath,
         queryInput: {
           event: {
             name: 'cant_find_user',
             languageCode: languageCode,
           } 
        },
        outputAudioConfig: {
          audioEncoding: `OUTPUT_AUDIO_ENCODING_LINEAR_16`,
          sampleRateHertz: 44100
        }
      }; 
```
But default fallback intent is returned

**Comment by jrash06** [comment]
Have set `lifeSpanCount` of context? Try using a non-zero value, like 5

**Comment by nnegrey** [comment]
Closing this for now, please feel free to reopen.
