### ISSUE TITLE
outputAudio is missing in response body

### ISSUE THREAD

**Issue by YrockInnovators** [googleapis/nodejs-dialogflow#158]
OS: WIndows 10
Node.js version: 10.6.0
npm version: 6.4.1
dialogflow: REST API v2

I am trying to receive a text to speech response from dialogflow version 2 using only a text input but the outputAudioConfig is missing in the result. I already set the text to speech to true in settings and use below body which is working with text response only.

      session: "1234567",
      queryInput: {
        text: {
          text: query,
          languageCode: "en-US"
        }
      },
      outputAudioConfig: {
        audioEncoding: "OUTPUT_AUDIO_ENCODING_LINEAR_16",
      } 

Kindly need assistance.

Thanks!

**Comment by sjmn** [comment]
@YrockInnovators check that you are using the beta version:
`const dialogflow = require('dialogflow').v2beta1;`

**Comment by JustinBeckwith** [comment]
@YrockInnovators did using the latest version fix your issue?

**Comment by YrockInnovators** [comment]
I am not using dialogflow libraries in my app module. I am accessing the dialogflow endpoint through google cloud apis

**Comment by YrockInnovators** [comment]
I did try to change the url to baseURL: string = "https://dialogflow.googleapis.com/v2beta1/projects/'projectID'/agent/sessions/'sessionID':detectIntent" but still no outputAudio field included in the json response message
