### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by Knowledge91** [googleapis/nodejs-dialogflow#16]
I am using Webpack to bundle my code for the later export to my server-less architecture. Unfortunately Google-Cloud does not seem to work with the Webpack workflow? Executing the from webpack produced bundle yields the error:
```
throw new Error("package.json does not exist at " + package_json_path);
```

Do to my research this is a problem with some Google Cloud dependencies:
[https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1821](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1821)
[https://github.com/grpc/grpc/issues/11435](https://github.com/grpc/grpc/issues/11435)

and the source probably is the node-pre-gyp module:
[https://github.com/mapbox/node-pre-gyp/issues/308](https://github.com/mapbox/node-pre-gyp/issues/308)

#### Environment details

  - OS: MacOS 10.13.2
  - Node.js version: v9.3.0
  - npm version: 5.6.0
  - dialogflow version: v2

Thanks!

**Comment by ekremkenter** [comment]
Did you try to exclude it from webpack? Below configuration worked for me.

module.exports = {
  ...
  externals: ['grpc','dialogflow'],
 ...
};

**Comment by JustinBeckwith** [comment]
Greetings!  Webpack isn't currently supported, but it's something we would very much like to do.

**Comment by pavelsavara** [comment]
This workaround helps https://github.com/serverless-heaven/serverless-webpack/issues/342

**Comment by sibelius** [comment]
can we use this package on react-native?

right now we are using fetch directly like this https://github.com/innFactory/react-native-dialogflow/blob/master/js/Dialogflow_V2.js#L89

it'd be cool to have full support to react and react native

**Comment by selmertsx** [comment]
I got the same issue to use `@google-cloud/pubsub`.
So I use the cloud Pubsub REST API directory.
Why don't you do this?

```typescript
// example
import { google } from "googleapis";
import axios from "axios";
const url = "https://pubsub.googleapis.com/v1/projects/${project_name}/topics/${topic_name}:publish";

async function main() {
  const token = await google.auth.getAccessToken();
  const data = { messages: [ { data: new Buffer("hogehoge").toString("base64") }]}
  const config = {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  };
  return await axios.post(url, data, config);
}

main();
```

**Comment by ragu-swaminathan** [comment]
Is there any work around or fix available to use dialogflow in reactjs?

**Comment by bcoe** [comment]
@ragu-swaminathan, we recently removed our dependency on `grpc` (which was a compiled dependency, and made running in reactjs a complete no-go); however, there's still some work to go before this library can easily be run in the browser.

This continues to be something we are working towards, but I don't believe there are any workarounds just yet.

**Comment by callmehiphop** [comment]
@bcoe @JustinBeckwith is there a tracking issue we can ask users to subscribe to? Seems like this is applicable to all the nodejs clients.

**Comment by bcoe** [comment]
@callmehiphop if one doesn't exist, let's create a tracking issue here:

https://github.com/googleapis/google-cloud-node

I agree it would be great to eventually provide a recipe for running in the browser.

**Comment by callmehiphop** [comment]
https://github.com/googleapis/google-cloud-node/issues/2933 has been opened!
