### ISSUE TITLE
Creating multiple contexts does not always create the requested contexts

### ISSUE THREAD

**Issue by umairda** [googleapis/nodejs-dialogflow#17]
I frequently create multiple contexts at a time. The create context calls always succeed without error but I have noticed that the contexts aren't always created. If I follow my create context request with a listContexts request then at times the array of listedContexts does not include both of the contexts that I requested to create.

I created a test using largely the functions in the `dialogflow-nodejs-client-v2` to demonstrate this behavior: https://github.com/umairda/dialogflow-test-create-multiple-contexts

#### Environment details

  - OS: mac osx
  - Node.js version: 8.0.0
  - npm version: 5.5.1
  - dialogflow version: 0.1.0

#### Steps to reproduce

  1. Delete all contexts
  2. List all contexts (should be 0)
  3. Create 2 contexts
  4. List all contexts (should be 2)

If you repeat steps 1-4 over and again you will see that in step 4 only one of the two contexts that were requested to created were actually created. 

I believe the `listContexts` call is working correctly because it accurately reflects the state of my agent in dialogflow

**Comment by JustinBeckwith** [comment]
Greetings @umairda!  This issue hasn't had any action in a while.  If you're still having trouble here - let us know!

**Comment by umairda** [comment]
Hi- sorry I just got time to work on this again.

I'm still seeing the issue but it is far less frequent than before. Previously it appeared that one of the two `create context` api calls was failing. 

But now it appears that the `delete all contexts` api call doesn't always work. In particular if I use the same session id and repeat the steps 1-4 mentioned above over and again (meaning after step 4 I start over at step 1) then eventually when I list the contexts in step 2 (expect 0) I actually end up with 1 context still being set.
