### ISSUE TITLE
UpdateIntent

### ISSUE THREAD

**Issue by limpidcoder** [googleapis/nodejs-dialogflow#174]
Is there any way to update Intent and view Intent details like training phrases, message text ?

**Comment by JustinBeckwith** [comment]
cc @googleapis/ml-apis

**Comment by nnegrey** [comment]
Hi!
To update an intent you can use: [UpdateIntentRequest](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.UpdateIntentRequest)

To view intent details, you can: [ListIntents](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#listintentsrequest), [Sample](https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/resource.js#L220-L267)

or you can also view this form the console. 

Let me know if that helps!
