### ISSUE TITLE
FR: Allow to create multiple agents per project and create them through an API

### ISSUE THREAD

**Issue by rwmb** [googleapis/nodejs-dialogflow#175]
- OS: any
  - Node.js version: any
  - `dialogflow` version: 0.6.0

Hi, I've searched online and I found that you can't create agents through the API, nor you can have multiple agents in the same Google Cloud project.
It would be nice for more complex applications to be able to create multiple agents within the same project, and make this possible through the API would allow us to automate the process.

Knowing if this is possible for the Dialogflow devs and how much time it would take would help me predict the scalability of my use case, so I can focus on what makes more sense now.
Thank you very much.

**Comment by JustinBeckwith** [comment]
@nnegrey is this possible?

**Comment by nnegrey** [comment]
Hi, currently you are correct, this is not a supported feature.

Is this instance a case where you would find yourself creating agents often and quickly?

**Comment by rwmb** [comment]
No need for it to be very quick - through an API would be much quicker than doing the whole process manually, obviously - but in a situation where you want to provide custom agents for different groups of customers, you'd have to create different agents AND projects so intents don't get confused. I do have this feature where I do something like that (I'm under NDA so we can talk about this through DM for more details), but I don't want to use a jenky solution like a bot to do something like this, so my application won't scale if I have to manually create one agent and one project per group.
Does this makes sense @nnegrey ?
Thanks for the quick response.

**Comment by CharlesT100** [comment]
Hi @nnegrey - I'd like to note I see this is an essential feature request.
I was surprised the agent couldn't be created via the API, especially for the Enterprise edition.

Additionally, the ability to add multiple agents into the same project would be extremely beneficial (although the workaround of exporting an agent/importing into another agent 'works' - it is not the expected workflow, creates overhead and many GCP projects that will never be used).

> I don't believe agents would be created __that__ often and quickly - product market fit isn't easy :)

**Comment by nnegrey** [comment]
Also requested here for visibility: https://github.com/googleapis/nodejs-dialogflow/issues/257

**Comment by rwmb** [comment]
Hi, @nnegrey, any updates on this issue? Is the team considering this feature?

**Comment by nnegrey** [comment]
Hi all, you can jump on this page to report bugs and feature requests directly to the product teams. 
https://cloud.google.com/support/docs/issue-trackers

There are two bugs currently open related to above FRs. Please jump on those and make additional comments for these requests. 
Multi Agent FR: https://b.corp.google.com/issues/119335121
Create via API FR: https://b.corp.google.com/issues/122786944

**Comment by callmehiphop** [comment]
Going to close this issue out, since the discussion seems to have moved elsewhere.

**Comment by rwmb** [comment]
@callmehiphop the other one was moved to this issue and was closed, this is the main one it seems

**Comment by callmehiphop** [comment]
@rwmb interesting, since this client is generated, there isn't anything actionable by the node devs themselves, it would be up to the API team to implement this feature.

@nnegrey @beccasaurus @sduskis  where is the right place for a request like this? I'm not really sure where it should go, but I don't think it's here.

**Comment by nnegrey** [comment]
Please see the above comment for feature requests that are tied to the product itself. 

```
Hi all, you can jump on this page to report bugs and feature requests directly to the product teams.
https://cloud.google.com/support/docs/issue-trackers

There are two bugs currently open related to above FRs. Please jump on those and make additional comments for these requests.
Multi Agent FR: https://b.corp.google.com/issues/119335121
Create via API FR: https://b.corp.google.com/issues/122786944
```

**Comment by rwmb** [comment]
@callmehiphop sorry, I thought issues were being managed here, but I agree, it's a feature of the platform and not the package

**Comment by nnegrey** [comment]
Just FYI, Agent Creation has been added: https://cloud.google.com/dialogflow/docs/release-notes#june_13_2019

**Comment by dimitriosp** [comment]
> Just FYI, Agent Creation has been added: https://cloud.google.com/dialogflow/docs/release-notes#june_13_2019

@nnegrey Great news on the creation part! But currently I can just update the parent one, do you also know how to use the API to create a new agent? There is no documentation on the creation part?

```
POST https://dialogflow.googleapis.com/v2/projects/PROJECT-NAME/agent/
then as body
{
  "parent": "test",
  "displayName": "test",
    "defaultLanguageCode": "en",
    "timeZone": "Europe/Madrid",
    "enableLogging": true,
    "matchMode": "MATCH_MODE_HYBRID",
    "classificationThreshold": 0.3,
    "apiVersion": "API_VERSION_V2",
    "tier": "TIER_STANDARD"
}
```
any idea?
Thanks

**Comment by rwmb** [comment]
That's amazing! I am very happy this feature has been added. I will certainly use it and let people know this exists! I will start messing around with it soon and give my feedback when possible! Thanks a lot guys.

**Comment by i-MaxProfit** [comment]
It seems that this feature still does not work. Unable to create new agent. We can only edit the existing one. Maybe someone knows life hack how to create agent via api?

**Comment by nnegrey** [comment]
Are you using the `SetAgent` request?
https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#setagentrequest

**Comment by aotol** [comment]
This post is misleading. It makes people feel that you can create multiple agents under one project as the original question raised by @rwmb is

> be able to create multiple agents within the same project
However, it has been confirm by Google itself that

> [Note: You can only create one agent for a GCP project. If you need multiple agents, you will need to create multiple projects.](https://cloud.google.com/dialogflow/docs/agents-manage)

The setAgent method that @nnegrey mentioned is to create or update the one, and the only one agent in project. If the project does not have an agent, this setAgent method will create one. Otherwise it simple does the update job. Therefore, **this setAgent API is not able to create multiple agents under one project.**
