### ISSUE TITLE
Sudden issues while using Intents.BatchUpdateIntents, Intents.BatchDeleteIntents

### ISSUE THREAD

**Issue by ikotarac** [googleapis/nodejs-dialogflow#181]
We started having issues using Dialogflow APIs since Tuesday, 10/02/2018. We use Node.js client library for Dialogflow to update Intents and EntityTypes on several accounts (used for staging and production environments, and everything worked perfectly up until now).

Are there any problems with Dialogflow APIs that we should be aware of? Any info, workarounds, ETAs and such would be much appreciated.

#### Environment details

  - OS: macOS 10.13.6 
  - Node.js version: v8.12.0
  - npm version: 6.4.1
  - `dialogflow` version: 0.5.0, 0.7.0

#### Steps to reproduce

Here are more details on which APIs we use, and the errors we received.

We call following APIs:

Intents.ListIntents
Intents.BatchUpdateIntents
Intents.BatchDeleteIntents
EntityTypes.ListEntityTypes
EntityTypes.BatchUpdateEntityTypes
EntityTypes.BatchDeleteEntityTypes

Following error started occurring while calling Intents.BatchUpdateIntents:

`Error: 9 FAILED_PRECONDITION: Intent with the display_name 'fallback-positive-redirect1' already exists.`

When we delete all intents manually in the console, our Node.js script manages to update intents correctly. We tried deleting all intents programmatically using Intents.ListIntents and then Intents.BatchDeleteIntents, but received error:

`Error: 5 NOT_FOUND: Cannot find intent '223355e0-ab2c-4bae-a095-ba24e5dbf30f' in project 'botdemo-b6a84'.`

**Comment by MumblesNZ** [comment]
I'm experiencing a similar error, but with `Error: 9 FAILED_PRECONDITION: Intent with the display_name 'demo-demo - no - changeplant' already exists.` when calling `intentsClient.createIntents()` after I have deleted it using the UI from the agent. I also have checked the downloaded zip version of the agent which also confirms no intent with that name exists anymore after deletion.

**Comment by callmehiphop** [comment]
@MumblesNZ @ikotarac I'm a little late to the party, but are either of you still experiencing this issue? If so, would you be able to provide us with some code examples to go off of?

**Comment by callmehiphop** [comment]
Hasn't been any activity here, so I'm going to close this out. If anyone continues to experience this, let us know and we'll be happy to re-open! 😎

**Comment by PepersAndOnions** [comment]
I am still experiencing this. I have gotten this error with calling intentsClient.batchUpdateIntentsAsync() and intentsClient.createIntents(). Prior to calling these, I have deleted all intents from the DialogFlow UI.

**Comment by callmehiphop** [comment]
Seems like we're hitting some kind of race condition here, probably not an issue with the client itself. You may want to open a product issue over at https://cloud.google.com/support/docs/issue-trackers.

@nnegrey any thoughts here? Does Dialogflow have some kind of eventual consistency model?

**Comment by nnegrey** [comment]
It's probably a race condition because it's a batch job not a synchronous job. 

I'm not aware of a guarantee that would solve this. You'd have to first verify that the batch job was finished before trying to do something else.

**Comment by callmehiphop** [comment]
@PepersAndOnions can I ask how you're calling `batchUpdateIntents`? Calling it should create a long running operation that you can use to observe the job state

```js
const [operation] = await client.batchUpdateIntents(...);
await operation.promise();
```

**Comment by PepersAndOnions** [comment]
I received the exception after making only one call to this API with 6 intents. No subsequent calls were made.

OperationFuture<BatchUpdateIntentsResponse, Struct> operation = 
          intentsClient.batchUpdateIntentsAsync(batchUpdateRequestBuilder.build());

**Comment by callmehiphop** [comment]
@PepersAndOnions ah, I see. I'm not really familiar with the Java client, so unfortunately I won't be of much help, but you might try opening an issue in the Java repo?

**Comment by agrawals1** [comment]
hello...I was working on batch update/create/delete of intents/entities. I got the http post request from https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent.intents/batchUpdate, but I have no idea How to attach the json body to the request and send it to the appropriate agent.

can somebody plz help me!!!

**Comment by callmehiphop** [comment]
@agrawals1 could you open a new issue for your question? Just looking to avoid derailing this one 😃

**Comment by agrawals1** [comment]
@callmehiphop sure...

**Comment by PepersAndOnions** [comment]
@callmehiphop Thanks for your help. I have opened an issue directly with DialogFlow
