### ISSUE TITLE
Usage of Session entities in user entity resolution

### ISSUE THREAD

**Issue by developer170883** [googleapis/nodejs-dialogflow#201]
As System entity for **GivenName** and **LastName** is locale specific , so I am populating session entity to supplement my user entity **PlayerFullName**.  **PlayerFullName** is a composite entity consisting of a combination of **System.GivenName** and **System.LastName**. Even though I see that session entity gets populated with the name that i provide at run time but dialog flow is not able to resolve the PlayerFullName entity with the data supplied.  Am i missing something or  my understaing of dialogflow session entity is not correct. Please help
Thanks in advance.

**Comment by nnegrey** [comment]
Hey, trying to understand your setup. 

You're creating a [`SessionEntity` ](https://dialogflow.com/docs/entities/session-entities), is that correct or are you creating a `EntityType` and putting `Entities` inside it?

**Comment by roshancsc** [comment]
Yes I am creating sessionentity through API 
var response = await sessionEntityTypesClient.createSessionEntityType(sessionEntityTypeRequest)
and I can see in the newly created entity in response.

**Comment by roshancsc** [comment]
@nnegrey as my dialogflow agent is in en-Au locale and I need to populate FirstName or LastName in my composite entity . It works for English name but the user base consists of non-English name. So i am trying to leverage session entity where during launch of the agent I supplement all the name that exist in the database.

**Comment by nnegrey** [comment]
Gotcha, one thing about SessionEntities is that they only exist for that Session, are you creating a new one for each created Session?
If you use it often, it may be worth creating a permanent one.

**Comment by roshancsc** [comment]
I have a dialogflow agent with webhook fulfilment  as AWS lambda serverless. The flow is when user launches the agent through google assistant, webhook is called to fulfil the welcome intent, during that fulfilment we load  all the employee reporting to that user in the SessionEntities  using dialogflow api. The fulfilment response is served by agent  and now user asks **"what is the status of PersonName"**. So any non-English name is not getting picked up. 
Is this not the same session that user has created through google assistant. If not then what purpose SessionEntities  serves in context of webhook fulfilment. I cannot populate the entity with entire list of person name in the database, as there are close to million record in the database. Please correct my understanding.

**Comment by roshancsc** [comment]
yes  I do, Is session Id parameter in createSessionEntityType is any arbitrary string or do we need to supply session id with the session property that we recieve in webhook fulfilment request. which looks like
**"projects/agent-id/agent/sessions/ABwppHFLGocXk5tqY715LG61kv11SQTEAT4SYkG3Ci4AHD1YubHZtWRrPVGAy8mAne7aYRDgDpdOapstGs3ty5KC"**
Because right now  i am supplying a new Guid every time.

The entity in my dialog flow looks like
![image](https://user-images.githubusercontent.com/3881299/47885709-78e61d80-de8a-11e8-970f-fa50d11eca0f.png)

**Comment by nnegrey** [comment]
What kind of training phrases do you have to help populate the entity?
