### ISSUE TITLE
Stuck in a loop after calling listIntents with incorrect credentials

### ISSUE THREAD

**Issue by BeefMediumRare** [googleapis/nodejs-dialogflow#218]
#### Environment details
  - OS: macOS Mojave 10.14
  - Node.js version: 10.3.0
  - npm version: 6.4.1
  - `dialogflow` version: 0.70

#### Steps to reproduce
I call some dialogflow function like this

``` javascript
  const intentsClient = new IntentsClient({credentials});
  const {intentsClient, projectAgentPath} = {
    intentsClient,
    projectAgentPath: intentsClient.projectAgentPath(projectId),
  };

  const response = await intentsClient.listIntents({parent: projectAgentPath});
```

the projectId is a `string` and the credentials an object `{
    client_email: string,
    private_key: string
}`

If I make the for example the private_key invalid by exchanging some char I find my self stuck in a loop that prints `Auth error:Error: [...]`. A `getIntent` call result in the same behaviour.

But if I call a method on a `SessionClient` e.g. `detectIntent` with an invalid private_key it will produce an actual error that I can catch and react upon.

**Comment by jbdoster** [comment]
I am experiencing an auth issue as well..

**Comment by kencanak** [comment]
any update on this fix? i am encountering the same issue

**Comment by callmehiphop** [comment]
Without digging in too deep, my best guess is because list requests can sometimes make multiple requests (essentially they keep making requests until you run out of results).

A temporary work around might be to disable the auto pagination

```js
const response = await intentsClient.listIntents({parent}, {autoPaginate: false});
```

@alexander-fenster sounds like a `google-gax` bug, WDYT?

**Comment by alexander-fenster** [comment]
@kencanak Since the original issue was filed, we made changes to how the auth promise rejection is handled in the client code. Can you share your code for us to take a look and repro?

Thanks!

**Comment by kencanak** [comment]
@alexander-fenster here's my code
`
const intentsClient = new dialogflow.IntentsClient({
  credentials: {
    client_email: 'random@random.iam.gserviceaccount.com',
    private_key: 'test',
  },
  projectId: 'project-id'
});


const projectAgentPath = intentsClient.projectAgentPath('project-id');

intentsClient.listIntents({
	parent: projectAgentPath,
})
.then((res) => {
	console.log(res);
	return;
})
.catch((err) => {
	console.error('oops');
	console.error(err);
});
`

**Comment by callmehiphop** [comment]
@alexander-fenster have you had a chance to poke at this?

**Comment by alexander-fenster** [comment]
Looking now. I see where the rejection is coming from, trying to understand what is the right way to deal with it.

**Comment by callmehiphop** [comment]
@alexander-fenster will this end up getting fixed when we move to the typescript gapic generator?

**Comment by czahedi** [comment]
@alexander-fenster any updates here?

**Comment by alexander-fenster** [comment]
I'll take one more look here, even though I'm not convinced it's important since it is being triggered by a very unique use case.

**Comment by czahedi** [comment]
Thanks. If it turns out it's a unique use-case (with a ticket over 1 yr old) then we can probably close it unless a similar issue arises down the road. Keep us posted

**Comment by nnegrey** [comment]
I'd suggest closing.

**Comment by alexander-fenster** [comment]
Agreed, closing for now, will reopen and investigate if more issues related to unhandled promise for bad auth key appear.

Rationale: this does not happen during the normal usage, only during initial setup where the user will definitely see that auth is not going right.
