### ISSUE TITLE
Managing multiple client sessions

### ISSUE THREAD

**Issue by hboylan** [googleapis/nodejs-dialogflow#22]
This issue relates to performance concerns.

It takes a relatively long time to initialize a new client (SessionsClient, AgentsClient, ContextsClient, etc.). I've tried to globalize this step, but the client's authentication needs to be refreshed each hour. They also appear to share the same auth strategy anyway, so it feels odd having to create one of each like this.

Is there a strategy for managing these clients so that the underlying APIs can be accessed more efficiently? (ie. via serverless functions)

#### Environment details

  - OS: **Ubuntu 16.04**
  - Node.js version: **8.9.4**
  - npm version: **5.6.0**
  - dialogflow version: **0.1.0**

#### Steps to reproduce

```javascript
const projectId = process.env.PROJECT_ID

// this is quite slow
const client = new dialogflow.SessionsClient({
  credentials: {
    client_email: "svc-acc@project-id.iam.gserviceaccount.com",
    private_key: "---BEGIN.....END-----"
  },
  projectId
})

function detectIntent(sessionId, input) {

  const request = {
    session: sessionClient.sessionPath(projectId, sessionId),
    queryInput: {
      text: {
        text: input,
        languageCode: "en-US"
      }
    }
  }
  
  // this is quite fast
  return client.detectIntent(request)
    .then(res => {
      console.log(res)
      return res
    })
    .catch(err => {
      console.error(err)
      throw new Error('Error occurred during intent detection')
    })
}
```

**Comment by MumblesNZ** [comment]
Hey @hboylan did you make any progress with this?

**Comment by hboylan** [comment]
Unfortunately no. I wound up using an express microservice because of the performance lost during the OAuth calls. Keeping each client in memory lowered the overall request latency by several hundred microseconds

**Comment by nnegrey** [comment]
Hi, I'm not sure if there is a better option due to the nature of OAuth and the idea that a Session is unique to each user to keep it secure. One thing could be to buffer these Sessions so that when a user is ready to make a request the detect intent call can be made right away.

**Comment by freewil** [comment]
I ran into a similar issue here. It appears the client instances are not designed to be long-living, although that is an issue for web servers or other processes serving a large number of requests, if instantiating them comes with a significant performance hit.

> I'm not sure if there is a better option due to the nature of OAuth and the idea that a Session is unique to each user to keep it secure.

I don't believe this is relevant to the issue as it doesn't appear the client instances store any session/user-specific state. Something that can be misleading in this example is that `sessionClient.sessionPath` does not mutate any state on the `sessionClient`, it simply returns a string to be used on the request object. Each request has its own `sessionPath`.

I ended up creating a little wrapper around `dialogflow` that instantiates clients every 50 minutes. It seems like it'd be ideal if the library did this itself based either on time or on a relevant auth error.

```js
const dialogflow = require("dialogflow");
const clientOpts = require("../config");

// Client authentication expires after 60 minutes, so with a safe buffer,
// expire clients after 50 minutes.
//
// See: https://github.com/googleapis/nodejs-dialogflow/issues/22
const EXPIRE_CLIENT_MS = 50 * 60 * 1000;

class ClientFactory {
  constructor(Klass) {
    this.Klass = Klass;

    this.created = null;
    this.instance = null;
  }

  getInstance() {
    if (!this.instance || Date.now() - this.created > EXPIRE_CLIENT_MS) {
      this.instance = new this.Klass(clientOpts);
      this.created = Date.now();
    }

    return this.instance;
  }
}

const intentsFactory = new ClientFactory(dialogflow.IntentsClient);
const sessionsFactory = new ClientFactory(dialogflow.SessionsClient);

exports.getIntentsClient = () => {
  return intentsFactory.getInstance();
};

exports.getSessionsClient = () => {
  return sessionsFactory.getInstance();
};

```
