### ISSUE TITLE
Different Convention in Docs & Repo

### ISSUE THREAD

**Issue by theomarshanti** [googleapis/nodejs-dialogflow#227]
The [DialogFlowDocumentation](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2) referenced in this repo uses a different convention when naming variables than this codebase does.
As a developer, I became frustrated at the docs when I couldn't debug my errors and had to go to the source code itself to find my solution. Wouldn't it be better for the docs & the codebase to show the same information?
The difference in convention is that the documentation uses snake_case while the codebase uses camelCase.

Examples:
[entity_type](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Intent.TrainingPhrase.Part) is actually `entityType` in the code.

[user_defined](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#part) is `userDefined` in the code; and `display_name` is `displayName`

There are many others

**Comment by nnegrey** [comment]
Hi the RPC docs are general docs for the API in general across languages rather than specifically for Node.js
