### ISSUE TITLE
Knowledge Base + Node JS returns knowledgeAnswers as "null"

### ISSUE THREAD

**Issue by LRitesh** [googleapis/nodejs-dialogflow#229]
Hi,

I'm trying Knowledge Bases with v2 Node JS API and running into an issue. In my intent `request` if I specify 
```
             queryParams: {
                    knowledgeBaseNames: [knowledgeBasePath]
                }
```
then I always get `knowledgeAnswers` returned as `null`. I also get `allRequiredParamsPresent` as `false` in the returned `queryResult`. But if I remove this from the request, and just enable the same Knowledge Base via UI, it works fine! 

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.14.1
  - npm version: 6.4.1
  - `dialogflow` version: 0.7.0

Thanks!

**Comment by nnegrey** [comment]
Hi, are you following the samples here for KnowledgeBases?
https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.v2beta1.js#L23

**Comment by nnegrey** [comment]
Also this sample for detecting an intent from a KnowledgeBase: https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.v2beta1.js#L371-L414

**Comment by JustinBeckwith** [comment]
Greetings!  There hasn't been much action on this issue for a while, so I'm going to go ahead and close it.  If you're still running into issues... please do let us know!

**Comment by dennyjohnk** [comment]
what should be the knowledgebase full name ?
