### ISSUE TITLE
Empty response on detectIntent with audio

### ISSUE THREAD

**Issue by mateuszNohup** [googleapis/nodejs-dialogflow#238]
Environment:
Node v8.14.0
npm 6.4.1
dialogflow-web 0.7.0

With the following code, I get an empty response like such:
```
[ { responseId: '',
    queryResult:
     { fulfillmentMessages: [],
       outputContexts: [],
       queryText: '',
       speechRecognitionConfidence: 0,
       action: '',
       parameters: null,
       allRequiredParamsPresent: false,
       fulfillmentText: '',
       webhookSource: '',
       webhookPayload: null,
       intent: null,
       intentDetectionConfidence: 0,
       diagnosticInfo: null,
       languageCode: 'en' },
    webhookStatus: null },
  undefined,
  undefined ]
```
on any audio file I use, I pass it the filename of an opus audio file. I have no problems with text input with a slightly different function and I can't find the problem. Dialogflow itself works fine,  I based the code on the examples given in the dialogflow docs.

Here's the code, what am I doing wrong?

```javascript
audioQuery: async (audio, languageCode) => {
	const readFile = util.promisify(fs.readFile);
	return readFile(audio)
		.then(inputAudio => {
			const request = {
				session: sessionPath,
				queryInput: {
					audioConfig: {
						audioEncoding: encoding, //'AUDIO_ENCODING_OGG_OPUS'
						sampleRateHertz: sampleRateHertz, //16000, also tried 48000 which is the value given in media players for the file
						languageCode: languageCode, //'en'
					},
				},
				inputAudio: inputAudio.toString("base64"), // tried also without converting
			};
			return sessionClient.detectIntent(request)
				.then(responses => {
					const result = responses[0].queryResult;
					if (result.intent) {
						return result.fulfillmentText;
					} else {
                                                // always goes here
						return 'No intent matched';
					}	
				})
				.catch(err => {
					console.error('ERROR:', err);
				});
		});
}
```

**Comment by nnegrey** [comment]
Hi, did you try following this sample? Are your text and audio request content the same? (E.g. both say "Hello")
https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js#L128-L167

I believe you should not convert the audio bytes.

**Comment by mateuszNohup** [comment]
Here's how i solved it
```
let audioQuery = async (audio, lang, options, sessionId) => {
	const sessionPath = sessionClient.sessionPath(config.projectId, sessionId);
	const request = {
		session: sessionPath,
		queryInput: {
			audioConfig: {
				audioEncoding: options.audioEncoding, // always AUDIO_ENCODING_LINEAR_16
				sampleRateHertz: options.sampleRateHertz, // got it from the file
				languageCode: lang,
			},
		},
		queryParams: {
			contexts: options.contexts,
		},
		inputAudio: audio, // wav as b64 string
		outputAudioConfig: {
			audioEncoding: 'OUTPUT_AUDIO_ENCODING_MP3',
		},
	}

	return sessionClient.detectIntent(request)
		.then(async responses => {
			let options = {
				audioResponse: true,
				languageCode: lang,
			}

			return buildResponse(responses, options);
		})
		.catch(err => {
			console.error('ERROR:', err);
		});
}
```

Basically I had to use wav files, converted to base64 strings and not read as a file, any other format was not working.
@nnegrey I was referring to a slightly different function, detectIntent on just text had no problem, with this solution everything works, I get the transcript in the response as expected.

**Comment by severcolhon** [comment]
Hi @mateuszNohup I'm facing a similar issue. Problem is that I do all your steps and still receive an empty object. 
Can you tell me what do you use to record the sound in the client's browser?
thx

**Comment by mateuszNohup** [comment]
We're using the [RecordRTC](https://recordrtc.org/) library @severcolhon, our issue was with the format of the audio used with the Dialogflow API and not with the recording itself. The API docs don't exactly help much there, you should try various configs for the encoding of the request and the response.

**Comment by nnegrey** [comment]
Here's some info the about the Audio Encodings supported by Dialogflow: https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.AudioEncoding

**Comment by severcolhon** [comment]
Thanks for the response @mateuszNohup. 
Could you please post the config used by RecordRTC and the audioConfig used to send the request to Dialogflow?
I think I tried all possibilities without success.

**Comment by mateuszNohup** [comment]
RecordRTC options config
```
{
	type: 'audio',
	numberOfAudioChannels: 1,
	checkForInactiveTracks: true,
	mimeType: "audio/ogg",
	recorderType: RecordRTC.StereoAudioRecorder,
	desiredSampRate: 16000,
	disableLogs: true,
	timeSlice: 50,
}
```

Request config
```
{
	session: sessionPath,
	queryInput: {
		audioConfig: {
			audioEncoding: 'AUDIO_ENCODING_LINEAR_16',
			sampleRateHertz: 16000,
			languageCode: lang,
		},
	},
	queryParams: {
		contexts: options.contexts,
		payload: require('./structjson').jsonToStructProto({
			queryType: "audio"
		}),
	},
	inputAudio: audio,
	outputAudioConfig: {
		audioEncoding: 'OUTPUT_AUDIO_ENCODING_MP3',
	},
}
```

Hope you find it helpful @severcolhon

**Comment by severcolhon** [comment]
Thanks @mateuszNohup! You are my hero!
RecordRTC only fails the second time I do a recording, but I'll try a workaround.
Nevertheless, the request to Dialogflow works perfectly now.

**Comment by Venryx** [comment]
@mateuszNohup According to the RecordRTC comments here: https://github.com/muaz-khan/RecordRTC#configuration

...specifying a mimeType of "audio/ogg" is only possible in the Firefox browser (not Chrome).

Is this accurate? Or did you somehow manage to get the audio recorded into an "ogg" container (from the microphone, while in-browser), even in Chrome?
