### ISSUE TITLE
Not able to update intent

### ISSUE THREAD

**Issue by AsoOor** [googleapis/nodejs-dialogflow#246]
Hello,

I am trying to update specific intent, but I cannot.
Here is the code:

```js

async function updateIntent() {
  const dialogflow = require('dialogflow');
  const projectId = 'project-id';
  const intentId = 'intent-id';
  const trainingPhrasesParts = ['test1', 'test2'];
  const intentsClient = new dialogflow.IntentsClient();
  const intentPath = intentsClient.intentPath(projectId, intentId);
  const trainingPhrases = [];
  trainingPhrasesParts.forEach(trainingPhrasesPart => {
    const part = {
      text: trainingPhrasesPart,
    };
    const trainingPhrase = {
      type: 'EXAMPLE',
      parts: [part],
    };
    trainingPhrases.push(trainingPhrase);
  });

  const intent = {
    trainingPhrases: trainingPhrases
  };
  
  const updateIntentRequest = {
    name: intentPath,
    intent: intent
  };

  try {
    const responses = await intentsClient.updateIntent(updateIntentRequest);
    response.send(responses);
  }
  catch (error) {
    response.send(error);
  }
}
```

**Comment by AsoOor** [comment]
> Greetings! Are you getting some kind of error?


Yes, this is the error :
`{"code":3,"metadata":{"_internal_repr":{"grpc-server-stats-bin":[{"type":"Buffer","data":[0,0,187,67,25,1,0,0,0,0]}]}},"details":"Resource name '' does not match 'projects/*/agent/intents/*'."}`

**Comment by GonzMG** [comment]
I have the same problem, but my code is kind of different. It seems like a bug or something. I found some threads talking about the same error and they solve it creating and deleting the intent...

**Comment by nnegrey** [comment]
Hi it looks like you may be structuring your request incorrectly. 
- [updateintentrequest](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#updateintentrequest)
- [intent](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Intent)

```
const intent = {
    name: name, // Required
    displayName: displayName, // Required
    trainingPhrases: trainingPhrases,
  };
  
const updateIntentRequest = {
    intent: intent,
  };
```

**Comment by GonzMG** [comment]
It works for me! Thank you!!
