### ISSUE TITLE
Bad GRCP binary throw "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential." instead of meaningful error

### ISSUE THREAD

**Issue by Vadorequest** [googleapis/nodejs-dialogflow#250]
#### Environment details

  - OS: MacOS 10.14
  - Node.js version: 6.10.3
  - npm version: 3.10.10
  - `dialogflow` version: 0.6.0

#### Steps to reproduce

  1. Add a `"postinstall": "npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc"` script in your package.json when using a MacOS device
  2. Build (npm, yarn)
  3. Test a Dialogflow authentication using either ENV variable or provided (following test use ENV variable)
```js
import dialogflow from 'dialogflow';

test('should authenticate when provided process.env.GOOGLE_APPLICATION_CREDENTIALS', async () => {
      process.env.GOOGLE_APPLICATION_CREDENTIALS = './yourcredentials.json';
      const projectId = 'yourprojectid';

      const sessionClient = new dialogflow.SessionsClient();
      const sessionPath = sessionClient.sessionPath(projectId, 'test');

      // The text query request.
      const request = {
        session: sessionPath,
        queryInput: {
          text: {
            text: 'hello',
            languageCode:'fr-FR',
          },
        },
      };

      const result = await sessionClient.detectIntent(request);
      console.log(result);
      expect(result).toBeDefined();
    });
``` 
  4. Run the test
  5. Error should produce message similar to `Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.`

Iran into this very weird issue yesterday, when compiling the binary target linux on my mac and using it by accident. My goal was to deploy a linux binary to AWS Lambda, I'm not used to deal with binary, especially not targeting specific platforms and such, and therefore ended up using a linux binary on a MacOS computer.

Removing the script in the package.json was enough to fix my issue, but I only figured it hours later, mostly due to the error message which made me believe something was wrong with my credentials, and looked a completely different way I should have. Lots of time wasted.

I believe the message should be much clearer when not using the proper binary.

**Comment by jbdoster** [comment]
I actually just started receiving this error too... My client secret has been working fine this whole time until now?

**Comment by JustinBeckwith** [comment]
Greetings folks!  Are y'all still seeing this?

**Comment by Vadorequest** [comment]
@JustinBeckwith As stated in my first post, the mistake was mine (running linux binary on macos), compiling the right stuff fixed it. The issue was mostly the error message wasn't transparent, resulting in a lot of time wasted figuring out what was wrong.
