### ISSUE TITLE
multiple DF agents in a single project

### ISSUE THREAD

**Issue by lastday154** [googleapis/nodejs-dialogflow#257]
Hi. Any idea about how to manage multiple DF agents in a single project? Uploading multiple JSON keys for each bot for the connection?

My project should handle multiple agents, and users can connect agents dynamically.

**Comment by nnegrey** [comment]
Hi, DialogFlow does not currently support multiple agents in a GCP project.

**Comment by nnegrey** [comment]
Going to close this one as this has been requested in https://github.com/googleapis/nodejs-dialogflow/issues/175
