### ISSUE TITLE
Deprecating dialogflow and move to @google-cloud/dialogflow

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-dialogflow#265]
While working on getting API docs for this package published, I realize that this package is published to npm under the name `dialogflow`, while our convention for Cloud packages is to publish under the `@google-cloud` scope.

For consistency, I propose we publish newer versions of this package as `@google-cloud/dialogflow` while deprecating `dialogflow` with a message:

`npm deprecate dialogflow "dialogflow has been moved to @google-cloud/dialogflow. To ensure you get package upgrades, please migrate to the new package."`

Thoughts appreciated @JustinBeckwith @nnegrey

**Comment by JustinBeckwith** [comment]
We sorta have a lot of modules that we don't publish under the `@google-cloud` scope for historical reasons.  I'm not like entirely opposed to this, but I do worry that it's additional churn with no real user benefit 🤷‍♂️ 

I would feel differently if we could redirect npm installs like github repositories.

**Comment by kinwa91** [comment]
It was just mostly to make our (me, mostly) life easier, no real benefit to users. I'll keep it as `dialogflow` for now then. Thanks!
