### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by OAyomide** [googleapis/nodejs-dialogflow#278]
Hi,

I ran into this issue: `Segmentation fault (core dumped)` and node process exits after that. Switching to other node versions seem to remove the issue, so I am pretty sure the issue is with node v11.7.0, Tried with 8.14.0 and 11.9.0 and both worked without giving the issue
#### Environment details

  - OS: Ubuntu 18.04 (Bionic Beaver)
  - Node.js version: 11.7.0
  - npm version: 6.5.0
  - `dialogflow` version: 0.8.0

#### Steps to reproduce

  1. Follow the code in the readme.
  2. Run the code: `node <filename> .js`

**Comment by JustinBeckwith** [comment]
Greetings!  Node 11 is still non-LTS.  While we work to support all versions, I'd the latest one works - that's probably all we can do.  Thanks for the report though!  I'd suggest sticking with the latest 11, or going back to the supported 10.x release pine if you're still having issues.
