### ISSUE TITLE
API returns array (but only on async/await)

### ISSUE THREAD

**Issue by RachelleJanssen** [googleapis/nodejs-dialogflow#289]
I was trying to fix some issues in some middleware and noticed that there was a difference between api calls using async/await and callbacks.

async/await returns an array (with  [something, null, null])
callbacks simply the result as an object

Why is that exactly? and is there a way to get a regular object back from the async/await (without using response[0] because that feels a bit hacky to me)

**Comment by callmehiphop** [comment]
@RachelleJanssen I'm not sure what is up with the extra null values, which method are you calling that returns this? As for the reason why we return an array, that is just how promises resolve across all the Node.js client libraries, we do this because most methods can return multiple items where as Promises can only be resolved with a single value. I recommend destructuring the results.

```js
const [something] = await client.method();
```

**Comment by RachelleJanssen** [comment]
Sorry my mistake, wasn't null but undefined. 
Still though, I got the array on the following code:
`const detectIntentResult = await dialogflowMiddleware.api.sessionsClient.detectIntent(detectIntentRequest);`

while this gives back an object:
`dialogflowMiddleware.api.sessionsClient.detectIntent(detectIntentRequest, (err, res) => { console.log(res); });`

don't mind the middleware stuff, that's just a class instance containing all clients

I heard Dialogflow V2-beta is going to contain multiple results in detectIntent, could that maybe be the 'issue' here?

**Comment by RachelleJanssen** [comment]
just tested with getIntent as well, got 2x undefined on that array as well

**Comment by callmehiphop** [comment]
I'm not sure where the undefined values are coming from, it could be a bug in `google-gax`. As far as the Array goes.. we've always returned them for Promises (even in the case of a single result) solely for the sake of being consistent across all our client libraries. So even if the undefined values weren't there, you would still need to destructure.

**Comment by callmehiphop** [comment]
Been kind of quiet here, so I'm going to close this out for now. Please let us know if there's anything else we can do to help!
