### ISSUE TITLE
'lastUpdate' property in all resources would be mighty nice

### ISSUE THREAD

**Issue by peternann** [googleapis/nodejs-dialogflow#29]
This would make 'update' operations potentially much safer for the case where someone else _might_ have updated Intents/Entities underneath you (i.e. A team development situation).
i.e.:
Update once - Capture the timestamp
Updating later - first check the timestamp - If it's changed from last time, then DANGER - someone else might have changed in the interim.

I only feel justified mentioning this because the Intents in the V1 zip format DO have a lastUpdate field. I think this is a grand idea and should be in every resource for both consistency and benefit.

**Comment by callmehiphop** [comment]
Unfortunately this code is purely generated, so this probably isn't the best place to make an API feature request. You can try opening a feature request at https://cloud.google.com/support/docs/issue-trackers, please feel free to link here if you do 🙃
