### ISSUE TITLE
Knowledge base doesn't get Enabled after Creation

### ISSUE THREAD

**Issue by dennyjohnk** [googleapis/nodejs-dialogflow#293]
Hi,
After creating a knowledge base using the **createKnowledgeBase** method, the knowledge base gets created, but it doesn't get enabled automatically.
I have to manually enable it through the web ui.
Is this a bug or is there any other method to enable a knowledge base ?

**Comment by nnegrey** [comment]
Is this happening every time or just the first initial KnowledgeBase for enabling the beta feature?

**Comment by dennyjohnk** [comment]
Yes. This is happening every time whenever I try to create knowledge base

**Comment by nnegrey** [comment]
Looks like by default they are disabled when created: https://cloud.google.com/dialogflow-enterprise/docs/knowledge-connectors#settings

**Comment by nnegrey** [comment]
You can override this by specifying the specific knowledge base in a request. 
However, it doesn't look like there is a way to enable this through the API. 
Feel free to file a feature request on: https://cloud.google.com/support/docs/issue-trackers

Gonna close this, but feel free to re-open. :)

**Comment by abhi007tyagi** [comment]
@dennyjohnk how did you create knowledge base programatically? I am not able to connect to my agent for creating KB. Here is my SO question https://stackoverflow.com/questions/60532102/dialogflow-nodejs-knowledge-iam-permission
