### ISSUE TITLE
Parameters is not detected after creating an intent using api 

### ISSUE THREAD

**Issue by jaymovaliya** [googleapis/nodejs-dialogflow#303]
Hi,
I am creating intents using api v2 with training phrases. i am able to detecting entities and everything works fine.
After training of an agent gets complete i tried with one of training phrase and i am able to detect intent and action but not parameters.

like this.
![dfissue1](https://user-images.githubusercontent.com/22033842/54581386-7d266800-4a32-11e9-9d64-158786ae2811.png)

and this
![dfissue2](https://user-images.githubusercontent.com/22033842/54581408-a8a95280-4a32-11e9-8401-68080692e1a3.png)

When i save an intent manually in UI (Save button) my issue gets resolves

have a look at this
![dfissue3](https://user-images.githubusercontent.com/22033842/54581499-06d63580-4a33-11e9-826f-b18f399b3514.png)

I want to do it automatically by **using api only.**

Help me

**Note:**
1). After creating an intent i am calling the **agent train api**
2) I am also **giving 5 minutes** to give it time to figure things out.  
 
Have a look at code also
`const createIntentRequest = {`
            `parent: agentPath,`
           ` intent: intent`
 ` }`
  `intentsClient.createIntent(createIntentRequest, async function(err, result){`
           `if (err) {`
              ` console.log(err)`
          ` }else {`
      `console.log(result)`
      `console.log(`${intent.displayName} has created..`)`
      `console.log("training started...")`
      `var trainAgentRequest = {`
        `parent: agent.projectPath('MY_PROJECT_ID')`
      `}`
      `try{`
      `var traineddata = await agent.trainAgent(trainAgentRequest)`
      `console.log(traineddata)`
      `}catch(e){`
       ` console.log(e, "this is error")`
      `}`
     ` console.log("training completed")`
      `setTimeout(function(){`
       ` console.log(traineddata)`
       ` callthis()`
     ` },300000)`
   ` }`
 ` })`
`function callthis(){`
  `console.log("completed")`
`}`

#### Environment details

  - OS: ubuntu 18.04
  - Node.js version: 8.10.0
  - npm version: 5.6.0
  - `dialogflow` version: 0.8.0
 

Thanks!

**Comment by nnegrey** [comment]
Alright so after some digging. https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Intent.TrainingPhrase.Part

When you create your intent:
You have to create your training phrases, but for the parts of your training phrase that you want assigned to an entity (or parameter), do you set the `entity_type` and `alias`

Here's a Java example:
I have already created the `test` entity.
```
Parameter parameter = Parameter.newBuilder()
          .setDisplayName("Test")
          .setEntityTypeDisplayName("@test")
          .setValue("$test")
          .build();

// The Part get's added to a TrainingPhrase, which is added to the Intent.
Part.newBuilder()
              .setText(phrase)
              .setEntityType("@test")
              .setAlias("Test")
              .build()
```

Is this about how you are creating `Intent`s?

**Comment by jaymovaliya** [comment]
Yes i am setting entity type and alias while creating intent with training phrases.
Look at snapshot of code in JavaScript :
`var word = getValue(result[1],0)`
          `var entity = getEntityValue(result[1])`
         ` partObj['text'] = word + ' '`
         ` partObj['entityType'] = '@' + entity`
          `partObj['alias'] = entity`
          ` tmpArrCombine.push(word)`

**Comment by nnegrey** [comment]
I'm able to get it working with:

```
  // [START dialogflow_create_intent]
  // Imports the Dialogflow library
  const dialogflow = require('dialogflow');

  // Instantiates the Intent Client
  const intentsClient = new dialogflow.IntentsClient();

  // The path to identify the agent that owns the created intent.
  const agentPath = intentsClient.projectAgentPath(projectId);

  const trainingPhrases = [];

  const part = {
    text: 'Number of Customers During Non-mealtime',
    entityType: '@KPIs',
    alias: 'KPIs',
  };

  const part1 = {
    text: 'today',
    entityType: '@customGranularity',
    alias: 'customGranularity',
  };

  // Here we create a new training phrase for each provided part.
  const trainingPhrase = {
    type: 'EXAMPLE',
    parts: [part, part1],
  };

  trainingPhrases.push(trainingPhrase);

  const parameter = {
    displayName: 'KPIs',
    entityTypeDisplayName: '@KPIs',
    value: 'Number of Customers During Non-mealtime',
  }

  const parameter1 = {
    displayName: 'customGranularity',
    entityTypeDisplayName: '@customGranularity',
    value: 'today',
  }

  const messageText = {
    text: messageTexts,
  };

  const message = {
    text: messageText,
  };

  const intent = {
    displayName: displayName,
    trainingPhrases: trainingPhrases,
    messages: [message],
    parameters: [parameter, parameter1],
  };

  const createIntentRequest = {
    parent: agentPath,
    intent: intent,
  };

  // Create the intent
  const responses = await intentsClient.createIntent(createIntentRequest);
  console.log(`Intent ${responses[0].name} created`);
```
Does this work for you?

**Comment by bcoe** [comment]
@jaymovaliya, can you confirm whether @nnegrey's approach works for you?

**Comment by jaymovaliya** [comment]
That's working for me,
But i am crating multiple intents together with more than 100 training phrases at that time it is not working.

**Comment by jahe** [comment]
Hi @jaymovaliya! 👋

I had the same issue and figured out that the field `parameters` must be set with entities you expect in the response.

**Intent** (https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2/projects.agent.intents#Intent)
```
"parameters": [{
  "name": string,
  "displayName": string,
  "value": string,
  "defaultValue": string,
  "entityTypeDisplayName": string,
  "mandatory": boolean,
  "prompts": [
    string
  ],
  "isList": boolean
}]
```

**Comment by callmehiphop** [comment]
There hasn't been a whole lot of activity on this thread lately and I believe it has been answered, so I'm going to close it out. If you feel that this was an error, let us know and we'll be happy to re-open/investigate 😎

**Comment by Istorn** [comment]
> I'm able to get it working with:
> 
> ```
>   // [START dialogflow_create_intent]
>   // Imports the Dialogflow library
>   const dialogflow = require('dialogflow');
> 
>   // Instantiates the Intent Client
>   const intentsClient = new dialogflow.IntentsClient();
> 
>   // The path to identify the agent that owns the created intent.
>   const agentPath = intentsClient.projectAgentPath(projectId);
> 
>   const trainingPhrases = [];
> 
>   const part = {
>     text: 'Number of Customers During Non-mealtime',
>     entityType: '@KPIs',
>     alias: 'KPIs',
>   };
> 
>   const part1 = {
>     text: 'today',
>     entityType: '@customGranularity',
>     alias: 'customGranularity',
>   };
> 
>   // Here we create a new training phrase for each provided part.
>   const trainingPhrase = {
>     type: 'EXAMPLE',
>     parts: [part, part1],
>   };
> 
>   trainingPhrases.push(trainingPhrase);
> 
>   const parameter = {
>     displayName: 'KPIs',
>     entityTypeDisplayName: '@KPIs',
>     value: 'Number of Customers During Non-mealtime',
>   }
> 
>   const parameter1 = {
>     displayName: 'customGranularity',
>     entityTypeDisplayName: '@customGranularity',
>     value: 'today',
>   }
> 
>   const messageText = {
>     text: messageTexts,
>   };
> 
>   const message = {
>     text: messageText,
>   };
> 
>   const intent = {
>     displayName: displayName,
>     trainingPhrases: trainingPhrases,
>     messages: [message],
>     parameters: [parameter, parameter1],
>   };
> 
>   const createIntentRequest = {
>     parent: agentPath,
>     intent: intent,
>   };
> 
>   // Create the intent
>   const responses = await intentsClient.createIntent(createIntentRequest);
>   console.log(`Intent ${responses[0].name} created`);
> ```
> 
> Does this work for you?

Hi dear, could you please provide an example with data?

**Comment by shzamani** [comment]
Hi,

I am having the same problem but the issue (bug) is still not solved. Can you please provide an example with your data?



> Hi @jaymovaliya! 👋
> 
> I had the same issue and figured out that the field `parameters` must be set with entities you expect in the response.
> 
> **Intent** (https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2/projects.agent.intents#Intent)
> 
> ```
> "parameters": [{
>   "name": string,
>   "displayName": string,
>   "value": string,
>   "defaultValue": string,
>   "entityTypeDisplayName": string,
>   "mandatory": boolean,
>   "prompts": [
>     string
>   ],
>   "isList": boolean
> }]
> ```

Hi,

I am having the same problem but the issue (bug) is still not solved. Can you please provide an example with your data? because I do set entitytypeDisplayName as the entity I expect, but it doesn't help.
