### ISSUE TITLE
where do you have the documents for this ibrary?

### ISSUE THREAD

**Issue by malikasinger1** [googleapis/nodejs-dialogflow#308]
I am unable to find proper documentation of this library

I need interface of this(sessionClient.detectIntent) method: 

```
...
const request = {
      session: sessionPath,
      queryInput: {
        text: {
          // The query to send to the dialogflow agent
          text: data.text,
          // The language used by the client (en-US)
          languageCode: 'en-US',
        },
      },
    };

    // Send request and log result
    const responses = await sessionClient.detectIntent(request);
...
```

**Comment by malikasinger1** [comment]
I want to send custom data with the detect intent request

**Comment by callmehiphop** [comment]
@malikasinger1 here's a [link](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2) to all the RPCs.

Looking at the docs for [DetectIntentRequest](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.DetectIntentRequest), I think you can do something like this

```js
const request = {
  queryParams: {
    payload: {
      key: 'value'
    }
  }
};
```

**Comment by malikasinger1** [comment]
thanks @callmehiphop for such quick response

**Comment by callmehiphop** [comment]
@malikasinger1 no problem, let me know if that solution works out for you!

**Comment by malikasinger1** [comment]
I have coded it like this but it is not working:

```
// The text query request.
    const request = {
      session: sessionPath,
      queryInput: {
        text: {
          // The query to send to the dialogflow agent
          text: data.text,
          // The language used by the client (en-US)
          languageCode: 'en-US',
        },
      },
      queryParams: {
        payload: {
          some: 'value'
        }
      }
    };
```
this is what i am getting in webhook: 

```Dialogflow Request body: {"responseId":"6d6166a2-9af8-44bf-9b62-f8e4e3a2f95e","queryResult":{"queryText":"what is the time","parameters":{"geo-city":""},"allRequiredParamsPresent":true,"fulfillmentText":"something went wrong while getting time","fulfillmentMessages":[{"text":{"text":["something went wrong while getting time"]}}],"intent":{"name":"projects/bilal-assistant/agent/intents/0eaab610-7a55-4b22-98b0-8941cf412026","displayName":"what is time"},"intentDetectionConfidence":0.75,"languageCode":"en-us"},"originalDetectIntentRequest":{"payload":{}},"session":"projects/bilal-assistant/agent/sessions/web-sessionId"}```

**Comment by malikasinger1** [comment]
and the link you told me doesnt seems like document for this library because i can not find interface for this method in that document, even spellings are change: 
in documnt it is `query_params` but you told me to write it as `queryParams` and both are not working however,

same thing with the `query_input` which is working for me as i coded it `queryInput`
I need a real doucment like other people have such as mongodb mongoose(https://mongoosejs.com/docs/guide.html) and firebase firestore(https://firebase.google.com/docs/firestore/quickstart) do have

**Comment by malikasinger1** [comment]
that document is for dialogflow rpc, not for dialogflow v2 nodejs client library

**Comment by callmehiphop** [comment]
The actual Node.js docs can be found [here](https://cloud.google.com/nodejs/docs/reference/dialogflow/0.8.x/), but when looking at the `queryParams` field they just redirect you to the link I posted earlier. I agree the docs could be better, but unfortunately I don't really have any power/influence over them. @jkwlui might be able to provide some help there.

It looks like I made a mistake and the `payload` value needs a very specific structure and unfortunately right now there isn't a super easy way to achieve that (See https://github.com/googleapis/nodejs-dialogflow/issues/97).

```js
const queryParams = {
  fields: {
    key: {
      stringValue: 'value'
    }
  }
};
```

If you have a complex structure, I'd suggest using the [sample `jsonValueToProto` function](https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/structjson.js#L44) to do something like this

```js
const queryParams = jsonValueToProto({key: 'value'});
```

**Comment by malikasinger1** [comment]
I deep dive in the typing files of this library and my code is something like this now:

```
// The text query request.
    const request = {
      session: sessionPath,
      queryInput: {
        text: {
          // The query to send to the dialogflow agent
          text: data.text,
          // The language used by the client (en-US)
          languageCode: 'en-US',
        },
      },
      queryParams: {
        payload: {
          some: 'value'
        },
        timeZone: "gmt+5",
        geoLocation: {
          latitude: data.coords.latitude,
          longitude: data.coords.longitude
        }
      }
    };
```

but it is still not working and I am getting this on webhook:
```

Dialogflow Request body: {"responseId":"ba796220-5d0d-48b4-8ce7-02c7edad21a9","queryResult":{"queryText":"what is the time","parameters":{"geo-city":""},"allRequiredParamsPresent":true,"fulfillmentText":"something went wrong while getting time","fulfillmentMessages":[{"text":{"text":["something went wrong while getting time"]}}],"intent":{"name":"projects/bilal-assistant/agent/intents/0eaab610-7a55-4b22-98b0-8941cf412026","displayName":"what is time"},"intentDetectionConfidence":0.75,"languageCode":"en-us"},"originalDetectIntentRequest":{"payload":{}},"session":"projects/bilal-assistant/agent/sessions/web-sessionId"}


```

**Comment by malikasinger1** [comment]
let me try your second solution

**Comment by malikasinger1** [comment]
according to your second solution, now my code is something like this: 

``` 
//////////////////////////////////////////////////////////////////////////
// copied from https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/structjson.js#L44
function jsonValueToProto(value) {
  const valueProto = {};

  if (value === null) {
    valueProto.kind = 'nullValue';
    valueProto.nullValue = 'NULL_VALUE';
  } else if (value instanceof Array) {
    valueProto.kind = 'listValue';
    valueProto.listValue = { values: value.map(jsonValueToProto) };
  } else if (typeof value === 'object') {
    valueProto.kind = 'structValue';
    valueProto.structValue = jsonToStructProto(value);
  } else if (typeof value in JSON_SIMPLE_TYPE_TO_PROTO_KIND_MAP) {
    const kind = JSON_SIMPLE_TYPE_TO_PROTO_KIND_MAP[typeof value];
    valueProto.kind = kind;
    valueProto[kind] = value;
  } else {
    console.warn('Unsupported value type ', typeof value);
  }
  return valueProto;
}

function jsonToStructProto(json) {
  const fields = {};
  for (const k in json) {
    fields[k] = jsonValueToProto(json[k]);
  }

  return { fields };
}

const JSON_SIMPLE_TYPE_TO_PROTO_KIND_MAP = {
  [typeof 0]: 'numberValue',
  [typeof '']: 'stringValue',
  [typeof false]: 'boolValue',
};

////////////////////////////////////////////////////////////////////////////


const queryParams = jsonValueToProto({ key: 'value' });
   
    // The text query request.
    const request = {
      session: sessionPath,
      queryInput: {
        text: {
          // The query to send to the dialogflow agent
          text: data.text,
          // The language used by the client (en-US)
          languageCode: 'en-US',
        },
      },
      queryParams: queryParams
      // queryParams: {
      //   fields: {
      //     key: {
      //       stringValue: 'value'
      //     }
      //   },
      //   timeZone: "gmt+5",
      //   geoLocation: {
      //     latitude: data.coords.latitude,
      //     longitude: data.coords.longitude
      //   }
      // }
    };

    // Send request and log result
    const responses = await sessionClient.detectIntent(request);
```

and it is not working and i am getting payload empty in the webhook, did i made any mistake

**Comment by malikasinger1** [comment]
@jkwlui can you help?

**Comment by malikasinger1** [comment]
Anyone?

**Comment by JustinBeckwith** [comment]
Greetings @malikasinger1!  If you have specific questions like this, would you mind opening a new issue?  Just so we can keep the issues single purpose and organized :)

**Comment by malikasinger1** [comment]
@JustinBeckwith you deleted my comment, very unethical and unfair, if you are created something which is not usable because of improper docs atleast face it with open heart, my comment was relevant but no one will know that just because you deleted the comment, if you are concerned about your reputation please improve your services and I will appreciate not just here but in my youtube channel and udemy courses, however I am not going to use this library in my upcoming course because I am facing too much difficulties but I am still hopeful that you and your team will improve the documents enough so I will hopefully use this library in my course someday

**Comment by JustinBeckwith** [comment]
Greetings @malikasinger1!  I deleted a few of your previous comments on this issue.  One of them was unrelated to the original content of the thread, and it would be a lot easier for it to be posted in a new issue, specific to the follow-up question.   The second one I deleted violated our code of conduct, which you can read here:
https://github.com/googleapis/nodejs-dialogflow/blob/master/CODE_OF_CONDUCT.md

We'd love to help, we'd love to answer your questions - but please be aware that we're all humans too :)
