### ISSUE TITLE
Calling DetectIntent with v2beta1 gives error 401 with same Authentication process used for v2

### ISSUE THREAD

**Issue by khaledbnmohamed** [googleapis/nodejs-dialogflow#320]
Hi,

I was using DetectIntent API in v2 and it was working fine with Access token signed using JWT

one I migrated to v2beta1 in order to use Knowledge I receive for the exact same POST request 

> "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": 

> "UNAUTHENTICATED"
 
here is the whole POST request :

```
const options = {
    method: 'POST',
    host: 'dialogflow.googleapis.com',
    path: '/v2beta1/projects/'+ google_project_id +'/agent/environments/draft/users/6542423/sessions/124567:detectIntent',
    headers: {
      'Authorization': 'Bearer ' + google_access_token,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
```

the only change is in the path... Any idea if this is bug or a mistake from you ?

**Comment by callmehiphop** [comment]
I'm not sure if this is the right place for your question, this repo is for the gRPC client and it looks like you're manually building REST requests? You might have better luck over at https://github.com/googleapis/google-auth-library-nodejs

**Comment by khaledbnmohamed** [comment]
> I'm not sure if this is the right place for your question, this repo is for the gRPC client and it looks like you're manually building REST requests? You might have better luck over at https://github.com/googleapis/google-auth-library-nodejs

I'll check it . Thank you so much for your reply
