### ISSUE TITLE
Fulfillment request not displaying umlaut correctly

### ISSUE THREAD

**Issue by kwcolson** [googleapis/nodejs-dialogflow#334]
#### Environment details

V2 API
Enable beta features and APIs = true
Enable Automatic Text to Speech = true
Languages:
English - en = Default
German - de

Fulfillment = Inline Editor

package.json:

```json
  "dependencies": {
    "actions-on-google": "^2.2.0",
    "firebase-admin": "^5.13.1",
    "firebase-functions": "^2.0.2",
    "dialogflow": "^0.6.0",
    "dialogflow-fulfillment": "^0.6.0"
  }
```

I have a single intent that has:
Enable webhook call for this intent = true
Enable webhook call for slot filling = true

With the language code setting 'de' in the console, I create a request that has an umlaut:

3 Käsekuchen

Here is the diagnostic output snippet:

RAW API RESPONSE:
```json
"parameters": {
      "amount": "",
      "flavor": "Käsekuchen",
      "size": "",
      "product": "Käsekuchen"
    },
```

FULFILLMENT REQUEST:
```json
"parameters": {
      "product": "K�sekuchen",
      "amount": "",
      "flavor": "K�sekuchen",
      "size": ""
    },
```

So when I build my response in the fulfillment, it shows the weird characters for the umlaut, instead of the umlaut.

If I turn off the Webhook fulfillment and create a response in Dialogflow, the umlaut shows correctly.

Thank you.
Ken

**Comment by callmehiphop** [comment]
@kwcolson I apologize that so much time has passed, but are you still experiencing this issue?
