### ISSUE TITLE
Batch delete entities not deleting entities

### ISSUE THREAD

**Issue by jbdoster** [googleapis/nodejs-dialogflow#340]
[x] Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow/issues
  [x] Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  [x] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOs High Sierra 10.13.6 
  - Node.js version: v10.15.3
  - npm version: 6.4.1
  - `dialogflow` version: v2beta1

#### Steps to reproduce

  1. listEntities()
  2. deleteEntities(entities)

#### Notes

**Code**
```
async function listEntities() {
    const entityTypePath = ENTITY_PATH;
    const request = {
        name: entityTypePath,
    };
    const [response] = await ENTITY_TYPES_CLIENT.getEntityType(request);
    response.entities.forEach(entity => {
        console.log(`Entity value: ${entity.value}`);
        console.log(`Entity synonyms: ${entity.synonyms}`);
    });
    return response.entities;
}
async function deleteEntities(eValues) {
    const entityTypePath = ENTITY_PATH;
    const request = {
        parent: entityTypePath,
        entityValues: eValues,
    };
    await ENTITY_TYPES_CLIENT.batchDeleteEntities(request);
    console.log(`Entity Value ${eValues} deleted`);
}
async function main() {
    let entities = await listEntities(PROJECT_ID);
    deleteEntities(entities);
    console.log('Entities found', entities);
}
main()
```

**Output**
`Entity Value [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] deleted`

Though the entities are not deleted when I go back to the console? This is a test entity that I created and it is not linked to any intents yet. What am I doing wrong? Thank you!

**Comment by bcoe** [comment]
@jbdoster try:

```js
async function main() {
    let entities = await listEntities(PROJECT_ID);
    await deleteEntities(entities);
    entities = await listEntities(PROJECT_ID);
}
```

The variable `entities` is still populated with the values from your initial request.

**Comment by jbdoster** [comment]
@bcoe Thank you but unfortunately it did not work. All of the entities are still in the Dialogflow Console when I go to the "Entities" tab on the left.

**Comment by MumblesNZ** [comment]
@jadekler did you solve your issue?

**Comment by callmehiphop** [comment]
@jbdoster I took a closer look at your `BatchDeleteEntitiesRequest` object, it looks like you're sending the entire entity but the API only wants the entity value. I think you just need to make the following edit

```js
const entities = await listEntities(PROJECT_ID);
const entityValues = entities.map(entity => entity.value);
await deleteEntities(entityValues);
```

**Comment by callmehiphop** [comment]
I'm going to close this out, but if my solution didn't work and you continue to encounter this issue please let us know!
