### ISSUE TITLE
split samples into one sample per file

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-dialogflow#358]
We can't currently auto-generate the README.md and samples/README.md because all samples are currently contained in a single `resource.js` file.

It would be nice to split this out into individual files and move to automated README generation.

**Comment by callmehiphop** [comment]
@beccasaurus does the ML team have plans to tackle this? Otherwise I can probably take it on soonish

**Comment by beccasaurus** [comment]
We do have plans :)

DF samples are being migrated to GAPIC sample generation

**Comment by munkhuushmgl** [comment]
I will split out samples in individual files
