### ISSUE TITLE
Sending `payload` for new or updated intent results in empty object in console

### ISSUE THREAD

**Issue by Fleker** [googleapis/nodejs-dialogflow#367]
### Environment details

  - OS: GLinux
  - Node.js version: v8.15.0
  - npm version: v6.4.0
  - `dialogflow` version: v0.7.0

#### Steps to reproduce

  1. Create or update an intent with a payloads field.

```
{
	"displayName": "help",
	"isFallback": false,
	"webhookState": "WEBHOOK_STATE_UNSPECIFIED",
	"mlEnabled": false,
	"priority": 500000,
	"trainingPhrases": [{
		"type": "EXAMPLE",
		"parts": [{
			"text": " Help me "
		}]
	}],
	"parameters": [],
	"messages": [{
		"platform": "PLATFORM_UNSPECIFIED",
		"payload": {
			"expectUserResponse": true,
			"isSsml": false,
			"noInputPrompts": [],
			"richResponse": {
				"items": [{
					"simpleResponse": {
						"displayText": "hi",
						"textToSpeech": "hello"
					}
				}],
				"suggestions": [{
					"title": "Say this"
				}, {
					"title": "or this"
				}]
			},
			"systemIntent": {
				"data": {
					"@type": "type.googleapis.com/google.actions.v2.OptionValueSpec",
					"listSelect": {
						"items": [{
							"optionInfo": {
								"key": "key1",
								"synonyms": ["key one"]
							},
							"title": "must not be empty, but unique"
						}, {
							"optionInfo": {
								"key": "key2",
								"synonyms": ["key two"]
							},
							"title": "must not be empty, but unique"
						}]
					}
				},
				"intent": "actions.intent.OPTION"
			}
		}
	}],
	"defaultResponsePlatforms": ["ACTIONS_ON_GOOGLE"]
}
```

  2. Create intent

```
...
const creationResponse = await intentsClient.createIntent({
          parent,
          languageCode: intent._languageCode,
          intent: dfIntent
})
...
```

  3. Go to the Dialogflow console and open the intent

![image](https://user-images.githubusercontent.com/3291635/59387747-f1259300-8d37-11e9-9641-4bb0abf50dab.png)

Notice how it is an empty object instead of the payload that I expected to send. I tried several different payloads from the Dialogflow and Actions on Google documentation, although it never seems to be any different.

Contrariwise, sending plain text responses does work as intended, so I am not sure if there is an issue with the payload object or if the `platform` needs to change. Is this field validated before being stored in the console?

**Comment by callmehiphop** [comment]
👋 @Fleker I think you need to send the `payload` field as a [protobuf Struct](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Struct). Unfortunately the client doesn't perform this conversion (yet?) but you can use [pb-util](https://www.npmjs.com/package/pb-util) to encode plain objects into structs.

**Comment by Fleker** [comment]
Yes, that was exactly what I needed to do. Thanks.
