### ISSUE TITLE
In streamingDetectIntent sample parameter `singleUtterance` specified incorrectly and has no effect

### ISSUE THREAD

**Issue by sv2** [googleapis/nodejs-dialogflow#374]
In streamingDetectIntent sample parameter `singleUtterance` specified incorrectly and has no effect

# Environment details

  - OS: Windows 8 
  - Node.js version: 10.11.0
  - npm version: 6.3.0
  - `dialogflow` version: 0.10.1

#### Steps to reproduce

https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js#L206

Currently:

```
const initialStreamRequest = {
    session: sessionPath,
    queryParams: {
      session: sessionClient.sessionPath(projectId, sessionId),
    },
    queryInput: {
      audioConfig: {
        audioEncoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
      },
      singleUtterance: true,
    },
  };
```
 
Should be:

```
const initialStreamRequest = {
    session: sessionPath,
    queryParams: {
      session: sessionClient.sessionPath(projectId, sessionId),
    },
    queryInput: {
      audioConfig: {
        audioEncoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
      }
    },
    singleUtterance: true
  };
```

Thanks!

**Comment by MumblesNZ** [comment]
Hey @sv2 it looks like singleUtterance on the StreamingDetectIntentRequest level is deprecated, and now only supports it on the InputAudioConfig level. I.E:
```

const initialStreamRequest = {
    session: sessionPath,
    queryParams: {
      session: sessionClient.sessionPath(projectId, sessionId),
    },
    queryInput: {
      audioConfig: {
        audioEncoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
        singleUtterance: true
      }
    }
  };

```

See https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.StreamingDetectIntentRequest.FIELDS.string.google.cloud.dialogflow.v2.StreamingDetectIntentRequest.session.

**Comment by sv2** [comment]
Thank you!

**Comment by b-loved-dreamer** [comment]
This issue has been handled. Reference [this](https://github.com/googleapis/nodejs-dialogflow/pull/739) for details. Closing this issue.
