### ISSUE TITLE
Update Dialogflow agent configuration

### ISSUE THREAD

**Issue by patrick-zimmermann** [googleapis/nodejs-dialogflow#380]
**Is your feature request related to a problem? Please describe.**
No.
 
**Describe the solution you'd like**
I would like to update the configuration of an agent (e.g. supported languages or threshold), instead of importing an entire agent with all of the intents and entities.

 **Describe alternatives you've considered**
Provide the capability to perform "custom" request agains the dialogflow api by specifying the api endpoint by yourself. Additionally you should be able to set path and query parameters, as well as a request body if necessary.

 **Additional context**
The [REST API](https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects/agent) as well as the [agent](https://cloud.google.com/dialogflow/docs/reference/rest/v2/Agent) object.

**Comment by patrick-zimmermann** [comment]
Hey, are there any updates regarding that topic?
I still would need the capability to update the agent configuration, such as changing the supported language codes, adjusting the classification threshold or even adding the google action configuration (which isn't even part of the agent object).

I just would like to know if such a feature is even considered for future development.

**Comment by callmehiphop** [comment]
@patrick-zimmermann this library is actually just generated from a proto file maintained by the backend team. Any new features wouldn't be developed here, but instead would be implemented by some one on the API team. You might have better luck opening an issue on the [product tracker](https://cloud.google.com/support/docs/issue-trackers).

**Comment by jdelman** [comment]
@patrick-zimmermann With the V2 API, you can call the `setAgent` method: https://github.com/googleapis/nodejs-dialogflow/blob/master/src/v2/agents_client.js#L315

**Comment by patrick-zimmermann** [comment]
@jdelman thanks for the advice. I integrated the `setAgent` some months ago. Until now I never realized that the function resets some manually set values on Dialogflow such as the **Automatic Training**, **Agent Validation** as well as the **Sentiment Analysis**.

After the `setAgent` function was executed successfully the values switch too false and are disabled even thought all of them had been enabled before. Did you ever experienced the same behaviour?

**Comment by acoroleu-tempus** [comment]
Any updates on this?
From dialogflow console I see there's this request which updates agent settings:
Request URL: `https://dialogflow.clients6.google.com/v2beta1/projects/[agentId]/locations/global/agent:updateSettings?alt=json&key=[apiKey}`
Which seems allowed to change **Automatic Training**.
How can we perfom that request using this library?

**Comment by gad2103** [comment]
i would also like to know if there is any plan for allowing access to the UI api for `https://dialogflow.clients6.google.com/v2beta1/projects/[agentId]/locations/global/agent:updateSettings?alt=json&key=[apiKey}`

it allows you to set speech settings and other valuable fields for the agent. here's an example payload:
```
{"agentSettings":{"enableSmalltalk":false,"enableValidation":false,"enableSpeechRequestContext":true,"enableAgentWideKnowledgeConnector":false,"knowledgeBaseNames":[],"knowledgeConfidenceAdjustment":0,"textToSpeechSettings":{"enableTextToSpeech":true,"outputAudioEncoding":"OUTPUT_AUDIO_ENCODING_LINEAR_16","synthesizeSpeechConfigs":{"en":{"speakingRate":1,"pitch":0,"volumeGainDb":0,"effectsProfileId":[],"voice":{"name":"en-US-Wavenet-F","customVoice":{}}}}}},"updateMask":"enableStackdriverLogging,enableSmalltalk,enableSpellCorrection,disableAutomaticTraining,enableValidation,enableSpeechLogging,enableSpeechRequestContext,endpointerSensitivity,enableSentimentAnalysis,enableAgentWideKnowledgeConnector,enableCustomSpeechModels,knowledgeBaseNames,knowledgeConfidenceAdjustment,textToSpeechSettings"}

**Comment by arbc** [comment]
> i would also like to know if there is any plan for allowing access to the UI api for `https://dialogflow.clients6.google.com/v2beta1/projects/[agentId]/locations/global/agent:updateSettings?alt=json&key=[apiKey}`
> 
> it allows you to set speech settings and other valuable fields for the agent. here's an example payload:
> 
> ```
> {"agentSettings":{"enableSmalltalk":false,"enableValidation":false,"enableSpeechRequestContext":true,"enableAgentWideKnowledgeConnector":false,"knowledgeBaseNames":[],"knowledgeConfidenceAdjustment":0,"textToSpeechSettings":{"enableTextToSpeech":true,"outputAudioEncoding":"OUTPUT_AUDIO_ENCODING_LINEAR_16","synthesizeSpeechConfigs":{"en":{"speakingRate":1,"pitch":0,"volumeGainDb":0,"effectsProfileId":[],"voice":{"name":"en-US-Wavenet-F","customVoice":{}}}}}},"updateMask":"enableStackdriverLogging,enableSmalltalk,enableSpellCorrection,disableAutomaticTraining,enableValidation,enableSpeechLogging,enableSpeechRequestContext,endpointerSensitivity,enableSentimentAnalysis,enableAgentWideKnowledgeConnector,enableCustomSpeechModels,knowledgeBaseNames,knowledgeConfidenceAdjustment,textToSpeechSettings"}
> ```
> 
> i don't see any protobuf files for agentSettings...

Any news regarding this subject? I would also like to know 🙏

**Comment by hshah965** [comment]
> i would also like to know if there is any plan for allowing access to the UI api for `https://dialogflow.clients6.google.com/v2beta1/projects/[agentId]/locations/global/agent:updateSettings?alt=json&key=[apiKey}`
> 
> it allows you to set speech settings and other valuable fields for the agent. here's an example payload:
> 
> ```
> {"agentSettings":{"enableSmalltalk":false,"enableValidation":false,"enableSpeechRequestContext":true,"enableAgentWideKnowledgeConnector":false,"knowledgeBaseNames":[],"knowledgeConfidenceAdjustment":0,"textToSpeechSettings":{"enableTextToSpeech":true,"outputAudioEncoding":"OUTPUT_AUDIO_ENCODING_LINEAR_16","synthesizeSpeechConfigs":{"en":{"speakingRate":1,"pitch":0,"volumeGainDb":0,"effectsProfileId":[],"voice":{"name":"en-US-Wavenet-F","customVoice":{}}}}}},"updateMask":"enableStackdriverLogging,enableSmalltalk,enableSpellCorrection,disableAutomaticTraining,enableValidation,enableSpeechLogging,enableSpeechRequestContext,endpointerSensitivity,enableSentimentAnalysis,enableAgentWideKnowledgeConnector,enableCustomSpeechModels,knowledgeBaseNames,knowledgeConfidenceAdjustment,textToSpeechSettings"}
> ```
> 
> i don't see any protobuf files for agentSettings...

@gad2103 @acoroleu-tempus Is this API still working? Tried updating the settings using this API by generating bearer token with a service account having Dialogflow API Admin permission and still getting an error "Method Not Found". I was able to get it work a few months ago.
