### ISSUE TITLE
400 invalid argument error while using listEntityTypes

### ISSUE THREAD

**Issue by sagarmk** [googleapis/nodejs-dialogflow#382]
#### Environment details

  - OS: red hat 7
  - Node.js version: 8.0.0
  - npm version: 5.0.0
  - `dialogflow` version: 2.0

#### Steps to reproduce

  1. Trying to executing listEntityTypes using projectId as stated in the documentation
  2. Experiencing error at the asyn function defn level specifically at,
const [response] = await entityTypesClient.listEntityTypes(request);

error is being thrown as invalid argument  where it says 
`'com.google.apps.framework.request.BadRequestException: Validate entity failed because of the following reasons: An Entity whose kind = \'KIND_LIST\' must contain exactly one synonym equal to value. While its value is [some names] and synonyms are [some names, othernames1, othernames2].
`

would have said if the UI threw the same error, also I am not mentioning tht anywhere in the api call, here all I do is give it a project id

**Comment by callmehiphop** [comment]
Hi @sagarmk is this still an issue for you? If so could you provide us an example of what parameters you are sending with the request?
