### ISSUE TITLE
How can I make a permanent session?

### ISSUE THREAD

**Issue by DKLeoBR** [googleapis/nodejs-dialogflow#385]
hat if the user takes 30 minutes to respond? Dialogflow drops the intent. is there any way to make this intention infinite and wait for this "yes" or "no"
for example
User: I Need a T-shirt
Bot: Yes, We Have, what color?
User: Red
Bot: Ok to Red T-shit, P, M or G?
User: Wait, I'll see with my Wife

    60 Minutes *
    User: Need G
    Bot: What?

See the problem? Bot Ends session, and no matter if you set "lifespan" to 999
How can i do a permanent session using INLINE editor of dialogflow
example codes please?
thanks

**Comment by nnegrey** [comment]
I believe Dialogflow only holds such information for 20 minutes whether that be in Sessions or Contexts.
