### ISSUE TITLE
User speaks too slow-the bot cuts off before the user finishes his/her sentence

### ISSUE THREAD

**Issue by CrystalSNS** [googleapis/nodejs-dialogflow#394]
Hello, 

I am looking for a way to make my bot wait longer when a user talk too slowly or a long sentence. 
For now, the bot always cuts off when the user makes a pause.

Can you please give me some clues?
Thanks,

**Comment by nnegrey** [comment]
Is this using a sample and is it streaming?
If so, the streaming sample has `singleUtterance: true,`

Set that to `false`. 

From the docs: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#inputaudioconfig
"""
Optional. If false (default), recognition does not cease until the client closes the stream. If true, the recognizer will detect a single spoken utterance in input audio. Recognition ceases when it detects the audio's voice has stopped or paused. In this case, once a detected intent is received, the client should close the stream and start a new request with a new stream as needed. Note: This setting is relevant only for streaming methods. Note: When specified, InputAudioConfig.single_utterance takes precedence over StreamingDetectIntentRequest.single_utterance.
"""

If this doesn't solve the issue, feel free to reopen.

**Comment by psatyawan-wexinc** [comment]
I face this issue with our current setup, even though singleUtterance is set to false.
