### ISSUE TITLE
Detect Intent from audio file always return empty response

### ISSUE THREAD

**Issue by shaileshkulkarni** [googleapis/nodejs-dialogflow#395]
Hello,

I have edited default welcome intent in the Dialogflow project to respond 'Welcome to ABC Inc'.

Tried the examples given in the following links
https://cloud.google.com/dialogflow/docs/detect-intent-audio#detect-intent-audio-nodejs

In both cases it simply returns empty response. No intent is detected.
However in the Dialogflow History section also, it does not show up anything indicating that it got invoked from test client.

Also I have enabled webhook and trying to just put log message indicating it got called. But its not logging over there confirming that its not getting invoked.

The input audio file is in mp3 format only. I also tried with the opus file format with simple "Hello" audio for "en-US".

I tried to play mp3 and opus file and I could clearly hear "Hello", there was little background noise but that should not be an issue. I think, when its trying to so Speech to text its not able to get anything and hence its not getting invoked for dialogflow for detection. But thats my guess.

Can someone help what is missing over here?

Thanks,
Shailesh

**Comment by shaileshkulkarni** [comment]
Node JS Code

// Imports the Dialogflow library
const dialogflow = require('dialogflow');

// Instantiates a session client
const sessionClient = new dialogflow.SessionsClient();

// The path to the local file on which to perform speech recognition, e.g.
// /path/to/audio.raw 
const filename = 'C:/DialogflowTest/hello1.mp3';

// The encoding of the audio file, e.g. 'AUDIO_ENCODING_LINEAR_16'
const encoding = 'AUDIO_ENCODING_LINEAR_16';   //'AUDIO_ENCODING_OGG_OPUS';

// The sample rate of the audio file in hertz, e.g. 16000
const sampleRateHertz = 16000;

// The BCP-47 language code to use, e.g. 'en-US'
const languageCode = 'en-US';

const projectId = "testagent-265c0";

const uuid = require('uuid');
const sessionId = uuid.v4();

const util = require('util');
const fs = require('fs');

const sessionPath = sessionClient.sessionPath(projectId, sessionId);
const base64 = require('base-64');
const utf8 = require('utf8');

async function detectIntentUsingAudio(projectId, sessionId, filename){
	// Read the content of the audio file and send it as part of the request.
	console.log("ProjectId : " + projectId + " : sessionId : " + sessionId + " : filename : " + filename);
	//const readFile = util.promisify(fs.readFile);
	const inputAudio = fs.readFileSync(filename).toString('base64');
	
	console.log("File read ----");
	//console.dir(inputAudio);
	
	//var bytes = utf8.encode(inputAudio);
	//console.log("After utf encoding");
	
	const request = {
		session: sessionPath,
		queryInput: {
		  audioConfig: {
			audioEncoding: encoding,
			sampleRateHertz: sampleRateHertz,
			languageCode: languageCode,
		  },
		},
		inputAudio: inputAudio,
		outputAudioConfig: {
			audioEncoding: 'OUTPUT_AUDIO_ENCODING_MP3',
		}
	};
	
	
	console.log("Sending audio request : ");
	//console.dir(request);

	// Recognizes the speech in the audio and detects its intent.
	const [response] = await sessionClient.detectIntent(request);

	console.log('Detected intent:');
	console.dir(response);		
}

process.env.GOOGLE_APPLICATION_CREDENTIALS = "C:/DialogflowTest/TestAgent-9784c03dc05b.json"

console.log("Detect Intent request using Streaming Audio : sessionId : " + sessionId);

detectIntentUsingAudio(projectId, sessionId, filename).then(function(e){
	console.log("success");
}).catch(function(e){
	console.log("Error :::: "+ e);
})

**Comment by nnegrey** [comment]
Have you tried with one of the provided audio files?
https://github.com/googleapis/nodejs-dialogflow/tree/master/samples/resources
