### ISSUE TITLE
The frontend js code of our web app did ajax call to Dialogflow V2 APIs: Encountered this error: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at xxxxxxx

### ISSUE THREAD

**Issue by eGlobeBizCom** [googleapis/nodejs-dialogflow#397]
The frontend js code of our web app did ajax call to Dialogflow V1 APIs of our chatbot for around 2 years without problem. Our ajax call code look like the following:

```js
  $.ajax({
      //crossDomain: true,
      type: "POST",
      url: baseUrl + "query",
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      headers: {
        Authorization: "Bearer " + accessToken
      },
      data: JSON.stringify({
        query: text_new,
        lang: "en",
        sessionId: "yaydevdiner"
      }),
```

Dialogflow V1 REST APIs stopped working around June 21/2019.  Now we need to enable our app client js code to call Dialogflow V2 REST APIs within short time.

I know that here the nodejs Dialogflow SDK team encourages us to place the code calling  Dialogflow V2 REST APIs through Google Cloud Service Account key.  As we need to fix this problem shortly and our major logic is in the client js file, we decided to reach this goal in the existing client js file and make the following changes  after discussing with the Dialogflow Support team.

I deployed the following code in the existing client js file:

```js
$.ajax({
       crossDomain: true,
      type: "POST",
      url: baseUrl + "queryText",
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      headers: {
        Authorization: "Bearer " + accessToken
      },

      data: JSON.stringify
     ({
          queryText: text_new,
        languageCode: "en"
      }),

accessToken = "ourChatbotPrivateKey.json",
 baseUrl = "https://dialogflow.googleapis.com/v2/projects/OurChatBotID/agent/sessions/OurChatbotSessionID:detectIntent",
```

Besides the above small changed code, the whole code package was working and has no change. After this code web app package is deployed to Firebase, we found the following error message in several browser console:

```
OPTIONS https://dialogflow.googleapis.com/v2/projects/ourChatbotID/agent/sessions/ourChatbotSessionID:detectIntentqueryText 404
(index):1 Access to XMLHttpRequest at 'https://dialogflow.googleapis.com/v2/projects/ourChatbotID/agent/sessions/ourChatbotSessionID:detectIntentqueryText' from origin 'https://ourProjectID.firebaseapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dialogflow.googleapis.com/v2/projects/ourChatbotID/ourChatobtSessionID:detectIntentqueryText. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing
```

Based on the above, my estimation about this problem: This line of hacking code is refused by Dialogflow V2 APIs server.

```
baseUrl = "https://dialogflow.googleapis.com/v2/projects/OurChatBotID/agent/sessions/OurChatbotSessionID:detectIntent
```

I understand that here is about nodejs-dialogflow. But there are no other places for me to get help for the above issue.  I know the readers of this page and this library team understand javascript and the above issue.  Any suggestions are warmly welcome.

**Comment by bcoe** [comment]
@eGlobeBizCom :wave: this is the repository for our gRPC client (which allows you to connect to the dialogflow API using http2/Node.js).

As of right now, this client does not work in the browser, and the recommended approach we point people towards for writing a client side application with dialogflow is to create a server that their application talks to, which in turn runs the dialogflow API; If you were to use this approach, your AJAX calls would be made to your own local server, and you wouldn't bump into these CORS issues.

Having said this, if you do want to take the approach of using a REST API, you just need to make sure that the website serving your frontend client serves the proper CORS headers:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

You might also look at our apiary client which helps simplify the process of interacting with our REST APIs:

https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/dialogflow

Hope this helps unblock you :+1:

**Comment by eGlobeBizCom** [comment]
@bcoe  Thank you for your timely feedback.  I have a follow up Q on this.


# This feature on the following library is useful to us
=================
Retrieve access token
With the code returned, you can ask for an access token as shown below:
const tokens = await oauth2Client.getToken(code);
// Now tokens contains an access_token and an optional refresh_token. Save them.
oauth2Client.setCredentials(tokens);
====================
https://github.com/googleapis/google-auth-library-nodejs



# After the above AccessToken is obtained, I am thinking to pass this AccessToken into the ajax call in our client js file  calling Dialogflow V2 APIs .  I saw this worked in the following post:
==================
Create a nodejs application and use “google-oauth-jwt” to get the access token. Also, make this as a service to call it before hand to have the access token ready before making any ajax calls. Here is sample code:
https://stackoverflow.com/questions/50633291/how-can-i-make-http-call-to-dialogflow-v2-using-simple-ajax-jquery?rq=1
========================


# But the above post is about one year old. I wish to confirm that if the AccessToken is still accepted by Dialogflow V2 APIs  before spending lots of our time on setting this up. 

Any thoughts and suggestions will be highly appreciated.
