### ISSUE TITLE
migrate dialogflow to googleapis.dev/generated README

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-dialogflow#406]
Dialogflow still has our old README format and old reference doc generation. We should make this library consistent with the majority of our Node.js client libraries.

see: https://github.com/googleapis/nodejs-dialogflow/issues/402

**Comment by b-loved-dreamer** [comment]
From the [README](https://googleapis.dev/nodejs/dialogflow/latest/index.html). Closing this issue.
