### ISSUE TITLE
V2 migration issue

### ISSUE THREAD

**Issue by crisboarna** [googleapis/nodejs-dialogflow#407]
Hello, 

I have done migration on my agent to v2 as mentioned in docs by creating new agent and importing, I am also using the https://github.com/googleapis/nodejs-dialogflow package to interact with it. 

Upon downloading credentials and successfully connecting to the agent, simple queries which work on web console on dialogflow.com return empty in NodeJS.

It does not recognize any intent I have created and am uncertain how to proceed with it.

I have enabled billing on GCP and setup IAM.

Could you please help me out on solving this ?

**Comment by bcoe** [comment]
@crisboarna could you please include an example of the Node.js code you are running?

**Comment by crisboarna** [comment]
```
const dialogflow = require('dialogflow');
this.sessionClient = new dialogflow.SessionsClient();
this.sessionPath = this.sessionClient.sessionPath(projectId, sessionId);
const response = await _this.sessionClient.detectIntent({
   session: _this.sessionPath,
       queryInput: {
       text: {
          text: context.message.text.toLowerCase(),
          languageCode: 'en'
       }
   }
});
```

I have tried both 
`const dialogflow = require('dialogflow');` and `const dialogflow = require('dialogflow').v2;` with no luck/difference.

**Comment by bcoe** [comment]
@crisboarna this source looks a little odd to me, operations should be performed on the `dialogflow` instance, not `this`. Take a look at the `detectIntent` sample:

https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect-intent-sentiment.v2.js

```js
 const sessionClient = new dialogflow.SessionsClient();

  /**
   * TODO(developer): Uncomment the following lines before running the sample.
   */
  // const projectId = 'ID of GCP project associated with your Dialogflow agent';
  // const sessionId = `user specific ID of session, e.g. 12345`;
  // const query = `phrase(s) to pass to detect, e.g. I'd like to reserve a room for six people`;
  // const languageCode = 'BCP-47 language code, e.g. en-US';

  // Define session path
  const sessionPath = sessionClient.sessionPath(projectId, sessionId);

  async function detectIntentandSentiment() {
    // The text query request.
    const request = {
      session: sessionPath,
      queryInput: {
        text: {
          text: query,
          languageCode: languageCode,
        },
      },
      queryParams: {
        sentimentAnalysisRequestConfig: {
          analyzeQueryTextSentiment: true,
        },
      },
    };

    // Send request and log result
    const responses = await sessionClient.detectIntent(request);
```

**Comment by callmehiphop** [comment]
@crisboarna did @bcoe's suggestion help you out at all?
