### ISSUE TITLE
Training Phrases missing on getIntent

### ISSUE THREAD

**Issue by shotamakino** [googleapis/nodejs-dialogflow#409]
The getIntent response value and the listIntents response always reads an empty array for its trainingPhrases value.

#### Environment details

  - OS:
  - Node.js version: 10.15.3
  - npm version: 6.9.0
  - `dialogflow` version: 0.10.3

#### Steps to reproduce

  1. call getIntents on an intent with training phrases listed in console

**Comment by shotamakino** [comment]
Ah did not set the IntentView. Closing.

**Comment by RezaRahmati** [comment]
this is still an issue, any fix for it?

**Comment by RezaRahmati** [comment]
in case somebody else has same issue, request should include `intentView` with value `1` to return `trainignPhrases`

```
        const request = {
            parent: projectAgentPath,
            intentView: 1 // INTENT_VIEW_FULL
        };
```
