### ISSUE TITLE
Parameters entity type and training phrases are not detected

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#411]
This is the function I'm using to set training phrases, parameters and responses of my entity:

```js
async function createIntent(
    projectId,
    displayName,
    trainingPhrases,
    messageTexts,
    parameters=[]
    
  ) {
    // [START dialogflow_create_intent]
    // Imports the Dialogflow library
    const dialogflow = require('dialogflow');
  
    // Instantiates the Intent Client
    const intentsClient = new dialogflow.IntentsClient(
        {credentials: credentials,}
    );
  
    // The path to identify the agent that owns the created intent.
    const agentPath = intentsClient.projectAgentPath(projectId);
  
    const trainingPhrasesBOT = [];
    
    //Prendiamo tutte le trainingPhrases
    trainingPhrases.forEach(trainingPhrase => {
      //Prendiamo tutte le loro parti
      var parts=[];
      trainingPhrase.forEach((piece)=>{
        
        //In questo punto, verifichiamo se il pezzo della frase è un parametro oppure un semplice pezzo di testo
        if (piece.entityType!=undefined){
          //Pezzo che contiene un termine chiave per un dato parametro
          var part = {
            text: piece.text,
            entityType: piece.entityType,
            alias:piece.alias,
          };
          parts.push(part);
        }
        else{
          //Pezzo di frase normale
          var part = {
            text: piece.text,
            entityType:" ",
            alias:" ",
          };
          parts.push(part);
        }
        
      });
      //A questo punto costruiamo la trainingphrase
      const trainingPhraseFinal = {
        type: 'EXAMPLE',
        parts: parts,
      };
  
      trainingPhrasesBOT.push(trainingPhraseFinal);
      parts=[];
      
  
      
    });
    
    const parameterBOT=[];
    parameters.forEach((parameter)=>{
      //ci prendiamo tutti i suoi attributi
      parameterBOT.push({
        displayName:parameter.name,
        entityDisplayName: "@"+parameter.name,
        value: ""
      })
    });

    const messageText = {
      text: messageTexts,
    };
  
    const message = {
      text: messageText,
    };
  
    const intent = {
      displayName: displayName,
      trainingPhrases: trainingPhrases,
      messages: [message],
      parameters:parameterBOT,
     
    };
  
    const createIntentRequest = {
      parent: agentPath,
      intent: intent,
    };
  
    // Create the intent
    try{
      const responses = await intentsClient.createIntent(createIntentRequest);
      console.log(`Intent ${responses[0].name} created`);
    }
    catch (e){
      console.log(e);
    }
    
    // [END dialogflow_create_intent]
  }
```

**What do I do:** I'm splitting training phrases in **trainingPhrase.forEach** function. I'm looking for "ordinary" string pieces and parameter's Intent related. 
When I find a normal piece, I'll set **entityType and alias** as "blank", meanwhile if is a parameter, I'll set it with paramater's entityType and alias.

Same process for parameters, but although I checked the value contained in both arrays (they're set correctly), training phrase pieces are not recognized (indeed in Dialogflow console there's no training phrases) and entity type for parameters created too.

Where is my problem?

**Comment by callmehiphop** [comment]
@nnegrey can you help here?

**Comment by nnegrey** [comment]
One quick clarification question: you create `trainingPhrasesBOT` but never use it. When creating the `const intent =` should that `trainingPhrases` field be set to `trainingPhrasesBOT` rather than `trainingPhrases`?

**Comment by Istorn** [comment]
@nnegrey Hi,

you're right but, although I corrected this little bug (thanks for that), there's a non-linear way to get parameters.

They shouldn't be defined as parameters apart. Once you define trainingPhrases and split them, you set parameters inside trainingphrases theirselves.

`'use strict';

//TODO https://blog.dialogflow.com/post/create-and-manage-entities-with-api/

const admin=require('firebase-admin');


const dialogflow = require('dialogflow');

// Read in credentials from file. To get it, follow instructions here, but
// choose 'API Admin' instead of 'API Client':
// https://dialogflow.com/docs/reference/v2-auth-setup
const credentials = require('./test1drawio.json');

const agentClient = new dialogflow.IntentsClient({
 credentials: credentials,
});

const projectId = 'test-ttlbdt';
const agentPath = agentClient.projectAgentPath(projectId);
var botFile='test2.xml';
const agentXMLCreator=require('./parserGraph');
var agentXML;
agentXML=agentXMLCreator.parseGraph(botFile);


console.log(agentXML);
  //Per ogni intent parsato dal grafico, lo andiamo ad aggiungere al nostro agente
 agentXML.intents.forEach((intent)=>{
  createIntent(projectId,intent.name,intent.id,intent.trainingPhrases,intent.risposte,intent.followUps,intent.parameters)
  .then((response)=>{
      console.log(response);
  });
});











//Funzione per creare l'intent

async function createIntent(
    projectId,
    
    displayName,
    idXML,
    trainingPhrases,
    messageTexts,
    followUps=[],
    parameters=[]
    
  ) {
    // [START dialogflow_create_intent]
    // Imports the Dialogflow library
    const dialogflow = require('dialogflow');
  
    // Instantiates the Intent Client
    const intentsClient = new dialogflow.IntentsClient(
        {credentials: credentials,}
    );
  
    // The path to identify the agent that owns the created intent.
    const agentPath = intentsClient.projectAgentPath(projectId);
  
    const trainingPhrasesBOT = [];
    
    //Prendiamo tutte le trainingPhrases
    trainingPhrases.forEach(trainingPhrase => {
      //Prendiamo tutte le loro parti
      var parts=[];
      trainingPhrase.forEach((piece)=>{
        
        //In questo punto, verifichiamo se il pezzo della frase è un parametro oppure un semplice pezzo di testo
        if (piece.entityType!=undefined){
          //Pezzo che contiene un termine chiave per un dato parametro
          var part = {
            text: piece.text,
            //entityType: piece.entityType.substr(1,piece.entityType.length),
            entityType: "@sys.any",
            alias:piece.entityType.substr(1,piece.entityType.length),
            userDefined: false,
          };
          parts.push(part);
        }
        else{
          //Pezzo di frase normale
          var part = {
            text: piece.text,
            
          };
          parts.push(part);
        }
        
      });
      //A questo punto costruiamo la trainingphrase
      const trainingPhraseFinal = {
        type: 'EXAMPLE',
        parts: parts,
      };
  
      trainingPhrasesBOT.push(trainingPhraseFinal);
      parts=[];
      
  
      
    });
   
    //Parrebbe inutile: se metto le training phrase parametrizzate li elenca già lui i parametri

    /*
    const parameterBOT=[];
    parameters.forEach((parameter)=>{
      //ci prendiamo tutti i suoi attributi
      parameterBOT.push({
        displayName:parameter.name,
        entityType: "@sys.any",
        value: "$"+parameter.name,
        
      })
    });
    */


    
    var messageText={
      text:""
    }
    //Facciamo altrettanto per i messaggi di risposta
    var messagesBuilt=[];
    messageTexts.forEach((message)=>{
        var messageToBuild="";
        message.forEach((piece)=>{
          piece.forEach((realPiece)=>{
            if (realPiece.alias!=undefined){
              //È un parameter
              messageToBuild+="$"+realPiece.alias;
            }else{
              //Pezzo di stringa normale
              messageToBuild+=realPiece.text;
            }
        
          });    
        });
        
        
        
        //Prendiamo la stringa
        //Ne facciamo l'oggetto
          messageText.text= [messageToBuild];
          messagesBuilt.push(messageText);
        
        
        //Puliamo
        messageToBuild="";

    });


   //Verifichiamo se è followup di qualche altro intent oppure bisogna passargli dei followup
  
    followUps.forEach((followUp)=>{
      //Verifichiamo se questa intent in questione è followup o diventa followup di qualcun altro
      if (followUp.father==intent.id){
        //È padre, quindi ha dei suoi followup: ce li peschiamo tutti
        agentXML.getFollowUPSByIntent(intent.id);

      }
      else if (followUp.son==intent.id){
        //È un followup di un altro intent
      }
    });
    
    //Costruiamo l'Intent
    const intent = {
      displayName: displayName,
      trainingPhrases: trainingPhrasesBOT,
      messages: messagesBuilt,
      //parameters:parameterBOT,
     
    };
  
    const createIntentRequest = {
      parent: agentPath,
      intent: intent,
    };
  
    // Create the intent
    try{
      const responses = await intentsClient.createIntent(createIntentRequest);
      console.log(`Intent ${responses[0].name} created`);
    }
    catch (e){
      console.log(e);
    }
    
    // [END dialogflow_create_intent]
  }
  `


By the way, answer (as messages in "intent") won't be recognized at all.

**Comment by nnegrey** [comment]
Parameters shouldn't be part of TrainingPhrases, rather a specific `part` of a training phrase can be associated with a `parameter`

**Comment by Istorn** [comment]
Hi @nnegrey indeed, I didn't probably express sharply myself.

That's the point: as you explained the direct and sane working of is what you mentioned but, testing the code I reported doesn't seem to work as described.

If I try to define parameters apart, then including them as training phrase' part (as we do normally on DIalogflow console, ordinary pattern) it won't work as desired. 

**What does it happen?**
Training phrases are created, parameters too but, once API has been called and everything created, it won't be set the paramter's entity type (e.g. "@sys.any"). Due to this undesired working of, paramters created won't be associated into the wanted training phrase.

Meanwhile, if no paramter won't be set into the intent but, directly into the training phrases as "part" with specified entity, it will!

I thought that it could be kind reporting this strange working of, that's all :)

**Comment by nnegrey** [comment]
I think in:
```
var part = {
            text: piece.text,
            //entityType: piece.entityType.substr(1,piece.entityType.length),
            entityType: "@sys.any",
            alias:piece.entityType.substr(1,piece.entityType.length),
            userDefined: false,
          };
```

You have to set `userDefined` to `true`.

From the docs:
"""
Optional. Indicates whether the text was manually annotated. This field is set to true when the Dialogflow Console is used to manually annotate the part. When creating an annotated part with the API, you must set this to true.
"""
You are manually annotating the part, it is a built in entity type, but the part is still manually annotated.

**Comment by Istorn** [comment]
Ok, now everything is clear.

In my honest opinion it should be explicited into your documentation to avoid this error in the future!

Thanks a lot, we might close the issue :)
