### ISSUE TITLE
Intents: fullfillment with external APIs

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#412]
I'm developing a master thesis and is required using external APIs to provide data to intents.

Actually, I tried to figure out how to set fullfillment and related external APIs calls.

Is it possible do that?

**Comment by nnegrey** [comment]
Dialogflow should be able to hit external APIs for fulfillment, but you have to configure it yourself. 

Docs: https://cloud.google.com/dialogflow/docs/fulfillment-overview

**Comment by callmehiphop** [comment]
Hasn't been much activity here in a bit so I'm going to close this issue. If you think this is a mistake, let us know and we'll be happy to re-open!
