### ISSUE TITLE
Missing method SetAgent

### ISSUE THREAD

**Issue by jdelman** [googleapis/nodejs-dialogflow#413]
#### Steps to reproduce

  1. Try to make a call to `SetAgent`.
  2. Realize that it's not in this library, even though it's specified in the RPC docs: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Agents.SetAgent

I guess I'm a little confused - there is a [link in the README](https://github.com/googleapis/nodejs-dialogflow/blame/master/README.md#L140) called `Dialogflow Node.js Client API Reference`. Clicking it takes you to a [general set of documentation on the RPC interface](https://cloud.google.com/dialogflow/docs/reference/rpc/) to the Dialogflow API, not anything specific to Node.js. The RPC interface to the Dialogflow API lists a method called [SetAgent](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Agents.SetAgent). Unless I'm missing something, there is no way to call `SetAgent` using this library. Am I missing something?

**Comment by jdelman** [comment]
This is addressed by https://github.com/googleapis/nodejs-dialogflow/pull/414 — I'm sure there's a more "official" way to do this programmatically as a lot of this code is boilerplate. The key is pulling in the latest version of `google/cloud/dialogflow/v2/agent.proto`.

**Comment by callmehiphop** [comment]
👋 @jdelman I think this should be fixed in our latest release (v0.11.0), please let us know if that is not the case or if you run into any new issues. Thanks for opening an issue about this!

**Comment by MatthewPorter31** [comment]
Hey there I'm working with googleapis in Node, and I am unable to find the setAgent method in the v2.d.ts file. I'm using the latest version, 59.0.0.
