### ISSUE TITLE
Intent's responses are not recognized

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#416]
I'm using this code to create Intent's responses:

```js
 var messageText={
      text:""
    }
    //Facciamo altrettanto per i messaggi di risposta
    var messagesBuilt=[];
    messageTexts.forEach((message)=>{
        var messageToBuild="";
        message.forEach((piece)=>{
          piece.forEach((realPiece)=>{
            if (realPiece.alias!=undefined){
              //È un parameter
              messageToBuild+="$"+realPiece.alias;
            }else{
              //Pezzo di stringa normale
              messageToBuild+=realPiece.text;
            }
        
          });    
        });
        
        
        
        //Prendiamo la stringa
        //Ne facciamo l'oggetto
          messageText.text= [messageToBuild];
          messagesBuilt.push(messageText);
        
        
        //Puliamo
        messageToBuild="";

    });

```

Then I'll pass it to the intent creator:

```js
const intent = {
      displayName: displayName,
      trainingPhrases: trainingPhrases,
      messages: messagesBuilt,
      parameters:parameterBOT,
     
    };
  
    const createIntentRequest = {
      parent: agentPath,
      intent: intent,
    };
  
    // Create the intent
    try{
      const responses = await intentsClient.createIntent(createIntentRequest);
      console.log(`Intent ${responses[0].name} created`);
    }
    catch (e){
      console.log(e);
    }
    
```

Intent will be created with no problem but no responses will be added.

**Now, In this particular case, there's only one response (set as "messages" in intent object) which consists of "Ciao $nome": a simple string where "$nome" could be an Intent's parameter.**

I said **could** because the parameter' entity won't be recognized (see related issue here: https://github.com/googleapis/nodejs-dialogflow/issues/415) so I thought "Could be the absence of parameter in my Intent?".

The answer is **no** because even if I put a crude string as response, such as like "ciao e benvenuto" the problem still persists.

**Comment by Istorn** [comment]
Is there anyone could help me?!

**Comment by bcoe** [comment]
:wave: hey @Istorn, I'm looping in @nnegrey who knows more about this library than myself.

In some of these cases it sounds like it might be upstream API behavior, and it might be worth also raising an issue here:

https://issuetracker.google.com/savedsearches/5300385

**Comment by nnegrey** [comment]
You might be missing a nested `text` object:

```
messages = [{
   text: {
      text: ['YOUR MESSAGE TEXT']
   }
]}
```

But is the issue with the messages or the parameters?
