### ISSUE TITLE
Definitions over classes attributes are missing

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#424]
Hello,

I'm really appreciating a lot your work, that's why I'm using it for my master degree's thesis.

In my opinion there's a point that should be upgraded.

There are many attributes over classes in your system that have any definition or explaining.

Making a concrete example: I would like to set an Intent's followup.

As follows:

```
`export interface Intent {
  name?: string;

  displayName: string;

  webhookState?: string;

  priority?: number;

  isFallback?: boolean;

  mlEnabled?: boolean;

  inputContextNames?: string[];

  events?: string[];

  trainingPhrases?: TrainingPhrase[];

  action?: string;

  outputContexts?: Context[];

  resetContexts?: boolean;

  parameters?: Parameter[];

  messages?: Message[];

  defaultResponsePlatforms?: string[];

  rootFollowupIntentName?: string;

  parentFollowupIntentName?: string;

  followupIntentInfo?: FollowupIntentInfo[];
}`
```

Let's speak about these attributes:

- **webhookState**: it should be a string. How should it be set?
- **inputContextNames**: are the context's name should be set here as Intent's input?
-  **rootFollowupIntentName,  parentFollowupIntentName,  followupIntentInfo** : how should they be set? What are they referring to? Isn't as so understandable as should...

Is there here anyone could explain them?

**Comment by bcoe** [comment]
@Istorn 👋 it's exciting to have you using dialogflow for your master's, sorry that I haven't been more responsive so far to the issues that you've opened (unfortunately, I'm a generalist, and don't know the ins and outs of dialogflow very deeply).

I'm going to work on getting you in touch with someone from the dialogflow team 👍

**Comment by nnegrey** [comment]
Are you looking for documentation?

WebhookState: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#webhookstate

InputContextNames: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#intent

For the RootFollowupIntentName, ParentFollowupIntentName, and FollowupIntentInfo. Although you can set these up via the API, I might suggest first doing so via the Dialogflow console as it provides a UI to this to better understand how they are all related to each other. 

Then incorporate it into the UI

**Comment by Istorn** [comment]
Hello, @bcoe many thanks for your answer!
Don't worry, I could wait and many thanks for helping me in this work :D 

@nnegrey Many, many thanks. I tried at least 23847239487 times to find them unsuccessfully.
Of course it will be always better to set them through DialogFlow UI but my thesis consists of providing a mine UI which uses your NodeJS system :)

**Comment by bcoe** [comment]
👍 @Istorn sounds like we can close this issue; the reference docs @nnegrey provided unblocked you?

**Comment by nnegrey** [comment]
Yep! (Sorry the docs are hard to find, I know how you feel)

Oh yea, for sure, I'm a visual learner, so when I see the UI, it helps me get a better understanding of how the API works. But totally understand building your own UI.
