### ISSUE TITLE
Is "queryParams.session" a misprint in samples/detect.js?

### ISSUE THREAD

**Issue by gsommavilla** [googleapis/nodejs-dialogflow#426]
# Is "queryParams.session" a misprint in samples/detect.js?

In the "Streaming detect intent" sample code at https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js there is a definition that I don't understand:

```
async function streamingDetectIntent(...)
...
const sessionPath = sessionClient.sessionPath(projectId, sessionId);

const initialStreamRequest = {
  session: sessionPath,
  queryParams: {
    session: sessionClient.sessionPath(projectId, sessionId),
  },
  ...
```

The "session" key inside "queryParams" looks like an exact copy of the "session" key above (the brother of "queryParams").

Also the fact that its value is computed again (without reusing sessionPath) is strange.

Finally, I have tested the code with "session" but without "queryParams.session" and it works, while if I comment also "session" I receive an error from dialogflow (`Error: 3 INVALID_ARGUMENT: Resource name '' does not match 'projects/*/locations/*/agent/environments/*/users/*/sessions/*'.`), which is understandable, since I am not passing any session string to the server.

So, my question is: is "queryParams.session" really needed? Or is it a misprint?

**Comment by callmehiphop** [comment]
Looking over the proto files, it looks like `session` is not a valid option for query params, so I'm going to go ahead and say it is a mistake. Thanks for bringing this to our attention!
