### ISSUE TITLE
Service continuity during agent update

### ISSUE THREAD

**Issue by kostaskat** [googleapis/nodejs-dialogflow#428]
For the purpose of service design, can you please comment on the below issue:

**When updating an agent (via calling the importAgent or restoreAgent and then the trainAgent/setAgent), how does Dialogflow treat on-going sessions**, i.e. _sessions that were either existing before triggering the agent update or sessions that were initiated before the agent update completed_?

Are on-going sessions routed to the agent instance version that was in place before the update, i.e. is that agent instance transition wrt sessions handled internally by Dialogflow? Or are consuming services (using the nodejs client library) responsible for treating this situation?

I was unable to find best practices on all the above in the Documentation, but please point me to any if I have missed it.

Thanks

**Comment by callmehiphop** [comment]
👋 @kostaskat I'm not sure how often the Dialogflow team looks through issues here, but you'll probably have better luck getting this answered over in the [product tracker](https://cloud.google.com/support/docs/issue-trackers). If you get an answer, please feel free to come back and link it! Thanks! And sorry I couldn't be of more help here ☹️
