### ISSUE TITLE
Memory Usage Increasing without Limit

### ISSUE THREAD

**Issue by charlesj** [googleapis/nodejs-dialogflow#429]
#### Environment details

  - OS: Linux
  - Node.js version: 10.16.3
  - npm version: 6.9.0
  - `dialogflow` version: 0.11.0

#### Steps to reproduce

  1. Upgrade to version 0.11.0 from version 0.8.2
  2. Allow service to run, making calls to `detectIntent`
  3. Obverse memory usage stair-stepping up over time.

Reproducable code:

```
import dialogFlow from 'dialogflow'

export async function runHarness() {

  let memoryUsage = 0
  const settings = { snipped: true }

  for(let i=0; i<1000; i++) {
    const sessionsClient = new dialogFlow.SessionsClient(settings)
    const sessionPath = sessionsClient.sessionPath(settings.projectId, 'testing-13')

    const request = {
      session: sessionPath,
      queryInput: {
        text: {
          text: 'hi',
          languageCode: 'en-US',
        },
      },
    }
    await sessionsClient.detectIntent(request)
    const { heapTotal } = process.memoryUsage()
    console.log(heapTotal, heapTotal - memoryUsage)
    memoryUsage = heapTotal
  }
}
```

Running this code against version 0.8.2 and observing the memory usage, it fluctuates, but stays right around the starting memory usage.  Running this against 0.11.0 shows memory usage growing steadily over time and never decreasing.

**Comment by nnegrey** [comment]
Just a quick look. 
You're creating a bunch of new clients, but never closing them might be the issue. 
If you're finished with a client it should always be closed.

**Comment by charlesj** [comment]
How is one supposed to close a client?

Looking through the [documentation](https://github.com/googleapis/nodejs-dialogflow) doesn't show anything.  The sample code for detecting an intent is available on that page, and it's almost exactly like mine.  It does not show anything related to closing the clients. 

I did the naive thing and tried to call `close` on the client.  It does not have such a method.  Please advise.

**Comment by callmehiphop** [comment]
@charlesj unfortunately I don't think the close method is exposed at this time. I would suggest creating a single client outside of your loop and re-using it.

**Comment by bcoe** [comment]
@charlesj does creating the client outside of the loop do the trick for you, this is the approach we tend to recommend to folks (instantiate the client once, and use it multiple times).

**Comment by charlesj** [comment]
Yes, we can make this work.  We work with many different projects, but I think plugging in a cache keyed to the project id will handle it.  In the past, on `.8.*` it did not matter, so when memory usage went crazy after upgrading to `.11.*+`, it stood out as problematic.

The state that is causing the memory to increase is completely hidden from our view, and at it's core it looks like it should just be handled by the the GC.  Obviously there is something underneath the hood that is preventing that.  The re-use of clients is something that is common in other libraries, but there is no indication that this is needed in this project, in the documentation or the example code.

**Comment by bcoe** [comment]
@callmehiphop do you think this memory issue might also be related to us not caching HTTP agents? or unrelated.

**Comment by callmehiphop** [comment]
@bcoe unrelated, afaik we don't use teeny-request in any of the grpc clients.

**Comment by callmehiphop** [comment]
I'm going to close this out since the suggested workaround seemed to do the trick.
