### ISSUE TITLE
Intent creation with multiple training phrases having same parameter, creates the mentioned parameter as list

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#444]
I'm creating an intent with two different training phrases containing the same parameter.

As follows:

```
TrainingPhrases=[
  {
     parts: [
        {
          text: "ciao mi chiamo"
        },
        {
          alias:"nome"
          entityType:"@sys.any"
          isList:false
          text:"Marco"
          userDefined:true
        }]
  },
  {
     parts:[
        {
           text: "Buongiorno sono"
        },
        {
           alias:"nome"
           entityType:"@sys.any"
           isList:false
           text:"Silvia"
           userDefined:true
        }
     ]
   }
]
```

Besides uncorrect JSON notation that might be here, as you can see "Silvia" and "Marco" are always referring to the same parameter that's "nome".

Once I load everything, the parameter is created as a list:

![Schermata 2019-10-04 alle 17 17 51](https://user-images.githubusercontent.com/10259557/66219617-ccc93a00-e6cb-11e9-9e5c-23f79f08ee93.png)

Why?

**Comment by nnegrey** [comment]
A `Part` doesn't know about `isList`
https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Intent.TrainingPhrase.Part

Only the Parameter does. 
When you create the parameter, you should mark `isList: false` then.
https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#parameter
