### ISSUE TITLE
Output and Input Context for Intents: setting them once they're created is not working

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#445]
After have read documentation, I've understood that we must create an intent before setting its output and input context through API.

And that is what I did.

I created this async function, invoke in the intent creation's callback, to be totally sure the intent exists in the agent.

Indeed, the parameter of this function is the intent itself returned from Google with its all attributes, I can see that to the debugger:

```js
async function updateIntent(intentTU) {
  const dialogflow = require('dialogflow');

  // Instantiates the Intent Client
  const intentsClientup = new dialogflow.IntentsClient({credentials});

  // The path to identify the agent that owns the created intent.
  const agentPath = intentsClientup.projectAgentPath(projectId);

  //Arrivati a questo punto della callback, Aggiungiamo input e outputcontext per ogni Intent
  intentTU.outputContexts.push({
    name: intentTU.displayName,
    lifespanCount: 10
  });

  const updateIntentRequest = {
    parent: agentPath,
    intent: intentTU
  };

  // Create the intent
  try {
    const responses = await intentsClientup.updateIntent(updateIntentRequest);
    console.log(`${responses[0].name} updated`);
    return responses;
  } catch (e) {
    console.log(e);
    return e;
  }
}

```

My objective, is to add an output context to the desired intent having the same name of the intent itself.

In addition: the agent path is correct, I use the same data to create intents.

By the way, once I try to invoke the **updateIntent** with correctly created **updateIntentRequest**, I receive back this error:

> Error: Name 'benvenuto' does not match patterns 'projects/{projectId=*}/agent/environments/{environmentId=*}/users/{userId=*}/sessions/{sessionId=*}/contexts/{contextId=*}

Where am I wrong?

**Comment by nnegrey** [comment]
You're using the intent's displayname as the name of the `output_context`

A `Context` object has a specially formatted name, as shown in the error. 
https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Context

You'll have to also create a context and use it's `name` field.

**Comment by mlinvilleengler** [comment]
it seems counter-intuitive that the name of the context is a full path. I would imagine that name would be the context display name. is the context id the context display name? if not where do we get the context id? Some additional docs on how to add context to calls with the node dialogflow client would be awesome!

**Comment by nnegrey** [comment]
The `name` field for Dialogflow is typically always the full path. 

While if the object has a `display_name` field (like an intent object does) then it would just be the display_name. 

The `context_id` is something you create. (similar to a `session_id`)

From the [docs](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Context):
"""
The Context ID is always converted to lowercase, may only contain characters in [a-zA-Z0-9_-%] and may be at most 250 bytes long.
"""
