### ISSUE TITLE
[BUG] Dialogflow Session Client fails to initialize since Version 0.11.0

### ISSUE THREAD

**Issue by akirilyuk** [googleapis/nodejs-dialogflow#449]
#### Environment details

  - OS: Mac OS 10.14.6
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `dialogflow` version: since 0.11.0, currently 0.12.0

#### Minimal code to reproduce

```js
const { SessionsClient } = require('dialogflow');

describe('test SessionClient creation', () => {
  it('should create a new SessionClient instance', done => {
    try {
      const dfClient = new SessionsClient({});
      done();
    } catch (err) {
      done(err);
    }
  });
});
```

```js
const dialogflow = require('dialogflow');

describe('test SessionClient creation', () => {
  it('should create a new SessionClient instance', done => {
    try {
      const dfClient = new dialogflow.SessionsClient({});
      done();
    } catch (err) {
      done(err);
    }
  });
});
```

These tests fail with the following error:

> TypeError: Cannot read property 'length' of undefined
> 
>     at Root.load (/Users/akirilyuk/***/node_modules/protobufjs/src/root.js:192:44)
>     at Root.loadSync (/Users/akirilyuk/***/node_modules/protobufjs/src/root.js:235:17)
>     at Object.loadSync (/Users/akirilyuk/***/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
>     at GrpcClient.loadFromProto (/Users/akirilyuk/***node_modules/google-gax/src/grpc.ts:162:40)
>     at GrpcClient.loadProto (/Users/akirilyuk/***/node_modules/google-gax/src/grpc.ts:190:17)
>     at new SessionsClient (/Users/akirilyuk/***/node_modules/dialogflow/src/v2/sessions_client.js:123:28)
>     at Object.done (/Users/akirilyuk/***/test/unit/vendors/dialogflow.test.js:6:24)
>     at resolve (/Users/akirilyuk/***/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
>     at new Promise (<anonymous>)
>     at mapper (/Users/akirilyuk/***/node_modules/jest-jasmine2/build/queueRunner.js:26:19)

Same setup with dialogflow 0.10.3 works without any problem.

**Comment by bcoe** [comment]
@akirilyuk try:

```
rm package-lock.json
rm -r ./node_modules
npm i
```

**Comment by akirilyuk** [comment]
@bcoe  @callmehiphop thx, issue resolved after I cleaned and fresh installed all dependencies

**Comment by bcoe** [comment]
@akirilyuk awesome :tada: let us know if you bump into any more problems in the future.
