### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-dialogflow#467]
Package name: `dialogflow`
Current release: **beta**
Proposed release: **GA**

## Instructions

Check the lists below, adding tests / documentation as required. Once all the "required" boxes are ticked, please create a release and close this issue.

## Required

- [x] 28 days elapsed since last beta release with new API surface
- [x] Server API is GA
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

## Optional

- [x] Most common / important scenarios have descriptive samples
- [x] Public manual methods have at least one usage sample each (excluding overloads)
- [x] Per-API README includes a full description of the API
- [x] Per-API README contains at least one “getting started” sample using the most common API scenario
- [ ] Manual code has been reviewed by API producer
- [ ] Manual code has been reviewed by a DPE responsible for samples
- [ ] 'Client LIbraries' page is added to the product documentation in 'APIs & Reference' section of the product's documentation on Cloud Site

**Comment by JustinBeckwith** [comment]
So we merged the PR bumping this thing to GA - wooo! It got me thinking.  As of today this is our only cloud / gapic generated client that isn't in the `@google-cloud` scope on npm.  Should we consider renaming it?  I think the steps would be:
- push one more version to `npm` under the `dialogflow` name with a deprecation warning, telling users to install `@google-cloud/dialogflow`.  
- Rename the module, bump the version to 1.0, and then publish under the new scope as GA. 

Thoughts on a.) if we should do this and b.) if we should do it now?

**Comment by nnegrey** [comment]
If we do this, we should do it in Python too. 

I vote yes, but this will likely make people upset, as we 2 years ago moved this from the Dialogflow org to the GoogleApis org. Depends on how much breaking we want to keep causing.

**Comment by JustinBeckwith** [comment]
The move between GitHub organizations shouldn't have created a breaking change for users though, right?  At the end of the day, this is making a one line change in your package manifest.
