### ISSUE TITLE
[Analytics] How can I get data from "Analytics" area?

### ISSUE THREAD

**Issue by tiagoPacheco** [googleapis/nodejs-dialogflow#472]
Hi, 

I'm using the Dialogflow API to manage my bot. At moment, I need to get the the data from "Analytics" area (image below) via API. Has some way that I could do this?

![Screenshot from 2019-11-19 16-51-22](https://user-images.githubusercontent.com/5752720/69180904-dfb59380-0aec-11ea-8bf7-0fee6822bf33.png)

I've search a lot how to do this using this lib, but I didn't find nothing.

Has anyone can help me with this?

**Comment by arthur-es** [comment]
I'm also intered in this Issue. I really need to get the number of sessions so I can inform my clients.

**Comment by b-loved-dreamer** [comment]
Hi  @tiagoPacheco — this [information](https://cloud.google.com/dialogflow/es/docs/analytics#:~:text=The%20Dialogflow%20Console%20provides%20an,used%20to%20improve%20your%20agent.&text=For%20most%20views%2C%20only%20successful,the%20V2%20API%20are%20included.) about the ```dialogflow``` analytics page includes references to other service, ```tag_consumed_api``` [that might be helpful in your case](https://cloud.google.com/monitoring/api/resources#tag_consumed_api). 

This issue has been open for a while. I am going to close for now, but feel free to reopen if needed.
