### ISSUE TITLE
How to use custom payload in dialogflow to create quick replies on web integration

### ISSUE THREAD

**Issue by praveenptl71** [googleapis/nodejs-dialogflow#476]
How to use custom payload in dialogflow to create quick replies on web integration

**Comment by amammay** [comment]
@praveenptl71 if you are looking at making a quick webhook fulfillment then using the https://github.com/dialogflow/dialogflow-fulfillment-nodejs lib should be a step in the right direction for simple use cases. If you are expecting support for more complex operations of dialogflow then you will likely have to leverage the api's. Fulfillment support with other languages is less than optimal with dialogflow in its current state.

**Comment by vishald123** [comment]
@praveenptl71, You can refer to this [link](https://www.youtube.com/watch?v=ueVX-p05378) to get a basic idea.

**Comment by b-loved-dreamer** [comment]
Closing this issue. May no longer be relevant.
