### ISSUE TITLE
BUG: BatchUpdatingIntents to enable all webhooks using updateMask

### ISSUE THREAD

**Issue by TomHartogs** [googleapis/nodejs-dialogflow#484]
OS: Windows 10
Node: v10.16.3
Npm: v6.11.3
Dialogflow: v2

I am trying to batchUpdate all intents in order to enable the webhook for them. 
  1. Get a list of all intents: `intentsClient.listIntents({parent: projectAgentPath});`
  2. For each intent set webhookState to 1 (enable)
  3. Create request with `updateMask: { paths: ['webhookState'] }`

Removing the updateMask successfully updates the webhookState but also overrides all other fields (to zero) as expected. However, when applying the updateMask the webhookState does not get updated at all. Is this a bug or am I missing something?

If you require any extra information feel free to ask. I have added a code snippet below that shows how I use the library.
```
const foundIntents = getIntents(projectId);

let intents: any[] = [];

foundIntents.forEach((intent) => {
    intents.push({
        name: intent.name,
        displayName: intent.displayName,
        webhookState: 1,
    });
});

const request = {
    parent: projectAgentPath,
    intentBatchInline: {
        intents: intents,
    },
    updateMask: {
        paths: ['webhookState']
    },
};
await intentsClient.batchUpdateIntents(request)
```

**Comment by TomHartogs** [comment]
@bcoe Is there any update on this? The updateMask still does not seem to work correctly (also tested using `client.updateIntent(request);`).
I am successfully able to update the intents using the rest API via the googleapis module, but would prefer to use this library to do so.

**Comment by bcoe** [comment]
@nnegrey don't suppose you have any feedback, as you know this API better than me.

@TomHartogs reading the proto definitions, it looks like potentially your query should be:

```js
    updateMask: {
        paths: "webhookState"
    },
```

I believe the `FieldMask` type expects a [string path](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf?&_ga=2.115067783.1265306868.1583363821-578940058.1581473159&_gac=1.191990488.1583199991.CjwKCAiA-vLyBRBWEiwAzOkGVJ6W4YMD56TIkZh0qi1EuTFEYUk3BMyy77APu2q8GLwVaol8DDLPAxoCyDoQAvD_BwE#fieldmask).

**Comment by TomHartogs** [comment]
@bcoe When using the rest API the FieldMask property in the request body indeed expects a string. However, in this library an array is expected or else the following error is thrown: `TypeError: .google.protobuf.FieldMask.paths: array expected`.
Perhaps that's where things go wrong, during conversion of the FieldMask from this library to the underlying API.

**Comment by bcoe** [comment]
@TomHartogs can you make TypeScript ignore that line, and see if things start working? If so it's a bug with our types which I can log with the upstream team :ok_hand:

**Comment by nnegrey** [comment]
Wouldn't the paths field be `webhook_state` because of underlying RPC rather than Node.js naming conventions?

I think I was able to get that to work, but I'm less of a Node.js expert.

**Comment by TomHartogs** [comment]
@nnegrey you are correct, the mask indeed is supposed to be `webhook_state`. The documentation states `updateMask: The mask to control which fields get updated`, this led me to think I should pass in the symbolic path as described in the object passed in the function.
I wasn't aware of the naming convention for the RPC calls (relatively new to GCP), thanks for the clarification! Also thank you @bcoe, it does not seem to be a bug, nevertheless thank you for thinking along!
