### ISSUE TITLE
Custom payload message format changed in fulfillment message response

### ISSUE THREAD

**Issue by GT-ThomasTan** [googleapis/nodejs-dialogflow#486]
#### Environment details

  - OS: macOS 10.15.1
  - Node.js version: v12.13.1
  - npm version: 6.12.1
  - `dialogflow` version: 1.0.0

#### Steps to reproduce

  1. On dialogflow console, add a custom payload message for default platform, payload:
`{
  "card": {
    "subtitle": "Hi! I'm Jamie, your personal virtual assistant. How can I help you today?",
    "buttons": [
      {
        "text": "I want to file my tax",
        "postback": "I want to file my tax"
      }
    ]
  }
}
`
  2. Call detectIntent API using client library
  3. Expected fulfillment message:
`{
  "payload": {
    "card": {
      "buttons": [
        {
          "text": "I want to file my tax",
          "postback": "I want to file my tax"
        }
      ],
      "subtitle": "Hi! I'm Jamie, your personal virtual assistant. How can I help you today?"
    }
  }
}`
  4. Actual response:
`{
  "payload": {
    "fields": {
      "card": {
        "structValue": {
          "fields": {
            "subtitle": {
              "stringValue": "Hi! I'm Jamie, your personal virtual assistant. How can I help you today?",
              "kind": "stringValue"
            },
            "buttons": {
              "listValue": {
                "values": [
                  {
                    "structValue": {
                      "fields": {
                        "text": {
                          "stringValue": "I want to file my tax",
                          "kind": "stringValue"
                        },
                        "postback": {
                          "stringValue": "I want to file my tax",
                          "kind": "stringValue"
                        }
                      }
                    },
                    "kind": "structValue"
                  }
                ]
              },
              "kind": "listValue"
            }
          }
        },
        "kind": "structValue"
      }
    }
  },
  "platform": "PLATFORM_UNSPECIFIED",
  "message": "payload"
}`

Just want to know if this behaviour is intended.

Thanks a lot.

**Comment by callmehiphop** [comment]
@GT-ThomasTan dialogflow likes to make use of [protobuf Structs](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct) from time to time, I think that is what you're seeing.

There's a module floating around called [pb-util](https://www.npmjs.com/package/pb-util) that you can use to convert the struct into a normal JSON structure if that is something you're interested in.

**Comment by GT-ThomasTan** [comment]
@callmehiphop I see, so this is intended behaviour. Noted, thanks a lot.
