### ISSUE TITLE
Question: specifying an environment in detectIntent API call

### ISSUE THREAD

**Issue by GT-ThomasTan** [googleapis/nodejs-dialogflow#487]
I am currently using the environment beta feature, I am wondering if there is currently a way to specify an environment while making detectIntent call.

Thanks.

**Comment by amammay** [comment]
https://github.com/googleapis/nodejs-dialogflow/blob/master/src/v2beta1/sessions_client.js#L382

**Comment by GT-ThomasTan** [comment]
Thanks a lot @amammay
