### ISSUE TITLE
Missing endInteraction intent attribute

### ISSUE THREAD

**Issue by yoshigev** [googleapis/nodejs-dialogflow#496]
- OS: Windows 7
  - Node.js version: 10.16.0
  - npm version: 6.13.0
  - `dialogflow` version: 1.0.0

#### Steps to reproduce

  1. Add an intent that should disconnect the conversation by marking the checkbox "Set this intent as end of conversation" in the UI.
  2. Send a text from the client that triggers this intent.

#### Expected result
Having an `endInteraction` attribute with `true` value in queryResult.intent attribute.

#### Actual result
When working with v2beta1, the `endInteraction` attribute exists.
When working with v2 (the default), the attribute is missing.
Instead, there is a "diagnosticInfo" field indicating `end_conversation`, but according to documentation it should only be used for debugging.

The received response:
```
[
  {
    "responseId": "xxx",
    "queryResult": {
      "fulfillmentMessages": [
        {
          "platform": "PLATFORM_UNSPECIFIED",
          "text": {
            "text": [
              "disconnect the call"
            ]
          },
          "message": "text"
        }
      ],
      "outputContexts": [
        {
          "name": "projects/xxx/contexts/__system_counters__",
          "lifespanCount": 1,
          "parameters": {
            "fields": {
              "no-input": {
                "numberValue": 0,
                "kind": "numberValue"
              },
              "no-match": {
                "numberValue": 0,
                "kind": "numberValue"
              }
            }
          }
        }
      ],
      "queryText": "disconnect",
      "speechRecognitionConfidence": 0,
      "action": "",
      "parameters": {
        "fields": {}
      },
      "allRequiredParamsPresent": true,
      "fulfillmentText": "disconnect the call",
      "webhookSource": "",
      "webhookPayload": null,
      "intent": {
        "inputContextNames": [],
        "events": [],
        "trainingPhrases": [],
        "outputContexts": [],
        "parameters": [],
        "messages": [],
        "defaultResponsePlatforms": [],
        "followupIntentInfo": [],
        "name": "projects/xxx",
        "displayName": "disconnect",
        "priority": 0,
        "isFallback": false,
        "webhookState": "WEBHOOK_STATE_UNSPECIFIED",
        "action": "",
        "resetContexts": false,
        "rootFollowupIntentName": "",
        "parentFollowupIntentName": "",
        "mlDisabled": false
      },
      "intentDetectionConfidence": 1,
      "diagnosticInfo": {
        "fields": {
          "end_conversation": {
            "boolValue": true,
            "kind": "boolValue"
          }
        }
      },
      "languageCode": "en",
      "sentimentAnalysisResult": null
    },
    "webhookStatus": null
  },
  null,
  null
]
```

Is there an alternative way to get the `endInteraction` indication?

Thanks,
Yehoshua

**Comment by b-loved-dreamer** [comment]
Hi @yoshigev, the ```endInteraction``` field is not guaranteed to be included in the intent object. Please, take a look at [this](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2beta1/DetectIntentResponse).

> object (Intent)The intent that matched the conversational query. Some, not all fields are filled in this message, including but not limited to: name, displayName, endInteraction and isFallback.

Closing this issue. Please, reopen if needed.
