### ISSUE TITLE
StreamingDetectIntent: dialogflow stop listening after long silence

### ISSUE THREAD

**Issue by bivas6** [googleapis/nodejs-dialogflow#507]
#### Environment details

  - OS: Win32
  - Node.js version: v12.9.1
  - npm version: 6.10.2
  - `dialogflow` version: 1.0.0

#### Steps to reproduce

  1. create dialog flow streaming detect intent client, and remain silence about ~10 sec.
  2. start speaking
  3. see that no error event or 'transcript' response arrived.

Thanks!

**Comment by bivas6** [comment]
I'm wrong, you got 2 empty messages, one with reconitionResult type = 'END_OF_SINGLE_UTTERANCE', and the second with query result with empty/ null properties. 

thanks!

**Comment by bivas6** [comment]
OK, so you did receive this 2 messages only if you stop writing to the detect stream (unpipe etc), but if not you only get the first message, which is the same message like after good recognition.
Can you please add an error event that imply that no voice has detected so far? Or some other indication..
Thanks!

**Comment by munkhuushmgl** [comment]
@bivas6 I will add some indication if the user does not attempt to provide any voice.

**Comment by munkhuushmgl** [comment]
@bivas6 I was able reproduce your bug on nodejs and java. I am working on filing a bug against dialogflow.
I will keep you updated once I get response back from them.

**Comment by bivas6** [comment]
@munkhuushmgl Why did you close it?

**Comment by bivas6** [comment]
cc: @orgads @yoshigev

**Comment by munkhuushmgl** [comment]
It won't fix (status)

**Comment by orgads** [comment]
Why? Can you elaborate?

**Comment by munkhuushmgl** [comment]
@orgads I think it is not service or API related issue, and I would suggest set up some kind of retry logic for your specific files that has a long silence. However, i will contact internal team about this issue.

**Comment by telpirion** [comment]
Hi @orgads , are you using the `single_utterance` flag in your [`InputAudioConfig`](https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3beta1#inputaudioconfig)?

**Comment by telpirion** [comment]
I'm going to close this issue for now. Please re-open it if you're still having issues. Thank you!

**Comment by orgads** [comment]
Sorry, I forgot to reply. We use both modes of single_utterance, IIRC it depends on the language. @bivas6 can you elaborate? Do you remember on which mode we had this issue? Is it still happening?

**Comment by orgads** [comment]
cc @yoshigev

**Comment by bivas6** [comment]
We are mostly using single_utterance = true, and yes it is still happening

**Comment by orgads** [comment]
@telpirion I can't reopen. Can you please do it?
