### ISSUE TITLE
Empty fulfillmentMessages/fulfillmentText in detectIntent response

### ISSUE THREAD

**Issue by daaru00** [googleapis/nodejs-dialogflow#517]
Hello,

In v1 version I using:
```js
const response = await axios.post('https://api.dialogflow.com/v1/query?v=20150910', {
  contexts: [
    'private'
  ],
  lang: event.Language,
  query: 'my message string',
  sessionId: sessionId,
  timezone: event.Timezone
}, {
  headers: {
    'Authorization': 'Bearer ' + event.ClientAccessToken
  }
})
```
and in response I receive the response message:
```
const result = response.data.result || {}
const speech = result.fulfillment.speech // contain my response string "Lancio un flush della cache in stage"
```
now in v2 I using this:
```js
const [response] = await sessionClient.detectIntent({
  session: event.SessionPath, // session path create before
  queryInput: {
    text: {
      text: 'my message string',
      languageCode: event.Language
    }
  },
  queryParams: {
    contexts: event.ContextsObjects || [], // contain "private" context id
    timeZone: event.Timezone
  }
})
```
in response object I receive an empty response:
```json
{
   "fulfillmentMessages":[{"platform":"PLATFORM_UNSPECIFIED","text":{"text":[""]},"message":"text"}]
}
```
and I'm at the end of conversation (as `diagnosticInfo` report)
```json
{
  "diagnosticInfo":{"fields":{"end_conversation":{"boolValue":true,"kind":"boolValue"}}}
}
```
is something related to "PLATFORM_UNSPECIFIED" message? I need to set some option to tell Dialogflow to respond me in "text format"?

I would like to receive the "Response" set in Dialogflow console, I am doing something wrong or there is and error parsing API response (that empty text string)
![dialogflow console response](https://user-images.githubusercontent.com/8782994/73563654-30872800-445e-11ea-85bf-047a69c6fc98.png)

Additional infos
- Intent name is correctly detect (`intent.displayName` contain my intent name)
- `allRequiredParamsPresent` is `true`
- `fulfillmentText` is also an empty string `""`
- NodeJS version is `v10.18.1`
- OS is `Ubuntu 18.04 LTS`

-----------

It happens only when I'm at the end of conversation, when some parameters is missing I correctly see a text response:
```json
{
  "fulfillmentMessages":[{"platform":"PLATFORM_UNSPECIFIED","text":{"text":["Per quale ambiente?"]},"message":"text"}]
}
```

**Comment by daaru00** [comment]
Can someone help me? I'm really stuck on this..

**Comment by vishald123** [comment]
Hi @daaru00, are you using a webhook?

**Comment by daaru00** [comment]
Hi @vishald123,

nope, no webhooks are configured. Just changed the SDK version but leave action's configurations untouched

**Comment by vishald123** [comment]
> Hi @vishald123,
> 
> nope, no webhooks are configured. Just changed the SDK version but leave action's configurations untouched

Could you provide your actions configuration?

**Comment by vishald123** [comment]
Hey @daaru00, You can refer to DialogFlow's [Migration Guide](https://cloud.google.com/dialogflow/docs/migrating) and see what are you missing. If you still face the issue, please feel free to comment and also if you could please provide complete gist of your code.

**Comment by nollymar** [comment]
I have a similar issue using a webhook. On my webhook I set a fulfillment message which I see in the Dialogflow console (Diagnostic Info -> Fulfillment Response). However, if I look at the Raw API Response tab, the fulfillmentMessages field is empty and the detectIntent returns an empty message as well.

I am using version 2 and this is how I send the webhook response: 
```
WebhookResponse.newBuilder()
                .addFulfillmentMessages(
                        Intent.Message.newBuilder()
                                .setText(Intent.Message.Text.newBuilder().addText(intentResponse)
                                        .build()).setPlatform(Intent.Message.Platform.PLATFORM_UNSPECIFIED))
                .addOutputContexts(Context.newBuilder()
                        .setName(webhookRequest.getSession())
                        .setLifespanCount(5).build())
                .build();
```

**Comment by b-loved-dreamer** [comment]
For reference, this is the [docs](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/DetectIntentResponse) for the ```DetectIntentResponse```. All samples related to intent detection [here](https://cloud.google.com/dialogflow/es/docs/how). I am closing this issue. Please,  reopen if needed.
