### ISSUE TITLE
dialogflow.SessionsClient.detectIntent returns array of nulls during random requests

### ISSUE THREAD

**Issue by Xeelley** [googleapis/nodejs-dialogflow#522]
**Environment details:**
Node: v12.4.0  
NPM packages: dialogflow v0.11.0 + @types/dialogflow v0.9.4  
Dialogflow API: v2

**Short description**
Some (random) `detectIntent` method calls returns array of 3 null values without errors.
In some cases its happen during series of requests with same body (like 4 of 5 request works fine, and 1 with issue) and with like 2-3 sec interval between requests.
In 'History' tab in Dialogflow panel I can see that all requests were received by Dialoflow and intent was successfully detected each time. 

**Code**
Here my class which send requests to Dialogflow API (Typescript environment):
```
import dialogflow from 'dialogflow';
import {v4} from "uuid";

export class Dialogflow {
    private readonly projectId: string;
    private readonly redis: RedisClient;
    private readonly sessionClient: dialogflow.SessionsClient;

    constructor(projectId: string, config: {
        privateKey: string,
        clientEmail: string
    }) {
        this.projectId = projectId;
        this.redis = new RedisClient();
        this.sessionClient = new dialogflow.SessionsClient({
            credentials: {
                private_key: config.privateKey,
                client_email: config.clientEmail
            }
        });
    }

    public async sendMessage(message: Message) {
        const sessionPath = await this.getSession(message); // SessionClient.sessionPath string
        const request =  {
            session: sessionPath,
            queryInput: {
                text: {
                    text: message.text,
                    languageCode: message.languageCode.toLowerCase()  === 'ru' ? 'ru-RU' : 'en-US'
                }
            }
        }

        try {
            const [response] = await this.sessionClient.detectIntent(request);
            // In some random requests response is null (like any other array args)
        } catch (e) {
            // error not happen
        }
    }

    private async getSession(message: Message) {
        const sessionKey = message.chatId + message.source;
        const sessionPath = await this.redis.get(sessionKey);
        if (sessionPath) {
            return sessionPath;
        } else {
            const newSessionId = v4();
            const newSessionPath = this.sessionClient.sessionPath(this.projectId, newSessionId);
            await this.redis.set(sessionKey, newSessionPath);
            return newSessionPath;
        }
    }
```

**P.S.**
I spent like 4 hours to debug but nothing found. No way to predict which request will returns null-array.

**Comment by bcoe** [comment]
thanks for the bug report @Xeelley. This sounds like it's potentially an issue with the upstream API, it might also be worth opening an issue here:

https://issuetracker.google.com/savedsearches/5300385

**Comment by fahimmahmoodmir** [comment]
any Update? because I also faced the same error

**Comment by b-loved-dreamer** [comment]
It looks like this issue may no longer be relevant. Feel free to re-open.

**Comment by nvtuan305** [comment]
I got same issue. Don't know why? Sometime, Dialogflow return array of nulls `[ null, undefined, undefined ]`

**Comment by Xeelley** [comment]
@nvtuan305 it was a plenty of time ago, but if I remember correclty I found that this issue refered to Node.js HTTP/2 protocol handling (not sure because of ustream API or Node.js agent). I didn't found any correlations between request body / duration / whatever and probability of error. Also only one real way to reproduce this issue is just consistently call `detectIntect` with same request body as many times as it needed.
It was a sticky point for me and team for a couple of weeks. We never found stable soltion using [dialoflow](https://www.npmjs.com/package/dialogflow) module, so our solution was rewrite all app<>dialogflow interactions to own [REST API v2](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2-overview) requests via [axios](https://www.npmjs.com/package/axios) and app still work's fine.
Coworker talks me error still happen on:
- Node.js v12.13.0
- `dialogflow` package v1.2.0

@bcoe any chance this issue referer to HTTP/2?
