### ISSUE TITLE
Dynamic list with one result

### ISSUE THREAD

**Issue by onigetoc** [googleapis/nodejs-dialogflow#529]
i have a list created from a api from a external file.
When i get only one result the app stop. I know that a list should have a minimum of 2 results but my suggestion is to allow one item in the list. I created a exception to show a basic card but i need the click or choice from user to trigger a audio file.
My suggestion, allow one result in List.

**Comment by bcoe** [comment]
@onigetoc :wave: if this is a feature request for the dialogflow product itself, vs., the client library, I suggest opening an issue [here](https://issuetracker.google.com/savedsearches/5300385). This will provide feedback directly to the product team.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We followed up with a suggestion to file a feature request [here](https://b.corp.google.com/savedsearches/5300385) a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue if needed.
