### ISSUE TITLE
Do not play mp3 download.

### ISSUE THREAD

**Issue by onigetoc** [googleapis/nodejs-dialogflow#530]
i'm creating a dialogflow (skill) and play mp3 from the internet. But when the mp3 come from external url and are in (download mode) it can't be play.
For exemple, a downloadable mp3 will play on a mp3 html player on chrome browser or any browser.
but it won't play in the dialogflow mp3 player.

mp3 who play directly in the browser from a link will play. except those in (download mode) (i don't know how to call it)

Exemple: this link will send you to a downloadable mp3
[Downloadable mp3](https://podcasts.captivate.fm/media/ada8bb2e-6106-4d58-bfdd-1d3b5851ec54/interview-with-dr.mp3)

this one will play in the browser.
[Normal mp3](http://traffic.libsyn.com/joeroganexp/p1423.mp3)

Both will play in a html5 player on a normal browser

**Comment by bcoe** [comment]
:wave: @onigetoc this repository is specifically for the client library, not issues related to the `dialogflow` product in general.

I suggest giving product feedback [here](https://issuetracker.google.com/savedsearches/5300385).

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We replied to this issue a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue if needed.
