### ISSUE TITLE
Where could I found the list version mapping between package with the GG-dialogflow

### ISSUE THREAD

**Issue by dieuit07** [googleapis/nodejs-dialogflow#533]
Hi guys, I'm using version 0.8.2, and I wonder if It currently uses the Dialogflow API version 1 OR 2.
It has been using in the project for a long time ago. And Dialogflow sent the notification about the deprecate v1. So that I need to find out which version of Dialogflow the project is using.

In the project, it only uses for "create sessionPath" and "detectIntent" to get response from DialogFlow.
In the Dialogflow I also see the Agent selecting V2-API. The API is using without an error. Would it already be compatible with Dialogflow v2.0 or I need to upgrade it to a higher version

I find in the document but couldn't find the mapping versions. Please instruct me.

**Comment by bcoe** [comment]
@dieuit07 :wave: if you run `npm pack dialogflow@0.8.2`, you can see a list of files published with the library.

It looks like `0.8.2` is using `v2` of the API:

```bash
npm notice 11.0kB src/v2/doc/google/cloud/dialogflow/v2/doc_agent.js                        
npm notice 6.9kB  src/v2/doc/google/cloud/dialogflow/v2/doc_context.js                      
npm notice 17.6kB src/v2/doc/google/cloud/dialogflow/v2/doc_entity_type.js                  
npm notice 42.5kB src/v2/doc/google/cloud/dialogflow/v2/doc_intent.js                       
npm notice 8.1kB  src/v2/doc/google/cloud/dialogflow/v2/doc_session_entity_type.js          
npm notice 24.7kB src/v2/doc/google/cloud/dialogflow/v2/doc_session.js                      
npm notice 2.8kB  src/v2/doc/google/longrunning/doc_operations.js                           
npm notice 4.8kB  src/v2/doc/google/protobuf/doc_any.js                                     
npm notice 1.4kB  src/v2/doc/google/protobuf/doc_empty.js                                   
npm notice 7.2kB  src/v2/doc/google/protobuf/doc_field_mask.js                              
npm notice 3.8kB  src/v2/doc/google/protobuf/doc_struct.js                                  
npm notice 4.2kB  src/v2/doc/google/rpc/doc_status.js                                       
npm notice 1.5kB  src/v2/doc/google/type/doc_latlng.js                                      
npm notice 2.3kB  src/v2/entity_types_client_config.json                                    
npm notice 51.9kB src/v2/entity_types_client.js             
```

If possible, mind you, I strongly recommend upgrading to `1.2.0`, and then shortly after `v2.0.0` as soon as it's released (this will given you nice new features like TypeScript).

**Comment by dieuit07** [comment]
Thank you for your quick helpful support, @bcoe :+1:  . I've just updated it to 1.2.0 :high_brightness:
