### ISSUE TITLE
Recently Added Intents are not being triggered

### ISSUE THREAD

**Issue by agnescameron** [googleapis/nodejs-dialogflow#536]
Hi there --

My operating system is MacOS High Sierra 10.13.3. Not sure how to re-create this issue (I think if I were able to, I'd be able to fix it).

I've been trying to debug a problem with our agent for a while now, and have been running up against a mysterious error. I'm interfacing to DF using the NodeJS client, which is why I've posted the issue here, though I believe the issue might lie with the platform itself (if there's a better place to post this, please advise).

None of the intents that I have added in the past week are being triggered when a text that matches a training phrase is entered. Currently, I am creating new intents using the web console interface, and then communicating with the bot using the nodeJS API.

I have tried modifying the lifespans of the context to make sure they are not interfering with one another, and also have ensured that the text on each intent is sufficiently specific as to prevent interference.

The most recent test I have tried is to run a query in the Dialogflow console itself, having reset all contexts. (I also notice the mysterious appearence of a context called system_counters, which I don't believe was there before) The results are shown below: despite the query being a verbatim training phrase (the training phrases are specific, and definitely dissimilar to training phrases for other intents for this agent).

![Screen Shot 2020-02-12 at 15 34 37](https://user-images.githubusercontent.com/16444898/74376976-12e88580-4db1-11ea-8ddd-781e1c1d6989.png)

I do not believe that this project has exceeded a quota limit. There are currently around 25 intents, and fewer than 20 training phrases per agent.

All previously written intents continue to work fine, and I am able to change and update training and response phrases without issue.

The only issue I can think of that has changed the account in the past week or so is that we created a service account that can manage multiple agents simultaneously. This is necessary for our application, as we're running a serverless site which can only store one private key as a process variable. This itself was discussed on the Google forums, and was a solution that others had successfully used. I can't think why that would affect the adding of intents, though, especially as everything else continues to work as expected.

Thanks!

agnes

**Comment by bcoe** [comment]
@agnescameron this repository is specifically for the JavaScript client libraries used to interact with dialogflow, we don't work on the dialogflow UI.

It might be worth opening an issue [here](https://issuetracker.google.com/savedsearches/5300385), which is the issue tracker for the product :+1: 

Let me know if I'm misunderstanding your problem.

**Comment by agnescameron** [comment]
sure, thanks! I mean, I think it's not a UI problem specifically, but it's not a Node problem either. Thanks for the tip!
