### ISSUE TITLE
entityOverrideMode for CreateSessionEntityTypeRequest should be of type number

### ISSUE THREAD

**Issue by jaycosaur** [googleapis/nodejs-dialogflow#537]
#### Environment details

  - Node.js version: 10.14.2
  - npm version: 6.4.1
  - `@google-cloud/dialogflow` version: 1.2.0

#### Steps to reproduce
The library currently has the following type for SessionEntityType:
```
interface SessionEntityType {
  name: string;
  entityOverrideMode: string;
  entities: Entity[];
}
```

But in consulting other language docs and the rest documentation as found [here](https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent.sessions.entityTypes#SessionEntityType) the entityOverrideMode is wrong and should instead be of type:

```
interface SessionEntityType {
  name: string;
  entityOverrideMode: number;
  entities: Entity[];
}
```

As a request the library should also expose access to the enum EntityOverrideMode:
```
ENTITY_OVERRIDE_MODE_UNSPECIFIED = 0;
ENTITY_OVERRIDE_MODE_OVERRIDE = 1;
ENTITY_OVERRIDE_MODE_SUPPLEMENT = 2;
```
Like:
```
import dialogflow from 'dialogflow'

const overrideMode = dialogflow.EntityOverrideMode.ENTITY_OVERRIDE_MODE_UNSPECIFIED // 0
```

Thanks team!

**Comment by bcoe** [comment]
:wave: thanks for the bug report, we have a new version of the library going out soon.

**Comment by bcoe** [comment]
@jaycosaur with the latest version of the library, I see that the interface is now:

```js
                /** Properties of a SessionEntityType. */
                interface ISessionEntityType {

                    /** SessionEntityType name */
                    name?: (string|null);

                    /** SessionEntityType entityOverrideMode */
                    entityOverrideMode?: (google.cloud.dialogflow.v2.SessionEntityType.EntityOverrideMode|keyof typeof google.cloud.dialogflow.v2.SessionEntityType.EntityOverrideMode|null);

                    /** SessionEntityType entities */
                    entities?: (google.cloud.dialogflow.v2.EntityType.IEntity[]|null);
                }
```

I believe this means you should be able to provide either a string version of the enum, or the numeric form of the enum:

```js

                    enum EntityOverrideMode {
                        ENTITY_OVERRIDE_MODE_UNSPECIFIED = 0,
                        ENTITY_OVERRIDE_MODE_OVERRIDE = 1,
                        ENTITY_OVERRIDE_MODE_SUPPLEMENT = 2
                    }
```

Can you confirm that this is working for you now?

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you, so we are closing it. Please feel free to re-open this issue.
