### ISSUE TITLE
Send training data

### ISSUE THREAD

**Issue by SebasPZ82** [googleapis/nodejs-dialogflow#55]
How can i use the sdk to train

maybe i am getting this bad, but do i need to send the message id and the intent id to train an agent?? 

Thanks!

**Comment by JustinBeckwith** [comment]
cc @googleapis/ml-apis

**Comment by nnegrey** [comment]
Do you mean Training phrases for an Intent?
https://dialogflow.com/docs/intents/training-phrases
or
https://dialogflow.com/docs/training-analytics/training

From the SDK, you could update an Intent's training phrases using: [UpdateIntentRequest](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.UpdateIntentRequest)

Let me know if that helps! :)
