### ISSUE TITLE
vuejs module 

### ISSUE THREAD

**Issue by ahmadihussain** [googleapis/nodejs-dialogflow#551]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/dialogflow` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ahmadihussain** [comment]
how to solve this error 

./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\HUSSAIN\Desktop\haji-admin\node_modules\@grpc\grpc-js\build\src'

**Comment by ahmadihussain** [comment]
how i can  this sovle error in vuejs 

./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\HUSSAIN\Desktop\haji-admin\node_modules\@grpc\grpc-js\build\src'

**Comment by ahmadihussain** [comment]
how I can  this solve the error in Vuejs 

./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\HUSSAIN\Desktop\haji-admin\node_modules\@grpc\grpc-js\build\src'

**Comment by bcoe** [comment]
:wave: hey @ahmadihussain, the `@grpc/grpc-js` dependency does not work in the browser (and in turn Vuejs). It should be possible to webpack this library however, following [instructions outlined here](https://github.com/googleapis/google-cloud-node/issues/2933).
