### ISSUE TITLE
Version 2 not available on npmjs

### ISSUE THREAD

**Issue by yusufkhan07** [googleapis/nodejs-dialogflow#560]
#### Environment details

  - OS: Ubuntu 18
  - Node.js version: 10.18.1 
  - npm version: 6.13
  - `@google-cloud/dialogflow` version: 1.2

#### Steps to reproduce

Version 2 isn't available on npm. Doing `npm i @google-cloud/dialogflow` fails with the error given below while `npm i dialogflow` installs `v1.2` which doesn't support typescript.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fdialogflow - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/dialogflow@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

Thanks!

**Comment by bcoe** [comment]
we are currently blocked awaiting dropping of Node 8 support, this process should begin later this week.

**Comment by diegodalbosco** [comment]
> we are currently blocked awaiting dropping of Node 8 support, this process should begin later this week.

HI @bcoe, any news about the date?

**Comment by JockeRider199** [comment]
You can still use the v2 by using this command (require git):
`npm install --save github:googleapis/nodejs-dialogflow`

I use this because i need typescript types ^^

**Comment by weeix** [comment]
From the note in README.md, I thought `@google-cloud/dialogflow` was already on npmjs and tried to install it too.

**Comment by bcoe** [comment]
@weeix @JockeRider199 @yusufkhan07 👋 `2.x.x` is now available on npm:

`npm i @google-cloud/dialogflow`

Note that you will require Node 10 or greater to run this 👍
