### ISSUE TITLE
Mega-agent support

### ISSUE THREAD

**Issue by raphaelsilvasage** [googleapis/nodejs-dialogflow#561]
Could you please add the mega-agent creation feature?

If I trigger an API request, there is this payload:

Request URL: https://api.dialogflow.com/api-client/agents (POST)
Request Payload
`
{"name":"MEGA","description":"","language":"pt-br","enableFulfilment":false,"primaryKey":"","secondaryKey":"","alexa":{"alexaCompatible":false},"cortana":{"cortanaCompatible":false,"cortanaAppName":null},"slack":{"slackCompatible":false,"slackClientId":null,"slackClientSecret":null,"slackSuccessPage":null,"directMention":true,"directMessage":true,"mention":true,"ambient":false,"publishedOnline":false},"facebook":{"facebookCompatible":false,"verifyToken":null,"pageAccessToken":null,"welcomeEvent":false},"kik":{"kikCompatible":false,"apiKey":null,"botName":null},"telegram":{"telegramCompatible":false,"token":null},"twilio":{"twilioCompatible":false},"twilioip":{"twilioipCompatible":false,"accountSid":null,"serviceSid":null,"signingKeySecret":null,"signingKeySid":null},"viber":{"viberCompatible":false,"botName":null,"apiKey":null,"avatar":null,"welcomeEvent":false},"skype":{"skypeCompatible":false,"applicationId":null,"secretId":null},"dialogflowMessenger":{"dialogflowMessengerCompatible":false},"slackRest":{"slackRestCompatible":false,"clientId":null,"clientSecret":null,"verifyToken":null,"ambient":true,"slackSuccessPage":null},"useCustomClassifier":true,"intentParamsAutoSync":true,"defaultTimezone":"America/Buenos_Aires","webhook":{"url":null,"username":null,"password":null,"basicAuthorizationCode":null,"headers":null,"available":false,"useForDomains":false},"tropo":{"tropoCompatible":false},"spark":{"sparkCompatible":false,"accessToken":null},"line":{"lineCompatible":false,"channelId":null,"channelSecret":null,"channelAccessToken":null},"twitter":{"twitterCompatible":false,"botName":null,"consumerKey":null,"consumerSecret":null,"accessToken":null,"accessTokenSecret":null},"isPrivate":true,"customClassifierMode":"use.after","googleAssistant":{"googleAssistantCompatible":false,"welcomeIntentSignInRequired":false,"invocationName":null,"project":null,"testingTimeout":null,"startIntents":[],"endIntentIds":[],"systemIntents":[],"voiceType":"male_1","env":null,"autoPreviewEnabled":null,"oAuthLinking":{"providerId":null,"clientId":null,"clientSecret":null,"authorizationUrl":null,"tokenUrl":null,"scopes":null,"grantType":"AUTH_CODE_GRANT"}},"mlMinConfidence":0.3,"additionalConfigs":{},"disableInteractionLogs":false,"enableOnePlatformApi":true,"onePlatformApiVersion":"v2","textToSpeech":{},"agentTier":1,"isMegaAgent":true,"hangouts":{"hangoutsCompatible":true}}
`

I think that is something related to "isMegaAgent" property

**Comment by b-loved-dreamer** [comment]
Introducing this feature request to a Public Issue Tracking. Closing this issue.
