### ISSUE TITLE
SessionsClient construction consistently takes > 100ms to create

### ISSUE THREAD

**Issue by wparad** [googleapis/nodejs-dialogflow#570]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 12.13.1
  - npm version: 6.12.1
  - `@google-cloud/dialogflow` version: 1.2

#### Steps to reproduce

```js
new dialogflow.v2beta1.SessionsClient();
```

This shouldn't take 100ms to complete. With lower memory and CPU this is forever.

**Comment by b-loved-dreamer** [comment]
I tried reproducing this issue but was unable to. I am closing this issue but feel free to re-open if needed.
