### ISSUE TITLE
Error: Getting metadata from plugin failed with error: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-dialogflow#575]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.16.0
  - npm version:  6.13.0
  - `dialogflow` version: 1.2.0
  - Environment Variable called "GOOGLE_APPLICATION_CREDENTIALS" and value is set to the path containing my-service-account.json

#### Steps to reproduce

  1.  run firebase serve --only functions

Then these comes to console
```
!  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to c:\gcloud\xybot-studio-dev-c0bad30738a5.json. Non-emulated services will access production using these credentials. Be careful!
i  functions: Beginning execution of "api"
!  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
```

  2. Access a Firestore collection
```
!  Google API requested!
   - URL: "https://www.googleapis.com/oauth2/v4/token"
   - Be careful, this may be a production service.
>  [Nest] 10848   - 03/31/2020, 6:14:08 PM   [ExceptionsHandler] 2 UNKNOWN: Getting metadata from plugin failed with error: error:0909006C:PEM routines:get_name:no start line +839ms
>  Error: 2 UNKNOWN: Getting metadata from plugin failed with error: error:0909006C:PEM routines:get_name:no start line
>      at Object.callErrorFromStatus (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
>      at Http2CallStream.call.on (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
>      at Http2CallStream.emit (events.js:203:15)
>      at process.nextTick (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:100:22)
>      at process._tickCallback (internal/process/next_tick.js:61:11)
```

p.s This is how I am initializing the admin
```
admin.initializeApp(functions.config().firebase);
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@RezaRahmati it looks like you're interacting with an emulator, is this unpurpose? i.e., are you attempting to test dialogflow in the context of the emulator?

**Comment by RezaRahmati** [comment]
@bcoe Thanks for reply, I am creating a backend to interact with dialogflow, and my backend is firebase, Now I am explaining to you, I think I found what I did wrong, let me investigate and I will be back

**Comment by RezaRahmati** [comment]
@bcoe I found the root cause, I stored service accounts private_key in firestore, seems when I read from that and I pass it to firebase then it happens, I am invsetigating what is wrong with storing service account private key

**Comment by RezaRahmati** [comment]
@bcoe problem is solved, When using Firestore UI to store private key it will convert all of '\n' to `\\n` and when passing to dialogflow api, it was malformed and throwing error. So I start string them via firestore apis and then it become OK.
