### ISSUE TITLE
How to create versions and environments of an agent?

### ISSUE THREAD

**Issue by guilhermegehres** [googleapis/nodejs-dialogflow#597]
I need to create an agent version as I do from the console

**Comment by b-loved-dreamer** [comment]
Hi @guilhermegehres — I found this [information](https://cloud.google.com/dialogflow/es/docs/agents-versions), potentially, on agent versioning. If still relevant, please take a look at it. 

I am closing this issue given that it may no longer be relevant. If needed, please reopen.

**Comment by wparad** [comment]
Please reopen, we want to do with through the API/library, not in the console.
