### ISSUE TITLE
Documentation links to 404

### ISSUE THREAD

**Issue by ibrnt** [googleapis/nodejs-dialogflow#6]
Hey team,

Looks like the links in the Readme are pointing to 404 pages:

Dialogflow Node.js Client API Reference should lead to https://dialogflow.com/docs/reference/api-v2/rpc/ 
Instead it opens as a 404 page

Dialogflow Documentation should lead to https://dialogflow.com/docs/reference/api-v2/rpc/
Instead it opens as a 404 page

Thanks.

**Comment by lukesneeringer** [comment]
I agree that the links 404, but they are set to exactly that URL.

**Comment by sstepashka** [comment]
@lukesneeringer I'm not sure, that it's ok. Someone have to setup this pages? Or just leave it as is?

**Comment by JustinBeckwith** [comment]
These appear to be fixed 🎉
