### ISSUE TITLE
How to configure the Webhook with this library? (v2)

### ISSUE THREAD

**Issue by chroth7** [googleapis/nodejs-dialogflow#604]
Maybe I am just blind, but I fail to see how to configure the webhook (url, headers, etc) using this client library. Probably it is missing?
(I managed to create agents, add intents, entityTypes, etc, that all works well)

 **Is your feature request related to a problem? Please describe.**
Well, if I add a webhook fulfillment on an intent, it obviously fails on a new agent, as the webhook URL is missing.
 **Describe the solution you'd like**
Maybe a parameter on the `IAgent` would do the trick.
 **Describe alternatives you've considered**
...
 **Additional context**
In the UI:
![image](https://user-images.githubusercontent.com/6230368/80979677-f300b500-8e27-11ea-9bde-696b1391c7bd.png)

Thanks for the great library, by the way!
Having Typescript support makes life so much easier!

**Comment by HiroshiHorie** [comment]
I must be totally blind also because the WebhookRequest, WebhookResponse interfaces exist in the package code but I can't access it from my code despite wasting a few hours.

**Comment by thus001a** [comment]
I need the same feature. It looks like the GRPC API supports this: https://cloud.google.com/dialogflow/es/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.UpdateFulfillmentRequest
I would have thought the node API is automatically generated from the GRPC API? So why do they not offer the same features?

**Comment by b-loved-dreamer** [comment]
Hi @chroth7 — Here's a [resource](https://developers.google.com/assistant/conversational/df-asdk/dialogflow/fulfillment) that may be helpful.

This issue has remained inactive for a while so I am closing it, but please feel free to reopen if needed.

**Comment by chroth7** [comment]
hi @b-loved-dreamer  - sadly, I wasn't working much with Dialogflow recently, so fine for me to close for now. I assume the other commenters agree :-)

Also, thanks for the link, will have a look!
