### ISSUE TITLE
Property 'sessionPath' does not exist on type 'SessionsClient'.ts(2339)

### ISSUE THREAD

**Issue by ajmas** [googleapis/nodejs-dialogflow#605]
#### Environment details

  - OS: macOS 10.15.4
  - Node.js version: 12.16.2
  - npm version: 6.13.6
  - `@google-cloud/dialogflow` version: 2.0.0
  - typescript: 3.8.3

#### Steps to reproduce

In a Typescript based project, working from within vscode:

```
import dialogflow from '@google-cloud/dialogflow';

const client = new dialogflow.SessionsClient(this.config);
const sessionPath = client.sessionPath(this.projectId, sessionId);
```

I am being told that:

> Property 'sessionPath' does not exist on type 'SessionsClient'.ts(2339)

This only became an issue when switching from the 1.2.0 `dialogflow` package to the 2.0.0 `@google-cloud/dialogflow`. The example in the [README.md](https://github.com/googleapis/nodejs-dialogflow/blob/master/README.md) shows equivalent code:

```
  // Create a new session
  const sessionClient = new dialogflow.SessionsClient();
  const sessionPath = sessionClient.sessionPath(projectId, sessionId);
```

looking in sessions_client.ts the closest I could see was `projectAgentEnvironmentUserSessionPath()`.

Is there an issue in my understanding or is this a documentation issue with a breaking change?

**Comment by ajmas** [comment]
Further testing suggests that `projectAgentSessionPath()` is right method to use and the documentation needs updating.

**Comment by bcoe** [comment]
@ajmas it sounds like you found a workaround? but we need to update some of our samples?

**Comment by ajmas** [comment]
@bcoe the samples are fine. It is just the README.md that needs updating.

**Comment by bcoe** [comment]
@ajmas looks like we're not auto-generating the README, which explains how we got out of sync.
