### ISSUE TITLE
Main readme file should use const dialogflow = require('@google-cloud/dialogflow').v2;

### ISSUE THREAD

**Issue by avallone-google** [googleapis/nodejs-dialogflow#613]
The main readme file states to use the lib like this:
const dialogflow = require('dialogflow');

This should be chaned to, like the samples use:
const dialogflow = require('@google-cloud/dialogflow').v2;

**Comment by peternann** [comment]
Plus this needs updating too, right: "npm install dialogflow" ???

**Comment by munkhuushmgl** [comment]
@avallone-google From my understanding, this issue may be already fixed. Could you confirm it is fixed ?

if there is anything missing, I would like to make small changes for you.

**Comment by avallone-google** [comment]
LGTM
