### ISSUE TITLE
Dialogflow slot filling for sys.any not picking up full string

### ISSUE THREAD

**Issue by davidvc** [googleapis/nodejs-dialogflow#640]
I am not sure where this belongs. I am using the Dialogflow UI, and I am hitting an error exactly as described here: https://github.com/dialogflow/dialogflow-javascript-client/issues/111

But this client has been deprecated. Was it replaced by this one? I can't tell. But this is still very much an issue and is blocking me from building a simple intent that lets me prompt a user for a message so they can send an email.

Please let me know if I should be taking this issue elsewhere. Otherwise, happy to provide more details.

**Comment by munkhuushmgl** [comment]
@davidvc As I investigated into this bug, there has been a bug already reported internally. I will follow up on that internal bug.

**Comment by davidvc** [comment]
Thanks, Mike. It's quite a blocker so hope we can get this resolved soon.

All the best,

David

**Comment by davidvc** [comment]
This is no longer an issue with the new Conversational Actions SDK
