### ISSUE TITLE
Create Intent take parameters from the Training Phrases and tag an entity type in python? 

### ISSUE THREAD

**Issue by Jenetty** [googleapis/nodejs-dialogflow#659]
I'm fairly new to programming world.
I'm trying to create an Intent with API using python.
My intention is to create an intent from API which can
 - take training phrases
 - prompt for parameters inputs from user
 - fullfillment enabled for the intent
 

Example:

Intent_Display_Name = 'GetNameFromID'
Training Phrases = ['What is the name of the employee who's id is 6',"Please get name for ID 6"]

for this I'm able to create the intents as below in python.

-----------------------------------------------------------------------------------------------------------------------------------
def create_intent(project_id, display_name, training_phrases_parts,
                  message_texts):
    """Create an intent of the given intent type."""
    import dialogflow_v2 as dialogflow
    intents_client = dialogflow.IntentsClient()

    parent = intents_client.project_agent_path(project_id)
    training_phrases = []
    for training_phrases_part in training_phrases_parts:
        part = dialogflow.types.Intent.TrainingPhrase.Part(
            text=training_phrases_part)
        # Here we create a new training phrase for each provided part.
        training_phrase = dialogflow.types.Intent.TrainingPhrase(parts=[part])
        training_phrases.append(training_phrase)

    text = dialogflow.types.Intent.Message.Text(text=message_texts)
    message = dialogflow.types.Intent.Message(text=text)

    intent = dialogflow.types.Intent(
        display_name=display_name,
        training_phrases=training_phrases,
        messages=[message])
    
    response = intents_client.create_intent(parent, intent)

    print('Intent created: {}'.format(response))

project_id = 'project_id'
display_name = 'GetNameFromID'
training_phrases_parts = ["What is the name of the employee who's id is 6","please get id"]
message_texts = [" Sure, getting the id for the name"]
create_intent(project_id,display_name,training_phrases_parts,message_texts)

-----------------------------------------------------------------------------------------------------------------------------

My problem is:

I'm able to :
             Create intent with training phrases 
But, I'm unable to:
             Extract the ID as a parameter from the user.
             Enable the fulfilment from API
Please help me.

Thanks.

**Comment by Jenetty** [comment]
Can someone please check this?

**Comment by munkhuushmgl** [comment]
@Jenetty I will help you with this.

**Comment by munkhuushmgl** [comment]
Were you able to do this using Dialogflow UI?

**Comment by munkhuushmgl** [comment]
you can extract user ID by using system entity type number @sys.number  in your action. I would suggest you to do it in UI first, then client library after that. Also, this is not python repo. Next time, please create the issue in python-dialogflow repo.

**Comment by munkhuushmgl** [comment]
closing this due to duplicate issue
https://github.com/googleapis/dialogflow-python-client-v2/issues/212
