### ISSUE TITLE
getValidationError() is not a function.

### ISSUE THREAD

**Issue by husseinajami10** [googleapis/nodejs-dialogflow#670]
I am trying this link https://googleapis.dev/nodejs/dialogflow/latest/google.cloud.dialogflow.v2.Agents.html#getValidationResult2
to get the validation result using APIv2 and NodeJS code but i always get an error .getValidationResult() is not a function.kindly find the below code:
const credentials = {

  "type": keys.CREDENTIALS_TYPE,

  "project_id": keys.GOOGLE_PROJECT_ID,

  "private_key_id": keys.PRIVATE_KEY_ID,

  "private_key": keys.PRIVATE_KEY,

  "client_email": keys.CLIENT_EMAIL,

  "client_id": keys.CLIENT_ID,

  "auth_uri": keys.AUTH_URI,

  "token_uri": keys.TOKEN_URI,

  "auth_provider_x509_cert_url": keys.AUTH_PROVIDER_X509_CERT_URL,

  "client_x509_cert_url": keys.CLIENT_X509_CERT_URL,

};

 const agent = new dialogflow.AgentsClient({credentials: credentials}); 

 

  

 Data.findOne({ projectid2 : req.body.projectID}).then(async profile => { if (profile) {

 

   var req = {

    

    parent: "projects/"+projectid2, 

    

    };

   try {

    var responses = await agent.getValidationResult(req);

    

    res.send(responses);

    } catch (error) {

    console.log("we have an error");

    console.log(error);

    }

   } })

**Comment by husseinajami10** [comment]
> I am trying this link https://googleapis.dev/nodejs/dialogflow/latest/google.cloud.dialogflow.v2.Agents.html#getValidationResult2
> to get the validation result using APIv2 and NodeJS code but i always get an error .getValidationResult() is not a function.kindly find the below code:
> const credentials = {
> 
> "type": keys.CREDENTIALS_TYPE,
> 
> "project_id": keys.GOOGLE_PROJECT_ID,
> 
> "private_key_id": keys.PRIVATE_KEY_ID,
> 
> "private_key": keys.PRIVATE_KEY,
> 
> "client_email": keys.CLIENT_EMAIL,
> 
> "client_id": keys.CLIENT_ID,
> 
> "auth_uri": keys.AUTH_URI,
> 
> "token_uri": keys.TOKEN_URI,
> 
> "auth_provider_x509_cert_url": keys.AUTH_PROVIDER_X509_CERT_URL,
> 
> "client_x509_cert_url": keys.CLIENT_X509_CERT_URL,
> 
> };
> 
> const agent = new dialogflow.AgentsClient({credentials: credentials});
> 
> Data.findOne({ projectid2 : req.body.projectID}).then(async profile => { if (profile) {
> 
> var req = {
> 
> ```
> parent: "projects/"+projectid2, 
> 
> 
> 
> 
> 
> };
> ```
> 
> try {
> 
> ```
> var responses = await agent.getValidationResult(req);
> 
> 
> 
> 
> 
> res.send(responses);
> 
> 
> } catch (error) {
> 
> 
> console.log("we have an error");
> 
> 
> console.log(error);
> 
> 
> }
> ```
> 
> } })

**Comment by munkhuushmgl** [comment]
@husseinajami10 which version were u using for issue?

**Comment by husseinajami10** [comment]
i am using the api v2
________________________________

**Comment by b-loved-dreamer** [comment]
Hi @husseinajami10, can you please provide more details around what your goal is and how you’re trying to get to that goal. Can you please describe your goal. It's difficult to discern from the code you shared.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free re-open this issue with more information.
