### ISSUE TITLE
Property setAgent does not exist on type Resource$Projects in v2.d.ts and v2beta1.d.ts

### ISSUE THREAD

**Issue by MatthewPorter31** [googleapis/nodejs-dialogflow#672]
Environment details
  - OS: Windows 10
  - Node.js version: `v10.13.0`
  - npm version: `googleapis - 59.0.0`
  - `@google-cloud/dialogflow` version: `3.2.0`

Steps to reproduce
1. import googleapis, initialize an oAuth2Client with tokens, and initialize dialogflow
`import { google } from 'googleapis'`
`const oAuth2Client = new google.auth.OAuth2(clientId, clientSecret, 'postMessage)'`
`oAuth2Client.setCredentials(tokens)`
`const dialogflow = google.dialogflow({ auth: oAuth2Client, version 'v2' })`

2. trying to call the setAgent method creates a Typescript error that setAgent does not exist
`const createdAgentResponse = await dialogflow.projects.setAgent({ params })`

Looks like issue #413 was created nearly one year ago and resolved, but after updating my googleapis package, I'm still running in to this error with both the `v2` and `v2beta1` Dialogflow versions.

Thanks!

**Comment by munkhuushmgl** [comment]
@MatthewPorter31 I will look into it.

**Comment by telpirion** [comment]
@MatthewPorter31 The snippet you provided doesn't show the best way to construct a Dialogflow client:

```
const dialogflow = require('@google-cloud/dialogflow');
const sessionClient = new dialogflow.SessionsClient();
```

I will close this issue for now. Please reopen if necessary.
