### ISSUE TITLE
Wrong NPM package in README?

### ISSUE THREAD

**Issue by RiccardoCalvi** [googleapis/nodejs-dialogflow#677]
Shouldn't it be `npm install @google-cloud/dialogflow`?
With the current name I get the error `sessionClient.projectAgentSessionPath is not a function`.
See also https://stackoverflow.com/questions/63177431/node-and-dialogflow-error-unhandledpromiserejectionwarning-typeerror-sessionc.

Cheers,
Ricky

**Comment by bcoe** [comment]
@RiccardoCalvi thank you for the note, we should fix this 👍
