### ISSUE TITLE
documentation request: webhook samples

### ISSUE THREAD

**Issue by olivoil** [googleapis/nodejs-dialogflow#708]
**Is your feature request related to a problem? Please describe.**

The project `dialogflow-fulfillment` is now deprecated, however it's still used in the default inline function when creating a webhook, and there is no clear recommendation to migrate from this library. `nodejs-dialogflow` seems to expose classes that would be useful to implement a webhook for fulfillment (`WebhookRequest` and `WebhookResponse`), but there are no examples showing how to leverage them.

 **Describe the solution you'd like**

Adding samples to showcase how this library can be used for fulfillment would be useful.

**Comment by b-loved-dreamer** [comment]
@olivoil — Thank you for filing this issue. We are going to carefully consider this ```feature request``` for updates to the ```dialogflow``` samples and documentation. In the mean time, please check out this [tutorial](https://cloud.google.com/dialogflow/es/docs/tutorials/sequences/create-fulfillment-using-webhook).

**Comment by b-loved-dreamer** [comment]
Closing this issue.
