### ISSUE TITLE
sessionClient.detectIntent retruns an invalid_request error

### ISSUE THREAD

**Issue by vickywane** [googleapis/nodejs-dialogflow#713]
Hi , 

I am currently using the `@google-cloud/dialogflow` package from a browser environment ( React.js App ). I have passed in the auth instance using the `google-auth-library`. I generated a refresh token using the Google OAuth Playground with the required scope for the Dialogflow service included, then I set the credentials of the Auth instance with the refresh_token. 

This works fine until I try to detect intent.

1) Is this a client library issue or a product issue?
   This is a client library issue, I continuously get an `invalid_request` error and from the Network request tab a `400 ( Bad Request)` status code error. A snapshot of the full error is attached below;
![Screenshot from 2020-11-15 19-07-08](https://user-images.githubusercontent.com/29664439/99192900-cd108180-2775-11eb-978d-d2b0c8ab339d.png)

#### Environment details

  - OS:  Ubuntu 20.04.1 LTS 
  - Node.js version: v14.13.0
  - npm version: 6.14.8
  - `@google-cloud/dialogflow` version: ^3.3.0

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vickywane** [comment]
@bcoe this issue still persists. 

Can you please enlighten me on a likely fix?

**Comment by bcoe** [comment]
@vickywane `@google-cloud/dialogflow` uses gRPC, which does not work in the browser. It should be possible to make things work using [webpack](https://github.com/googleapis/google-cloud-node/issues/2933#issuecomment-547657659), but we do not (as of today) actively support a browser environment with the library.

Another approach you might use is to have a backed service, perhaps in a Cloud Function, that runs the operation with `@google-cloud/dialogflow`, and then have the react app simply interact with the function.

**Comment by vickywane** [comment]
Alright, i some statements on the last active thread with regards to this saying browser support is out but still experimental. 

I'll just move forward with the Node express backend service like you have suggested, even though I tried running from it. 

Closing this now.
