### ISSUE TITLE
Dialogflow - environments not working or allowing to publish

### ISSUE THREAD

**Issue by rachanakalchetty** [googleapis/nodejs-dialogflow#741]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/dialogflow` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by telpirion** [comment]
@rachanakalchetty Please provide more details so that we can investigate. Thank you!

**Comment by b-loved-dreamer** [comment]
Hi @rachanakalchetty, would you please elaborate more on the issue you're experiencing? The description section was left with default text.

**Comment by monkfruit123** [comment]
This is a feature that I am interested in as well. As I understand, the dialogflow API does not support publishing a new version of the bot, or to "promote" a version of the bot to higher environments.

I would love to be able to orchestrate deployment through pipelines, but because the API does not exist, we have to login to the console to do this.

**Comment by b-loved-dreamer** [comment]
Hi @monkfruit123 — we are trying to understand the specifics of this feature request, if indeed it is a feature request. The originator of this issue ticket has not provided a descriptive answer to that effect. If this is something you are trying to pursuit, please open a new issue and explain with clarity what it is you want to see included as part of our service and we'll determine if your request is achievable based on our design and architecture constraints and availability.

**Comment by b-loved-dreamer** [comment]
Thank you (@rachanakalchetty)  for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
