### ISSUE TITLE
Environments support

### ISSUE THREAD

**Issue by bivas6** [googleapis/nodejs-dialogflow#743]
Hi,

Can you add support for `projectLocationAgentEnvironmentSessionPath()` in the `SessionsClient` class?
I saw that this is exists in the df-cx library, but not in here.
Currently I manually create it like this:
```
    const projectLocationAgentEnvironmentPath = sessionClient.projectLocationAgentEnvironmentPath(
      projectId,
      location, 
      environment
    );
    const sessionPath = `${projectLocationAgentEnvironmentPath}/users/-/sessions/${sessionId}`; 
```

Thanks

**Comment by telpirion** [comment]
This sounds like a feature request for the Dialogflow service. Please file feature requests here:
https://issuetracker.google.com/savedsearches/5300385
