### ISSUE TITLE
Adding self signed cert to ChannelCredentials is not working

### ISSUE THREAD

**Issue by monkfruit123** [googleapis/nodejs-dialogflow#744]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Due to corporate proxy, calls to Dialogflow fail citing a SSL issue.

`E0224 15:00:59.989000000 24080 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.`

I tried to create ChannelCredential and pass it to the SessionsClient constructor, but it errored out with a different issue.

`   const sessionId = uuid.v4();
    const ssl_creds = grpc.credentials.createSsl(
        fs.readFileSync('certs/corporate_cert.cer'));
    const sessionClient = new dialogflow.SessionsClient({ 'sslCreds': ssl_creds });
    const sessionPath = sessionClient.projectAgentSessionPath(keyFile.project_id, sessionId);
    const request = {
        session: sessionPath,
        queryInput: {
            text: {
                text: 'query text',
                languageCode: 'en-US',
            },
        },
    };
    const responses = await sessionClient.detectIntent(request);
    console.log(responses)
    console.log('Detected Intent');
    const result = responses[0].queryResult;`

corporate_cert.cer contains all the certs in the cert chain i.e root and intermediate.

The error I receive is:

`(node:15424) UnhandledPromiseRejectionWarning: TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\channel.js:69:19)
    at new Client (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\client.js:58:36)
    at new ServiceClientImpl (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\make-client.js:58:5)
    at GrpcClient.createStub (C:\node\df-intent-visualization\node_modules\google-gax\build\src\grpc.js:235:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection 
id: 1)
(node:15424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.       `

I also tried by bypassing SSL validation using the following snippet of code.

`const ssl_creds = grpc.credentials.createInsecure();`

Here is the error log I received:

`D0224 15:15:38.858000000 27052 dns_resolver.cc:294] Using native dns resolver
I0224 15:15:38.858000000 27052 timer_manager.cc:88] Spawn timer thread
I0224 15:15:38.859000000 27052 init.cc:164] grpc_init(void)
I0224 15:15:38.859000000 30796 timer_manager.cc:250] timers not checked: expect another thread to
I0224 15:15:38.859000000 30796 timer_manager.cc:197] sleep until kicked
I0224 15:15:38.860000000 27052 completion_queue.cc:504] grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
(node:31008) UnhandledPromiseRejectionWarning: TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\channel.js:69:19)
    at new Client (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\client.js:58:36)
    at new ServiceClientImpl (C:\node\df-intent-visualization\node_modules\@grpc\grpc-js\build\src\make-client.js:58:5)
    at GrpcClient.createStub (C:\node\df-intent-visualization\node_modules\google-gax\build\src\grpc.js:235:22)
(node:31008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection 
id: 1)
(node:31008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.       
`

Version of libraries:

- "@google-cloud/dialogflow": "^3.3.0"
- "grpc": "^1.24.5"

**Comment by monkfruit123** [comment]
Any help would be much appreciated!

**Comment by munkhuushmgl** [comment]
Have u tried updating grpc version to latest?

**Comment by monkfruit123** [comment]
I looked at the package-lock.json files and the two dependencies look like they are the latest. Are they any other I should update to latest?

@grpc/grpc-js - 1.2.9
grpc - 1.24.5

**Comment by monkfruit123** [comment]
Any suggestions? I still haven't been able to solve this issue.

**Comment by munkhuushmgl** [comment]
Hey @bcoe Can you help me on this?

**Comment by bcoe** [comment]
@monkfruit123 rather than manually instantiating the gRPC client, try setting `https_proxy`:

https://github.com/grpc/grpc-node/blob/b44502144c3a5a1f40e6ba0b701ee8d21100d37f/packages/grpc-js/src/http_proxy.ts#L45

Then try setting the environment variable, `NODE_TLS_REJECT_UNAUTHORIZED=0`; which should suppress the SSL_ERROR_SSL -- this is not recommended if you do not trust that the certificates are in fact coming from your corporate proxy.

**Comment by monkfruit123** [comment]
Apologies for following up on this after a while.

Is there a way to install the certificates so we don't need to set the environment variable?
