### ISSUE TITLE
Unable to npm install pump in the samples/ directory.

### ISSUE THREAD

**Issue by itsmichaelwang** [googleapis/nodejs-dialogflow#75]
#### Environment details

  - OS: macOS High Sierra v10.13.2
  - Node.js version: v10.0.0
  - npm version: npm@6.0.0 (I also tried npm@5.1.0)
  - `dialogflow` version: v2? I cloned it today

#### Steps to reproduce

  1. clone the repo
  2. cd samples/
  3. npm install (or npm install pump, which seems to be the package causing the specific issue)

Get this error message:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/michael.wang/Workspace/dialogflow-nodejs-client-v2/samples/node_modules/.staging/fsevents-459b5284/node_modules/set-blocking' -> '/Users/michael.wang/Workspace/dialogflow-nodejs-client-v2/samples/node_modules/.staging/set-blocking-abdd6c3c'
> 
> npm ERR! path /Users/michael.wang/Workspace/dialogflow-nodejs-client-v2/samples/node_modules/.staging/dialogflow-2c1f8a43/node_modules/@mrmlnc/readdir-enhanced
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/Users/michael.wang/Workspace/dialogflow-nodejs-client-v2/samples/node_modules/.staging/dialogflow-2c1f8a43/node_modules/@mrmlnc/readdir-enhanced' -> '/Users/michael.wang/Workspace/dialogflow-nodejs-client-v2/samples/node_modules/.staging/@mrmlnc/readdir-enhanced-f9b82517'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/michael.wang/.npm/_logs/2018-05-03T23_20_02_953Z-debug.log
> 

Posting this to flag the issue, also to update with a solution if I am able to find one.

**Comment by eap23** [comment]
@itsmichaelwang Having exactly the same issue:

**Environment details**
- OS: macOS Sierra v10.12.6
- Node.js version: v8.11.4
- npm version: v5.6.0

**Steps to reproduce**
1. `clone the repo`
2. `npm install`
3. `cd samples/`
4. `npm install`

**Error message**
> 
> npm ERR! path /Users/../Documents/Code/Git/dialogflow-nodejs-client-v2/samples/node_modules/.staging/dialogflow-f99e8d81/node_modules/@babel/code-frame
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/Users/../Documents/Code/Git/dialogflow-nodejs-client-v2/samples/node_modules/.staging/dialogflow-f99e8d81/node_modules/@babel/code-frame' -> '/Users/../Documents/Code/Git/dialogflow-nodejs-client-v2/samples/node_modules/.staging/@babel/code-frame-a76a8747'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/../.npm/_logs/2018-09-19T07_42_36_817Z-debug.lo

Looking forward for a solution!

**Comment by eap23** [comment]
@itsmichaelwang Try deleting `/samples/package-lock.json` and then retry to run `npm install pump`.
Successfully installed.

**Comment by ankgitk** [comment]
1.
