### ISSUE TITLE
Not able to detect intent from audio bytes in audio streaming

### ISSUE THREAD

**Issue by axchanda** [googleapis/nodejs-dialogflow#79]
- OS: Windows 10
  - Node.js version: 8.9.0
  - npm version: 5.6.0
  - `dialogflow` version: 0.3.0

#### Steps to reproduce

I am trying to detect audio from buffer binary data, instead of streaming from a file as shown in the demo. 
  1. I tried to send the bytes to the detectStream as below.

```js
connection.on('message', (message) => {
     if (message.type === 'utf8') { console.log(message.utf8Data); }
    if (message.type === 'binary') { 
      detectStream.write({ inputAudio: (message.binaryData)});

// Message.binarydata is the buffer audio chunk
    }
});
```

It was detecting the audio well for every chunk but it didn't process the short Utterance data instead the recognitionResult always came as true. As per the sample code, it returns result only when recognitionResult is `null`.  For eg.,

```js
{
      "responseId": "",
      "recognitionResult": {
        "messageType": "TRANSCRIPT",
        "transcript": "I have an experience of two years",
        "isFinal": true,
        "confidence": 0.9128984212875366
      },
      "queryResult": null,
      "webhookStatus": null
    },
```

I want to process it once the isFinal becomes true or the recognitionResult to be made null once the short Utterance is acheived. 

  2. I had also tried for a workaround of converting the buffer to stream and then pumping it through2 function. This time utterly everything failed.

```js
      pump(streamifier.createReadStream(message.binaryData),
        // Format the audio stream into the request format.
        through2.obj((obj, _, next) => {
          next(null, { inputAudio: obj });
        }),
        detectStream
      ); 
```

Please let me know the quickest resolution possible.  Thanks!

**Comment by iceboal** [comment]
Hi @axchanda 

Did you call `detectStream.end()`?
https://github.com/grpc/grpc.github.io/blob/master/docs/tutorials/basic/node.md#streaming-rpcs

**Comment by utkarshmalik211** [comment]
+1

**Comment by infation** [comment]
Hey did you find a solution to the issue? I'm experiencing similar problem.

**Comment by krisgutta** [comment]
I ran into the same issue, it looks like dialogflow does not return the intent until the stream is closed. So you'd have to call 

detectStream.end();

my detectStream is initialized with the following code, 

this.detectStream = this.sessionClient
    .streamingDetectIntent()
    .on('error', console.error)
    .on('data', data => {
      if (data.recognitionResult) {
        console.log(
          `Intermediate transcript: ${data.recognitionResult.transcript}`
        );
      } else {
        console.log(`Detected intent:`);
        console.log(data.queryResult);
      }
    });

**Comment by axchanda** [comment]
@krisgutta That's fine! But still the question is unanswered 
_I want to process it once the isFinal becomes true or the recognitionResult to be made null once the short Utterance is acheived._

How will you be detecting the final event when there is a completion of speech from one end?

**Comment by nnegrey** [comment]
The last response will have `isFinal` set to true, once that happens you should process the result.

From: https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#streamingdetectintentrequest
"""
Optional. If false (default), recognition does not cease until the client closes the stream. If true, the recognizer will detect a single spoken utterance in input audio. Recognition ceases when it detects the audio's voice has stopped or paused. In this case, once a detected intent is received, the client should close the stream and start a new request with a new stream as needed. This setting is ignored when query_input is a piece of text or an event.
"""

**Comment by bcoe** [comment]
@axchanda did @nnegrey point you in the right direction?

**Comment by axchanda** [comment]
@bcoe @nnegrey What he mentioned is already know info. The issue is that while streaming the audio, the isFinal gets activated without closing the stream and we are able to process it is the trick here.

**Comment by nnegrey** [comment]
Once you see the `isFinal` set to true, I believe you need to close the stream, as mentioned by iceboal up above.

**Comment by bcoe** [comment]
@axchanda make sure that `singleUtterance` is set to `true` in your initialization, see:

https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js#L195

The pertinent code being:

```js
const initialStreamRequest = {
    session: sessionPath,
    queryParams: {
      session: sessionClient.sessionPath(projectId, sessionId),
    },
    queryInput: {
      audioConfig: {
        audioEncoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
      },
      singleUtterance: true,
    },
  };
```

You should then be able to run code almost identical to the sample, except instead of using `fs.createReadStream`. Try the module `stream-buffers` (`npm i stream-buffers`)  and replace `detect.js` sample code with the following:

```js
const {ReadableStreamBuffer} = require('stream-buffers')
const buffer = new ReadableStreamBuffer()
buffer.put(message.binaryData)
buffer.stop()

pump(
    buffer,
    // Format the audio stream into the request format.
    through2.obj((obj, _, next) => {
      next(null, {inputAudio: obj});
    }),
    detectStream
  );
```

**Comment by callmehiphop** [comment]
@axchanda have you had a chance to try out @bcoe's suggestion? Just want to follow up and see if this is still an issue for you

**Comment by callmehiphop** [comment]
Haven't seen much activity here lately and I believe @bcoe has answered the question. I'm going to close this out, but if anyone continues to experience this issue, please let us know! 😎
