### ISSUE TITLE
Support for Output Audio Encoding MULAW

### ISSUE THREAD

**Issue by bivas6** [googleapis/nodejs-dialogflow#800]
Hi,

We saw much improvement in the speech recognitions using MULAW in dialogflow-cx. 
We need to use the same audio encoding for input and output audio.
For some reason, the ES SDK doesn't seems to support output audio encoding MULAW, although it specified in the [docs](https://cloud.google.com/dialogflow/es/docs/reference/rpc/google.cloud.dialogflow.v2#outputaudioencoding)

We would appreciate a new version that support this codec. 
Thanks!!

**Comment by telpirion** [comment]
Thank you very much for the feature request! Please file your request here on the [public issue tracker](https://issuetracker.google.com/issues/new?component=501190).

**Comment by yoshigev** [comment]
Hi @telpirion,
Isn't the public issue tracker intended for issues with the cloud service?
@bivas6 request only regards the NodeJS SDK.
I believe that simply adding `OUTPUT_AUDIO_ENCODING_MULAW = 5` to the `OutputAudioEncoding` enum would be enough.
For example, the Java SDK supports it (see [here](https://googleapis.dev/java/google-cloud-dialogflow/latest/com/google/cloud/dialogflow/v2beta1/OutputAudioEncoding.html#OUTPUT_AUDIO_ENCODING_MULAW)).
Isn't this so?

Thanks,
Yehoshua
