### ISSUE TITLE
Is this library a replacement for https://github.com/googleapis/nodejs-dialogflow?

### ISSUE THREAD

**Issue by crup** [googleapis/nodejs-dialogflow#813]
I'm currently using this SDK which seems unmaintained at the moment. Is this repository a replacement for https://github.com/dialogflow/dialogflow-fulfillment-nodejs?

**Comment by munkhuushmgl** [comment]
@frankyn @lucaswadedavis Can you guys answer this question ?

**Comment by b-loved-dreamer** [comment]
Hi @crup. This repo is not an official replacement for the repository you referenced. You can learn more about ```Fulfillment``` in the [documentation](https://cloud.google.com/dialogflow/es/docs/quick/fulfillment) page. 

Additionally, if you want to do any fulfillment-related setup, you can click on the Fulfillment panel on your DialogFlow [Dashboard](https://dialogflow.cloud.google.com/#/agent/python-docs-samples-tests/fulfillment).

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
