### ISSUE TITLE
how dialogflow handle unsupervised learning query

### ISSUE THREAD

**Issue by DhruvMevada** [googleapis/nodejs-dialogflow#82]
If I enter the query in dialogflow which is out of the scope, then how the dialogflow will handle it?
Is there any unsupervised learning is there in dialogflow or not?

Thanks!

**Comment by nnegrey** [comment]
I believe that falls under the [Default Fallback Intent](https://dialogflow.com/docs/intents/default-intents#default_fallback_intent)

Also having more [Training Phrases](https://dialogflow.com/docs/intents/training-phrases) should help as well. 

Does that help answer the question? :)

**Comment by nnegrey** [comment]
You can also create Fallback Intents with [is_fallback in a Intent](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#intent)
