### ISSUE TITLE
Dialogflow with contexts

### ISSUE THREAD

**Issue by saikrishna321** [googleapis/nodejs-dialogflow#846]
Hi Team,

I'm trying on implementing hangout bot with dialogflow and one of the intent required certain fields. I can't find sample around on how to use the same sessionID from the first requests. 

Current implementation:

```
export async function dialogflowDetectIntent(projectId, userMessage) {
  const sessionClient = new dialogflow.SessionsClient({ fallback: true });
  const sessionPath = sessionClient.projectAgentSessionPath(
    projectId,
    sessionId
  );
  console.log('Session Path', sessionPath);
  const request = {
    session: sessionPath,
    queryInput: {
      text: {
        text: userMessage,
        languageCode: 'en-US',
      },
    },
  };
  console.log('Inside detect intent');
  const responses = await sessionClient.detectIntent(request);
  console.log('Detected intent');
  const result = responses[0].queryResult;
  console.log(`  Query: ${result.queryText}`);
  console.log(`  Response: ${result.fulfillmentText}`);
  if (result.intent) {
    console.log(`  Intent: ${result.intent.displayName}`);
  } else {
    console.log('  No intent matched.');
  }
  console.log(JSON.stringify(result));
  return {
    result,
    fulfillmentText: result.fulfillmentText,
    intent: result.intent.displayName,
  };
}

```

Usage
```
Bot - dialogflowDetectIntent('projectID', 'What are the next holidays?') 
Response: Do you want to know on Public or Optional?
User: Public (dialogflowDetectIntent('projectID', 'Public') ) In this place it goes as new request as the sessionId is created again.
```

How to use the sessionID which is already a part of the outputcontexts?

**Comment by b-loved-dreamer** [comment]
Hi @saikrishna321. I think you need to handle potential conversation turns in your ```dialogflow''' experience based on the context with the end user. Are you using follow-up intents?

From the docs: 

>A session represents a conversation between a Dialogflow agent and an end-user. You create a session at the beginning of a conversation and use it for each turn of the conversation. Once the conversation has ended, you discontinue using the session.

https://cloud.google.com/dialogflow/es/docs/contexts-follow-up-intents
https://cloud.google.com/dialogflow/es/docs/api-overview?hl=en
https://www.youtube.com/watch?v=-tOamKtmxdY

**Comment by saikrishna321** [comment]
@b-loved-dreamer Thanks for quick response. I'm using Liner Dialogs and currently I'm able to get it working by setting a sessionID for the entire session. For Ex:


User: When is the next holiday? -> Unique sessionID is generated using the userID which is 36byte
Bot: Are you looking for Public or Optional Holiday? 
User: Public
Bot: Response

For all the request to Dialogflow I'm using the same sessionID created.

Now for the next set of conversation which is a new question, I still use the same sessionID. Is this is the right approach or would there be any side effects as the same sessionID is used for the entire session.

**Comment by b-loved-dreamer** [comment]
You should be able to use the session through the life of the conversation.  Once the conversations ends, you discontinue using the session.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
