### ISSUE TITLE
Unable to update environment with new agent version

### ISSUE THREAD

**Issue by leesus** [googleapis/nodejs-dialogflow#863]
I am unable to update the published agent version of a custom environment using the EnvironmentsClient `updateEnvironment` method, I get an error that the update mask is referencing output only field `agentVersion`. Promoting an agent version using the REST API or with the old `googleapis` dialogflow library work correctly (`projects.agent.environments.patch`).

#### Environment details

  - OS: macOS 11.5.1
  - Node.js version: 14.16.1
  - npm version: 7.0.3
  - `@google-cloud/dialogflow` version: 4.1.0

#### Steps to reproduce

  1. Make a request:
  ```
  const environmentsClient = new EnvironmentsClient({
    credentials: SERVICE_ACCOUNT_KEY,
    projectId: 'some-project-id'
  });

  const [updatedEnvironment] = await environmentsClient.updateEnvironment({
    environment: {
      agentVersion: 'path/to/agent/version',
      name: 'environment-name'
    },
    updateMask: {
      paths: ['agentVersion']
    }
  });
  ```
  2. Observe errror message:
  ```
Error: 3 INVALID_ARGUMENT: com.google.apps.framework.request.BadRequestException: Update mask contains output only fields: [agentVersion].
    at Object.callErrorFromStatus (/Users/me/my-project/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/me/my-project/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/Users/me/my-project/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/me/my-project/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/me/my-project/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:75:11) {
  code: 3,
  details: 'com.google.apps.framework.request.BadRequestException: Update mask contains output only fields: [agentVersion].',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

**Comment by b-loved-dreamer** [comment]
Hi @leesus — thank you for filing this issue. Documentation about the ```updateMask``` can be found [here](https://cloud.google.com/dialogflow/es/docs/how/field-mask#node.js). An ```agentVersion``` cannot be updated through this API call, ```updateEnvironment```. The ```updateMask``` field does not allow you to update the agent version because there is a separate/different API call you need to make to edit an agent version, as these are two separate entities that work together. 

If you want to update an agent version, please check this [doc page](https://googleapis.dev/nodejs/dialogflow/latest/v2beta1.VersionsClient.html#updateVersion).

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
