### ISSUE TITLE
Get History of Conversations

### ISSUE THREAD

**Issue by SasikiranJ** [googleapis/nodejs-dialogflow#901]
Hi , I want to get History of conversations from dialogflow. Is there anyway i can get them?

**Comment by kweinmeister** [comment]
Hi @SasikiranJ, there is currently not an API for that, but this [StackOverflow answer](https://stackoverflow.com/questions/55377439/is-there-a-way-to-retrieve-the-conversation-history-in-dialogflow) shows how to do it via logging.
