### ISSUE TITLE
Detect intent with text issue with knowledgebase

### ISSUE THREAD

**Issue by poshakjaiswal** [googleapis/nodejs-dialogflow#902]
Environment details
OS: OS X 11.6
Node.js version: v12.18.3
npm version: 6.14.6
@google-cloud/dialogflow version: 3.3.0

Steps to reproduce
1.create an intent with few training phrases.
2.Create a knowledge-base and add few documents with matching phrases(Question) to the intent created in step 1.
3. Even after not specifying the knowledge base in the detect intent call as a parameter the detect intent returns the answer from the knowledgebase.
  
Is there a way with which we can just query a particular knowledge-base instead of making a global detect intent call.

async function detectIntentKnowledge(
  projectId,
  sessionId,
  languageCode,
  knowledgeBaseId,
  query
) {
  // [START dialogflow_detect_intent_knowledge]
  // Imports the Dialogflow client library
  const dialogflow = require('@google-cloud/dialogflow').v2beta1;
  // Instantiate a DialogFlow client.
  const sessionClient = new dialogflow.SessionsClient();

  /**
   * TODO(developer): Uncomment the following lines before running the sample.
   */
  // const projectId = 'ID of GCP project associated with your Dialogflow agent';
  // const sessionId = `user specific ID of session, e.g. 12345`;
  // const languageCode = 'BCP-47 language code, e.g. en-US';
  // const knowledgeBaseId = `the ID of your KnowledgeBase`;
  // const query = `phrase(s) to pass to detect, e.g. I'd like to reserve a room for six people`;

  // Define session path
  const sessionPath = sessionClient.projectAgentSessionPath(
    projectId,
    sessionId
  );
  const knowledgeBasePath =
    'projects/' + projectId + '/knowledgeBases/' + knowledgeBaseId + '';

  // The audio query request
  const request = {
    session: sessionPath,
    queryInput: {
      text: {
        text: query,
        languageCode: languageCode,
      },
    },
    queryParams: {
      knowledgeBaseNames: [knowledgeBasePath],
    },
  };

  const responses = await sessionClient.detectIntent(request);
  const result = responses[0].queryResult;
  console.log(`Query text: ${result.queryText}`);
  console.log(`Detected Intent: ${result.intent.displayName}`);
  console.log(`Confidence: ${result.intentDetectionConfidence}`);
  console.log(`Query Result: ${result.fulfillmentText}`);
  if (result.knowledgeAnswers && result.knowledgeAnswers.answers) {
    const answers = result.knowledgeAnswers.answers;
    console.log(`There are ${answers.length} answer(s);`);
    answers.forEach(a => {
      console.log(`   answer: ${a.answer}`);
      console.log(`   confidence: ${a.matchConfidence}`);
      console.log(`   match confidence level: ${a.matchConfidenceLevel}`);
    });
  }
  // [END dialogflow_detect_intent_knowledge]
}

**Comment by rokity** [comment]
Read about [this ](https://cloud.google.com/dialogflow/es/docs/knowledge-connectors), I think that it's what are you searching. 

Check this [sample ](https://github.com/googleapis/nodejs-dialogflow/blob/05ea702372c08d0f0f157419799e59ea983df32a/samples/detect.v2beta1.js)for NodeJS reference.

**Comment by kweinmeister** [comment]
The issue in this repo are for problems with the client library itself. Since there doesn't appear to be a bug with the library, we'll go ahead and close the issue. Please feel free to reopen if you have more information.
