### ISSUE TITLE
Couldn't update Dialogflow Fulfillment using FulfillmentsClient.updateFulfillment

### ISSUE THREAD

**Issue by foxik384** [googleapis/nodejs-dialogflow#904]
#### Environment details

  - OS: Kubuntu Linux 20.04 (Kernel Version 5.10.0-1050-oem)
  - Node.js version: v16.13.0
  - npm version: 8.1.0
  - `@google-cloud/dialogflow` version: 4.5.0

#### Steps to reproduce

  1. Create a service account with *Dialogflow API Admin role* in Google Cloud and get credentials in JSON format
  2. Create index.js with the following content and run it:
```javascript
const dialogflow = require('@google-cloud/dialogflow');

const updateFulfillment = async (credentialsPath, projectId) => {
  const client = new dialogflow.FulfillmentsClient({ keyFilename: credentialsPath });
  const fulfillmentPath = client.projectAgentFulfillmentPath(projectId);
  const [fulfillment] = await client.getFulfillment({ name: fulfillmentPath });

  // Before update
  console.log(fulfillment.genericWebService);
  
  const [newFulfillment] = await client.updateFulfillment({ 
    fulfillment: {
      name: fulfillment.name,
      genericWebService: {
        uri: 'https://example.com',
        username: 'test',
        password: 'password'
      }
    }, updateMask: {
      paths: ['genericWebService']
    }});

  // After update
  console.log(newFulfillment.genericWebService);
};

updateFulfillment('/path/to/service/account/credentials.json', 'dummy-project');
```

#### Actual result

The output from two `console.log` invocations is the same. The fulfillment values haven't updated.

#### Expected result

The output from two `console.log` invocations should differ. The fulfillment values should be updated.

#### Notes

In Google Cloud stack driver logs I can see the update request.
It actually works if you use Python SDK for Dialogflow. But for some reason, It didn't work for NodeJS.

Could you explain why is not possible to update Dialogflow Fulfillment using this library?

**Comment by foxik384** [comment]
Sorry, the script from the issue shouldn't work because Dialogflow requires to specify valid URI for genericWebService. The following one should work and the issue should be reproduced on it:
```javascript
const dialogflow = require('@google-cloud/dialogflow');

const updateFulfillment = async (credentialsPath, projectId) => {
  const client = new dialogflow.FulfillmentsClient({ keyFilename: credentialsPath });
  const fulfillmentPath = client.projectAgentFulfillmentPath(projectId);
  const [fulfillment] = await client.getFulfillment({ name: fulfillmentPath });

  // Before update
  console.log(fulfillment.genericWebService);
  
  const [newFulfillment] = await client.updateFulfillment({ 
    fulfillment: {
      name: fulfillment.name,
      genericWebService: {
        uri: 'https://example.com',
        username: 'test',
        password: 'password'
      }
    }, updateMask: {
      paths: ['genericWebService']
    }});

  // After update
  console.log(newFulfillment.genericWebService);
};

updateFulfillment('/path/to/service/account/credentials.json', 'dummy-project-id');
```

**Comment by SmiffyKMc** [comment]
I'm currently having this issue also like above. You are unable to update any fields in the fulfillment.

**Comment by SmiffyKMc** [comment]
I think I fixed the issue. The documentation doesn't really explain to well in the example how to update the values. You need to make the fields to be changed like so:

```
{
    paths: ["enabled", "display_name", "generic_web_service"]
}
```

**Comment by foxik384** [comment]
Hello @SmiffyKMc ,

Yes, you are right. By changing `genericWebService` to `generic_web_service` I can update fulfillment values.

Thank you for your comment.
I close this issue as it was fixed.
