### ISSUE TITLE
Context Setting in DialogFlow version 2 not working

### ISSUE THREAD

**Issue by sganeshkumar** [googleapis/nodejs-dialogflow#92]
I have some doubt in context setting in dialogflow. In version 1 I have achieved the context through this code. But I don't know how can I achieve context settings in Dialgflow version 2. Please guide me.
```js
unirest.post("https://api.api.ai/v1/contexts?sessionId=" + contextInfo.sessionID)
      .set('Content-Type', 'application/json')
      .header("Authorization", "Bearer " + global.config.DEVELOPER_TOKEN)
      .send(contextInfo.contextInfo)
      .end(function (response) {
        console.log(response.body);
        m_callback("",response.body)
      })
```

**Comment by pskirko-google** [comment]
First, be sure to read how Contexts work in the v2 API:

https://dialogflow.com/docs/contexts

You can create contexts using the CreateContext method:

https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Contexts.CreateContext

If you want to specify the input contexts for a DetectIntent request, you do so by passing the contexts in the QueryParameters object:

https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.QueryParameters

Please try those API methods, after reading the v2 Contexts doc, and see if that works. Thanks.
