### ISSUE TITLE
Support updating `agentVersion` by `EnvironmentsClient.updateEnviornment()`

### ISSUE THREAD

**Issue by lrills** [googleapis/nodejs-dialogflow#924]
Basically it's the same as #863, since it's closed somehow. Updating `agentVersion` is supported by the API now, please check this thread:
https://issuetracker.google.com/issues/153750593?pli=1

For now, I'm using this workaround:
```js
await environmentsClient.auth.request({
  url: `https://dialogflow.googleapis.com/v2/${environment.name}`,
  method: 'PATCH',
  params: { updateMask: 'agentVersion' },
  data: {
    agentVersion: version.name,
  },
});
```
It seems to work at the API side.

**Comment by rokity** [comment]
So it works at API side but not with nodejs library ? 

If I understand the problem.

Thanks

**Comment by rokity** [comment]
The [#863](https://github.com/googleapis/nodejs-dialogflow/issues/863) it was reopened by your mention so now it's reopened.

**Comment by kweinmeister** [comment]
Hi @lrills, I believe that this feature is now in the library. Here is a sample that shows its use: https://github.com/googleapis/nodejs-dialogflow/blob/main/samples/generated/v2/environments.update_environment.js

Can you confirm it's now working for you please?

**Comment by kweinmeister** [comment]
As we haven't heard back on this issue, we'll go ahead and close it. Please feel free to reopen if you have more information. Thanks!
