### ISSUE TITLE
https://cloud.google.com/conversation/docs   Docs page returns 404 error page

### ISSUE THREAD

**Issue by prateekkembhavi** [googleapis/nodejs-dialogflow#95]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/dialogflow/dialogflow-nodejs-client-v2/issues
  - Search the issues on our "catch-all" repository: https://github.com/GoogleCloudPlatform/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `dialogflow` version:

#### Steps to reproduce

  1. ???
  2. ???

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by prateekkembhavi** [comment]
are there no docs for the standard version?

**Comment by JustinBeckwith** [comment]
For the community docs, please check out https://dialogflow.com/docs
