### ISSUE TITLE
`v2beta1.Sessions.StreamingDetectIntent` latency and error rate are very high

### ISSUE THREAD

**Issue by AhmadIbrahiim** [googleapis/nodejs-dialogflow#956]
Hello, We're noticing a significant delay between detecting the intent and receiving the audio buffer, Sometime it goes above 10s.

Once we stepped out to GCP API/Service details we saw that: 
![image](https://user-images.githubusercontent.com/17949497/169040442-14eb59be-34c8-432c-bed9-7907f53b5a56.png)

AVG latency is going close to 10s and the error rate is very high as well! 

This is sample of DF response code : 
![image](https://user-images.githubusercontent.com/17949497/169040693-04d9e286-6818-465c-9059-e20c2bd599c9.png)

Debugging this API is very hard because we're using it with a media stream which uses gRPC not reset!

Any idea to help us debug this issue is really appreciated.

**Comment by sofisl** [comment]
Hello! We are moving this repo to googleapis/google-cloud-node, and are closing any stale issues. If this issue is persisting for you, we kindly ask that you reopen in that repo. Thank you very much!
