### ISSUE TITLE
queryResult on WebhookRequest defined as optional - why?

### ISSUE THREAD

**Issue by luxterful** [googleapis/nodejs-dialogflow#969]
### My question is related to the typescript types in this library
In the [specification](https://cloud.google.com/nodejs/docs/reference/dialogflow/latest/dialogflow/protos.google.cloud.dialogflow.v2.webhookrequest#_google_cloud_dialogflow_protos_google_cloud_dialogflow_v2_WebhookRequest_queryResult_member) for WebhookRequest it says that the **queryResult** parameter is possibly undefined. But i never encountered this scenario (that there is no queryResult). Could you tell me the scenario why this is defined as possibly undefined?

Otherwise i was wondering if it would make sense to define it as not possibly undefined?

ALSO: in [this documentation page](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2beta1/WebhookRequest) it is NOT marked as "optional" as it does for originalDetectIntentRequest

**Comment by sofisl** [comment]
Hello! We are moving this repo to googleapis/google-cloud-node, and are closing any stale issues. If this issue is persisting for you, we kindly ask that you reopen in that repo. Thank you very much!
