### ISSUE TITLE
Is there a clean way to convert a JSON object to a struct?

### ISSUE THREAD

**Issue by maximelebastard** [googleapis/nodejs-dialogflow#97]
Hi,

When creating a context, I'd like to pass parameters. 

As seen in [this sample](https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/d907f3af57438c3e88c274b100eab520b5b51062/samples/resource.js#L889), I need to convert my Javascript object to a Google protobuf.struct.

The way it's done into the example is by creating and using the [structjson.js helper](https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/samples/structjson.js), but it's not available from the dependency and it's not an official API.

Well, I can copy this structjson.js into my project and use it - but is there any versioned npm dependency that can do that ? Or do you plan to create an official structjson API into the lib ?

Thank you

**Comment by pierrefaure** [comment]
Also interested 🤔

**Comment by MumblesNZ** [comment]
+1 interested in this, I'm wanting to go the other way, protobuf.struct to javascript object.

**Comment by kopiro** [comment]
Up

**Comment by RezaRahmati** [comment]
@kinwa91 any update on this?

**Comment by callmehiphop** [comment]
@JustinBeckwith @alexander-fenster It seems like maybe the gapics themselves could benefit from simple encode/decode methods for `google.protobuf` values. Thoughts?

**Comment by alexander-fenster** [comment]
I wonder if `protobufjs` (that we use for reading proto files when loading, so it is always in `node_modules`) has a way of doing that (I don't know right now but would expect it to have something). I will look into this.

**Comment by callmehiphop** [comment]
Hey everyone, I've published a small utility module ([pb-util](https://www.npmjs.com/package/pb-util)) that you can use to easily encode/decode structs while we figure out a better solution that is native to the client.

```js
const {struct} = require('pb-util');

// encode a struct
const structValue = struct.encode({foo: 'bar'});
// {
//   fields: {
//     foo: {
//       kind: 'stringValue',
//       stringValue: 'bar'
//     }
//   }
// }

// decode a struct
const json = struct.decode({
  fields: {
    foo: {
      kind: 'stringValue',
      stringValue: 'bar'
    }
  }
});
// {foo: 'bar'}
```

**Comment by bcoe** [comment]
@maximelebastard  could you confirm that @callmehiphop's utility did the trick for you?

**Comment by maximelebastard** [comment]
Hi @bcoe, this is a quite old ticket and we don't use this library anymore. But happy to ear that it was resolved for future users thanks to @callmehiphop !

**Comment by bcoe** [comment]
@maximelebastard thanks for the quick feedback, closing the issue as an interesting historical artifact 😛

**Comment by robbyemmert** [comment]
Why is this closed? Are you officially supporting pb-util?

**Comment by callmehiphop** [comment]
@robbyemmert unfortunately I don't think this is a problem for the dialogflow client to solve. I would suggest subscribing to https://github.com/protobufjs/protobuf.js/issues/839 instead.
