### ISSUE TITLE
Cloud function that can point to different environments for testing.

### ISSUE THREAD

**Issue by markwindsorr** [googleapis/nodejs-dialogflow#975]
Hi, I have a cloud function that handles the dialogflow detect intent request. I have 2 custom environments on my dialogflow account (dev and prod) and am wondering where in my cloud function would I specify which environment to point too so I can test changes locally

**Comment by sofisl** [comment]
Hello! We are moving this repo to googleapis/google-cloud-node, and are closing any stale issues. If this issue is persisting for you, we kindly ask that you reopen in that repo. Thank you very much!
